"""Historical bd release binaries for Bazel tests, pinned by the release catalog.

scripts/migration-test/release-catalog.json is the reviewed universe of
historical releases. Every version in it whose GitHub release records a
linux_amd64 asset (github_release.linux_amd64_asset: name and sha256 digest)
becomes one repository, bd_release_<version>, holding that release's `bd`.
Nothing is downloaded until a test declares the binary as data, and the
download is verified against the catalog's digest, so tests that run historical
releases need no network and no checksum code of their own.

Tests use the hub repository, @bd_releases:

    data = ["@bd_releases//:v0.49.6"],
    env = {"BD": "$(rlocationpath @bd_releases//:v0.49.6)"},

and @bd_releases//:versions.bzl lists every pinned version (VERSIONS), so a
BUILD file can generate one target per release.

Adding a release is a catalog change (regenerate it with
scripts/migration-test/catalog); this file and MODULE.bazel stay as they are.

The catalog pins linux/amd64 assets only: a test that runs one sets
target_compatible_with = LINUX_AMD64 (from this file), so `bazel build //...`
skips it on other hosts.
"""

_RELEASE_URL = "https://github.com/gastownhall/beads/releases/download/{version}/{asset}"

_RELEASE_BUILD = """\
package(default_visibility = ["//visibility:public"])

exports_files(["bd"])
"""

# target_compatible_with for a test that runs a pinned release.
LINUX_AMD64 = [
    "@platforms//os:linux",
    "@platforms//cpu:x86_64",
]

def _bd_release_impl(rctx):
    rctx.download_and_extract(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        # Ties the repository-cache entry to this URL (and so this version).
        canonical_id = rctx.attr.url,
    )
    if not rctx.path("bd").exists:
        fail("release asset {} holds no top-level bd binary".format(rctx.attr.url))
    rctx.file("BUILD.bazel", _RELEASE_BUILD)

bd_release = repository_rule(
    implementation = _bd_release_impl,
    attrs = {
        "sha256": attr.string(mandatory = True, doc = "sha256 of the release archive."),
        "url": attr.string(mandatory = True, doc = "Release archive URL."),
    },
    doc = "Downloads one historical bd release archive and exports its `bd` binary.",
)

def _repo_name(version):
    return "bd_release_" + version.replace(".", "_").replace("-", "_")

def _hub_impl(rctx):
    lines = [
        "# Generated by tools/bazel/bd_releases.bzl from the release catalog.",
        "package(default_visibility = [\"//visibility:public\"])",
        "",
        "exports_files([\"versions.bzl\"])",
        "",
    ]
    for version in rctx.attr.versions:
        lines.append("""alias(
    name = "{version}",
    actual = "@{repo}//:bd",
)
""".format(version = version, repo = _repo_name(version)))
    rctx.file("BUILD.bazel", "\n".join(lines))
    rctx.file("versions.bzl", "\n".join([
        "\"\"\"Every historical bd release @bd_releases pins (from the release catalog), oldest first.\"\"\"",
        "",
        "VERSIONS = [",
    ] + ["    \"{}\",".format(v) for v in rctx.attr.versions] + ["]", ""]))

_bd_releases_hub = repository_rule(
    implementation = _hub_impl,
    attrs = {
        "versions": attr.string_list(mandatory = True),
    },
    doc = "Hub repository: one alias per pinned release, plus versions.bzl.",
)

def catalog_releases(catalog):
    """Returns [(version, asset name, sha256)] for every catalog release with a linux_amd64 asset.

    Args:
      catalog: the decoded release-catalog.json.

    Returns:
      A list of (version, asset, sha256) tuples in catalog order.
    """
    releases = []
    for entry in catalog["versions"]:
        asset = entry.get("github_release", {}).get("linux_amd64_asset")
        if asset == None:
            continue
        digest = asset["digest"]
        if not digest.startswith("sha256:"):
            fail("release {}: asset digest {} is not sha256".format(entry["version"], digest))
        releases.append((entry["version"], asset["name"], digest[len("sha256:"):]))
    return releases

def _bd_releases_impl(mctx):
    catalogs = [tag.path for mod in mctx.modules if mod.is_root for tag in mod.tags.catalog]
    if len(catalogs) != 1:
        fail("bd_releases needs exactly one catalog tag in the root module, got {}".format(len(catalogs)))
    catalog = json.decode(mctx.read(catalogs[0]))
    versions = []
    for version, asset, sha256 in catalog_releases(catalog):
        bd_release(
            name = _repo_name(version),
            url = _RELEASE_URL.format(version = version, asset = asset),
            sha256 = sha256,
        )
        versions.append(version)
    _bd_releases_hub(name = "bd_releases", versions = versions)
    return mctx.extension_metadata(
        root_module_direct_deps = ["bd_releases"],
        root_module_direct_dev_deps = [],
        reproducible = True,
    )

bd_releases = module_extension(
    implementation = _bd_releases_impl,
    tag_classes = {
        "catalog": tag_class(attrs = {
            "path": attr.label(mandatory = True, doc = "The release catalog JSON."),
        }),
    },
    doc = "Declares one repository per historical bd release in the release catalog, and the @bd_releases hub.",
)
