#!/usr/bin/env python3
"""Write a pinned-shard manifest for tools/bazel/go_test_pinned_shard.sh.

Usage: pin_shards.py --shards P --min-seconds S [--write MANIFEST] TESTLOGS...

TESTLOGS are a sharded test's bazel-testlogs directories (each holding
shard_*_of_*/test.xml, or one test.xml), from one or more runs. Every
top-level <testcase> (a name without "/") at or above S seconds in any run is
pinned: its duration is the maximum seen, and the tests are bin-packed
longest-processing-time first onto P shards. Every other test stays in the
binary's own round-robin shards. Without --write the manifest is printed.

The durations come from the test.xml -test.v writes (GO_TEST_WRAP_TESTV=1, as
--config=doltserver-cmd sets), so regenerate from a run of the lane itself:

    bazel test //cmd/bd:bd_dolt_server_test --config=doltserver-cmd
    python3 tools/bazel/pin_shards.py --shards 16 --min-seconds 5 \\
        --write cmd/bd/dolt_server_pinned_shards.txt \\
        bazel-testlogs/cmd/bd/bd_dolt_server_test

Exit status: 0 on success, 1 on bad input (no test.xml, fewer pinned tests
than shards).
"""

import argparse
import glob
import os
import sys
import xml.etree.ElementTree as ET


def durations(testlogs_dirs):
    """Return {top-level test name: max seconds} over every test.xml."""
    out = {}
    for d in testlogs_dirs:
        paths = sorted(glob.glob(os.path.join(d, "shard_*_of_*", "test.xml")))
        if not paths and os.path.exists(os.path.join(d, "test.xml")):
            paths = [os.path.join(d, "test.xml")]
        if not paths:
            raise ValueError(f"{d}: no test.xml")
        for p in paths:
            for tc in ET.parse(p).getroot().iter("testcase"):
                name = tc.get("name") or ""
                if not name.startswith("Test") or "/" in name:
                    continue
                secs = float(tc.get("time") or 0)
                out[name] = max(out.get(name, 0.0), secs)
    return out


def pin(durs, shards, min_seconds):
    """Bin-pack the tests >= min_seconds onto shards (LPT). Returns a list of
    (shard number 1..shards, [(name, secs)...]) and the per-shard totals."""
    heavy = sorted(
        ((n, s) for n, s in durs.items() if s >= min_seconds),
        key=lambda ns: (-ns[1], ns[0]),
    )
    if len(heavy) < shards:
        raise ValueError(f"{len(heavy)} tests take >= {min_seconds}s, fewer than {shards} shards")
    bins = [[] for _ in range(shards)]
    totals = [0.0] * shards
    for name, secs in heavy:
        k = min(range(shards), key=lambda i: (totals[i], i))
        bins[k].append((name, secs))
        totals[k] += secs
    return bins, totals


def render(bins, totals, min_seconds, rest):
    lines = [
        "# Pinned shards for tools/bazel/go_test_pinned_shard.sh. Generated by",
        "# tools/bazel/pin_shards.py; regenerate rather than edit (see its usage).",
        "#",
        f"# Every top-level test measured at >= {min_seconds:g}s, bin-packed",
        "# longest-first onto these shards; every other test runs in the",
        "# binary's own round-robin shards. Measured seconds per pinned shard:",
        "# " + " ".join(f"{t:.0f}" for t in totals),
        f"# Unpinned tests: {rest[0]}, {rest[1]:.0f}s in total.",
        "#",
        "# <pinned shard> <TestName>",
    ]
    for k, tests in enumerate(bins, start=1):
        for name, _ in sorted(tests):
            lines.append(f"{k} {name}")
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--shards", type=int, required=True)
    ap.add_argument("--min-seconds", type=float, required=True)
    ap.add_argument("--write")
    ap.add_argument("testlogs", nargs="+")
    args = ap.parse_args(argv)
    if args.shards < 1:
        print("--shards must be at least 1", file=sys.stderr)
        return 1
    try:
        durs = durations(args.testlogs)
        bins, totals = pin(durs, args.shards, args.min_seconds)
    except (ValueError, OSError, ET.ParseError) as e:
        print(f"pin_shards.py: {e}", file=sys.stderr)
        return 1
    rest = [s for s in durs.values() if s < args.min_seconds]
    text = render(bins, totals, args.min_seconds, (len(rest), sum(rest)))
    if args.write:
        tmp = args.write + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, args.write)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
