package workapi

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/steveyegge/beads/issueops"
)

type listFilterGoldenCase struct {
	Name   string               `json:"name"`
	Params issueops.ListRequest `json:"params"`
	Config ListConfig           `json:"config"`
	Filter json.RawMessage      `json:"filter"`
	Error  string               `json:"error,omitempty"`
}

// TestBuildListFilterGolden replays the filter table recorded from cmd/bd's
// pre-extraction buildListFilter (bd-fv4). The golden was generated by the old
// builder before it was deleted, so a green run here is the proof that moving
// the logic into this package changed nothing — and it keeps pinning the
// filter shape for every later change to BuildListFilter.
//
// Two cases at the END of the file are NOT recorded: max_rows_cap and
// skip_counts pin fields that did not exist when the old builder did, so there
// was nothing to record them from. They pin what the leaf promises
// (issueops.ListRequest.MaxRows and .SkipCounts), which is the same standard
// the conformance contract holds the implementations to.
//
// ONE case has been deliberately RE-recorded rather than preserved:
// status_all_keyword's Pinned went false -> null. The old builder compared the
// raw selector string to "pinned"/"hooked", so --status=all — which promises
// EVERY status — silently kept forcing Pinned=false and hid pinned beads from
// the one selector that says it hides nothing. TestPinnedDefaultBySelector
// below owns that behavior now; see the PR body for the compatibility note.
func TestBuildListFilterGolden(t *testing.T) {
	blob, err := os.ReadFile(filepath.Join("testdata", "list_filter_golden.json"))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var cases []listFilterGoldenCase
	if err := json.Unmarshal(blob, &cases); err != nil {
		t.Fatalf("decode golden: %v", err)
	}
	// The golden is the oracle; an emptied or truncated file must fail loudly
	// rather than pass vacuously.
	if len(cases) < 30 {
		t.Fatalf("golden has %d cases, expected the full recorded table", len(cases))
	}

	seen := make(map[string]bool, len(cases))
	for _, c := range cases {
		if seen[c.Name] {
			t.Fatalf("duplicate golden case %q", c.Name)
		}
		seen[c.Name] = true

		t.Run(c.Name, func(t *testing.T) {
			filter, err := BuildListFilter(c.Params, c.Config)

			gotErr := ""
			if err != nil {
				gotErr = err.Error()
			}
			if gotErr != c.Error {
				t.Fatalf("error = %q, golden has %q", gotErr, c.Error)
			}

			got, err := json.Marshal(filter)
			if err != nil {
				t.Fatalf("marshal filter: %v", err)
			}
			var want bytes.Buffer
			if err := json.Compact(&want, c.Filter); err != nil {
				t.Fatalf("compact golden filter: %v", err)
			}
			if !bytes.Equal(got, want.Bytes()) {
				t.Errorf("filter differs from the recorded pre-extraction filter\n got: %s\nwant: %s", got, want.Bytes())
			}
		})
	}
}
