package workapi

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/steveyegge/beads/issueops"
)

type readyBuilderResult struct {
	Filter json.RawMessage `json:"filter,omitempty"`
	Error  string          `json:"error,omitempty"`
	Stderr string          `json:"stderr,omitempty"`
}

type readyFilterGoldenCase struct {
	Name   string                `json:"name"`
	Args   []string              `json:"args"`
	Params issueops.ReadyRequest `json:"params"`
	Direct readyBuilderResult    `json:"direct"`
	Gather readyBuilderResult    `json:"gather"`
}

func loadReadyFilterGolden(t *testing.T) []readyFilterGoldenCase {
	t.Helper()
	blob, err := os.ReadFile(filepath.Join("testdata", "ready_filter_golden.json"))
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var cases []readyFilterGoldenCase
	if err := json.Unmarshal(blob, &cases); err != nil {
		t.Fatalf("decode golden: %v", err)
	}
	// The golden is the oracle; an emptied or truncated file must fail loudly
	// rather than pass vacuously.
	if len(cases) < 35 {
		t.Fatalf("golden has %d cases, expected the full recorded table", len(cases))
	}
	return cases
}

// TestBuildReadyFilterGolden replays the filter table recorded from cmd/bd's
// two pre-collapse ready-filter builders (bd-ehi). The golden was generated by
// running both of them before either was deleted, so a green run here is the
// proof that collapsing them into this package changed nothing.
//
// EVERY RECORDED FILTER CARRIES "Lite": false, which the old builders could
// not have produced because types.WorkFilter had no such field. The record is
// of what each REQUEST resolves to, and false is what a request that did not
// ask for the projection resolves that field to, so writing it in keeps the
// replay exact rather than weakening it — the same absorption
// types.IssueFilter's MaxRows and SkipCounts had on the listing golden. A case
// that MEANT to set it would fail here, which is the property being kept.
//
// It replays the gatherReadyInput column: that is the builder both CLI paths
// now share, and it is the one whose output a filter can be built from for
// every case (the direct column stops at --max-rows, which stays in cmd/bd).
func TestBuildReadyFilterGolden(t *testing.T) {
	cases := loadReadyFilterGolden(t)

	seen := make(map[string]bool, len(cases))
	replayed := 0
	for _, c := range cases {
		if seen[c.Name] {
			t.Fatalf("duplicate golden case %q", c.Name)
		}
		seen[c.Name] = true

		if c.Gather.Filter == nil {
			// The old CLI rejected this command line before a filter existed.
			// Those rejections are flag-syntax and flag-name concerns that stay
			// in cmd/bd, so there is nothing recorded here to replay.
			continue
		}
		replayed++

		t.Run(c.Name, func(t *testing.T) {
			filter, err := BuildReadyFilter(c.Params)
			if err != nil {
				t.Fatalf("BuildReadyFilter: %v", err)
			}
			got, err := json.Marshal(filter)
			if err != nil {
				t.Fatalf("marshal filter: %v", err)
			}
			var want bytes.Buffer
			if err := json.Compact(&want, c.Gather.Filter); err != nil {
				t.Fatalf("compact golden filter: %v", err)
			}
			if !bytes.Equal(got, want.Bytes()) {
				t.Errorf("filter differs from the recorded pre-collapse filter\n got: %s\nwant: %s", got, want.Bytes())
			}
		})
	}

	if replayed < 30 {
		t.Fatalf("only %d cases produced a filter to replay, expected the bulk of the table", replayed)
	}
}

// TestReadyFilterGoldenDivergences pins the ways cmd/bd's two pre-collapse
// builders disagreed *in what the golden recorded*. The collapse had to keep
// one branch of each disagreement, so the list is the record of what was
// chosen and why - the alternative was absorbing them silently, which is how
// the two copies drifted in the first place.
//
// It is not the whole record, and cannot be. The golden was recorded with
// jsonOutput false, where HandleError and HandleErrorRespectJSON print the
// same stderr line, so the two builders' disagreement over which of those
// helpers reports a usage error is invisible here: every case where they
// differ shows identical stderr. That divergence - five usage errors on the
// proxied route that now emit a JSON error object on stdout for a --json
// caller instead of stderr text - is pinned by cmd/bd's
// TestGatherReadyInputUsageErrorsRespectJSON and by the proxied integration
// test json_usage_errors_are_json_on_stdout instead.
func TestReadyFilterGoldenDivergences(t *testing.T) {
	known := map[string]string{
		// Kept: gather's. The direct path rejects --offset > 0 before it
		// reaches a builder ("--offset is only supported under
		// --proxied-server"), so it never had an offset to set. Not
		// observable.
		"offset_positive":     "direct never sets Offset; its RunE rejects --offset upstream",
		"everything_together": "same as offset_positive: Offset only, via --offset 2",

		// Kept: direct's. --max-rows / BEADS_MAX_ROWS is a direct-path knob;
		// the proxied path rejects a live cap outright and deliberately
		// ignores it for --claim. cmd/bd resolves it and stamps it onto the
		// filter, so it stays out of the shared params.
		"max_rows_flag":     "direct sets MaxRows/MaxRowsSource; the proxied path has no cap to thread",
		"max_rows_negative": "direct validates --max-rows; the proxied RunE does that itself before gathering",

		// Kept: gather's. The direct RunE rejects this combination before
		// building anything, so its builder never saw it. Not observable.
		"claim_with_gated": "direct's RunE rejects --claim --gated upstream",

		// Kept: both. The rejection the gather builder recorded is about
		// --offset, which only the proxied route supports, so it moved to that
		// route's RunE instead of into the shared gatherer; `bd ready
		// --offset -1` still prints ready work on the direct route. See
		// cmd/bd's TestGatherReadyInputIgnoresNegativeOffset.
		"offset_negative": "gather rejects a negative --offset; direct silently ignored it",
	}

	for _, c := range loadReadyFilterGolden(t) {
		same := c.Direct.Error == c.Gather.Error &&
			c.Direct.Stderr == c.Gather.Stderr &&
			bytes.Equal(compactJSON(t, c.Direct.Filter), compactJSON(t, c.Gather.Filter))
		_, expected := known[c.Name]
		switch {
		case same && expected:
			t.Errorf("case %q is listed as a divergence but the two recorded builders agree", c.Name)
		case !same && !expected:
			t.Errorf("case %q: the two pre-collapse builders disagree and the difference is undocumented\ndirect: %s\ngather: %s",
				c.Name, mustMarshal(t, c.Direct), mustMarshal(t, c.Gather))
		}
	}
}

func compactJSON(t *testing.T, raw json.RawMessage) []byte {
	t.Helper()
	if raw == nil {
		return nil
	}
	var buf bytes.Buffer
	if err := json.Compact(&buf, raw); err != nil {
		t.Fatalf("compact: %v", err)
	}
	return buf.Bytes()
}

func mustMarshal(t *testing.T, v any) []byte {
	t.Helper()
	blob, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	return blob
}
