package telemetry

import (
	"context"
	"errors"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/issueops"
)

// roleAccessorNames is the seven-strong capability surface every storage
// decorator has to answer for. It is duplicated from the sibling test in
// internal/storage rather than shared because that package cannot import this
// one and this one's test helpers cannot be exported back.
var roleAccessorNames = []string{
	"IssueLifecycle",
	"IssueReader",
	"IssueRelations",
	"Commenter",
	"ReadyClaimer",
	"BatchCloser",
	"DependencyEditor",
}

// TestInstrumentedStorageDeclaresEveryRoleAccessor is the structural half of
// this decorator's conformance story.
//
// InstrumentedStorage embeds storage.DoltStorage for capability pass-through,
// so DELETING an accessor still compiles: the embedded interface supplies a
// promoted method with the same signature and every call on that role goes
// unspanned and untimed. Reflection catches it because the compiler reports a
// promoted method's implementation as living in "<autogenerated>".
func TestInstrumentedStorageDeclaresEveryRoleAccessor(t *testing.T) {
	decorator := reflect.TypeOf(&InstrumentedStorage{})
	for _, name := range roleAccessorNames {
		method, ok := decorator.MethodByName(name)
		if !ok {
			t.Errorf("%s has no %s accessor at all", decorator, name)
			continue
		}
		file, _ := runtime.FuncForPC(method.Func.Pointer()).FileLine(method.Func.Pointer())
		if strings.Contains(file, "<autogenerated>") {
			t.Errorf("%s.%s is promoted from the embedded store, not declared on the decorator: "+
				"every call on that role goes unspanned", decorator, name)
		}
	}
}

// roleAccessorStore is a DoltStorage whose only real methods are the seven role
// accessors, each answering with a distinguishable sentinel so a test can tell
// an instrumented surface from a passed-through one.
type roleAccessorStore struct {
	storage.DoltStorage
	surface *roleAccessorSentinel
	err     error
}

func (s *roleAccessorStore) IssueLifecycle() (issueops.Lifecycle, error) { return s.surface, s.err }
func (s *roleAccessorStore) IssueReader() (issueops.Reader, error)       { return s.surface, s.err }
func (s *roleAccessorStore) IssueRelations() (issueops.Relations, error) { return s.surface, s.err }
func (s *roleAccessorStore) Commenter() (issueops.Commenter, error)      { return s.surface, s.err }
func (s *roleAccessorStore) ReadyClaimer() (issueops.ReadyClaimer, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) BatchCloser() (issueops.BatchCloser, error) { return s.surface, s.err }
func (s *roleAccessorStore) DependencyEditor() (issueops.DependencyEditor, error) {
	return s.surface, s.err
}

// roleAccessorSentinel implements all seven roles at once. Nothing calls its
// methods; identity is the whole point.
type roleAccessorSentinel struct{}

func (*roleAccessorSentinel) Create(context.Context, issueops.CreateRequest) (issueops.CreateResult, error) {
	return issueops.CreateResult{}, nil
}
func (*roleAccessorSentinel) Update(context.Context, issueops.UpdateRequest) (issueops.UpdateResult, error) {
	return issueops.UpdateResult{}, nil
}
func (*roleAccessorSentinel) Close(context.Context, issueops.CloseRequest) (issueops.CloseResult, error) {
	return issueops.CloseResult{}, nil
}
func (*roleAccessorSentinel) Reopen(context.Context, issueops.ReopenRequest) (issueops.ReopenResult, error) {
	return issueops.ReopenResult{}, nil
}
func (*roleAccessorSentinel) Ready(context.Context, issueops.ReadyRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}
func (*roleAccessorSentinel) List(context.Context, issueops.ListRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}
func (*roleAccessorSentinel) Get(context.Context, issueops.GetRequest) (*issueops.IssueDetails, error) {
	return nil, nil
}
func (*roleAccessorSentinel) Related(context.Context, issueops.RelatedRequest) ([]*issueops.RelatedIssue, error) {
	return nil, nil
}
func (*roleAccessorSentinel) AddComment(context.Context, issueops.AddCommentRequest) (issueops.AddCommentResult, error) {
	return issueops.AddCommentResult{}, nil
}
func (*roleAccessorSentinel) ClaimNext(context.Context, issueops.ClaimNextRequest) (issueops.ClaimNextResult, error) {
	return issueops.ClaimNextResult{}, nil
}
func (*roleAccessorSentinel) CloseBatch(context.Context, issueops.CloseBatchRequest) (issueops.CloseBatchResult, error) {
	return issueops.CloseBatchResult{}, nil
}
func (*roleAccessorSentinel) AddDependencies(context.Context, issueops.AddDependenciesRequest) (issueops.AddDependenciesResult, error) {
	return issueops.AddDependenciesResult{}, nil
}
func (*roleAccessorSentinel) RemoveDependency(context.Context, issueops.RemoveDependencyRequest) (issueops.RemoveDependencyResult, error) {
	return issueops.RemoveDependencyResult{}, nil
}

// TestInstrumentedStorageInstrumentsEveryRoleAccessor catches what reflection
// cannot: an accessor that IS declared but reads
// `return s.Unwrap().Commenter()`. That edit compiles, keeps satisfying
// DoltStorage, and silently drops every span and timing on that role.
//
// Unlike the hook decorator, this one has no read-role exemption: telemetry
// spans reads as well as writes, so ALL SEVEN must come back wrapped. Only
// IssueLifecycle and IssueReader had a recursion pin of their own before this
// test; the other five wrappers had no test at all.
func TestInstrumentedStorageInstrumentsEveryRoleAccessor(t *testing.T) {
	t.Setenv("BD_OTEL_STDOUT", "true")
	sentinel := &roleAccessorSentinel{}
	inner := &roleAccessorStore{surface: sentinel}
	wrapped, ok := WrapStorage(inner).(*InstrumentedStorage)
	if !ok {
		t.Fatal("WrapStorage did not instrument the store; telemetry is disabled in this environment")
	}

	for _, test := range []struct {
		name string
		got  func() (any, error)
	}{
		{"IssueLifecycle", func() (any, error) { return wrapped.IssueLifecycle() }},
		{"IssueReader", func() (any, error) { return wrapped.IssueReader() }},
		{"IssueRelations", func() (any, error) { return wrapped.IssueRelations() }},
		{"Commenter", func() (any, error) { return wrapped.Commenter() }},
		{"ReadyClaimer", func() (any, error) { return wrapped.ReadyClaimer() }},
		{"BatchCloser", func() (any, error) { return wrapped.BatchCloser() }},
		{"DependencyEditor", func() (any, error) { return wrapped.DependencyEditor() }},
	} {
		t.Run(test.name, func(t *testing.T) {
			surface, err := test.got()
			if err != nil {
				t.Fatalf("%s() error = %v", test.name, err)
			}
			if surface == any(sentinel) {
				t.Fatalf("%s() returned the inner surface uninstrumented, so every call on that role is unspanned and untimed", test.name)
			}
		})
	}
}

// TestInstrumentedStorageRoleAccessorsPropagateInnerErrors pins the other half
// of the recursion: an accessor that recurses must not swallow the inner
// store's refusal, nor hand back a wrapper around nothing.
func TestInstrumentedStorageRoleAccessorsPropagateInnerErrors(t *testing.T) {
	t.Setenv("BD_OTEL_STDOUT", "true")
	want := errors.New("inner refused")
	wrapped, ok := WrapStorage(&roleAccessorStore{err: want}).(*InstrumentedStorage)
	if !ok {
		t.Fatal("WrapStorage did not instrument the store; telemetry is disabled in this environment")
	}

	for _, test := range []struct {
		name string
		got  func() (any, error)
	}{
		{"IssueLifecycle", func() (any, error) { return wrapped.IssueLifecycle() }},
		{"IssueReader", func() (any, error) { return wrapped.IssueReader() }},
		{"IssueRelations", func() (any, error) { return wrapped.IssueRelations() }},
		{"Commenter", func() (any, error) { return wrapped.Commenter() }},
		{"ReadyClaimer", func() (any, error) { return wrapped.ReadyClaimer() }},
		{"BatchCloser", func() (any, error) { return wrapped.BatchCloser() }},
		{"DependencyEditor", func() (any, error) { return wrapped.DependencyEditor() }},
	} {
		t.Run(test.name, func(t *testing.T) {
			surface, err := test.got()
			if !errors.Is(err, want) {
				t.Fatalf("%s() error = %v, want %v", test.name, err, want)
			}
			if surface != nil {
				t.Fatalf("%s() = %#v alongside an error, want a nil surface", test.name, surface)
			}
		})
	}
}
