package telemetry

import (
	"context"
	"errors"
	"reflect"
	"runtime"
	"strings"
	"testing"

	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/issueops"
	"github.com/steveyegge/beads/memoryops"
)

// roleAccessorNames is the twenty-four-strong capability surface every storage
// decorator has to answer for. It is duplicated from the sibling test in
// internal/storage rather than shared because that package cannot import this
// one and this one's test helpers cannot be exported back.
var roleAccessorNames = []string{
	"IssueLifecycle",
	"IssueReader",
	"IssueClaimer",
	"IssueRelations",
	"EdgeReader",
	"BlockingAnnotator",
	"TreeWalker",
	"Counter",
	"WorkspaceConfig",
	"Memories",
	"VersionReconciler",
	"StatsReporter",
	"CycleDetector",
	"ReadyCounter",
	"Querier",
	"Sweeper",
	"Deleter",
	"Bootstrapper",
	"InitVerifier",
	"Commenter",
	"ReadyClaimer",
	"BatchCloser",
	"BatchCreator",
	"DependencyEditor",
}

// TestInstrumentedStorageDeclaresEveryRoleAccessor is the structural half of
// this decorator's conformance story.
//
// InstrumentedStorage embeds storage.DoltStorage for capability pass-through,
// so DELETING an accessor still compiles: the embedded interface supplies a
// promoted method with the same signature and every call on that role goes
// unspanned and untimed. Reflection catches it because the compiler reports a
// promoted method's implementation as living in "<autogenerated>".
func TestInstrumentedStorageDeclaresEveryRoleAccessor(t *testing.T) {
	decorator := reflect.TypeOf(&InstrumentedStorage{})
	for _, name := range roleAccessorNames {
		method, ok := decorator.MethodByName(name)
		if !ok {
			t.Errorf("%s has no %s accessor at all", decorator, name)
			continue
		}
		file, _ := runtime.FuncForPC(method.Func.Pointer()).FileLine(method.Func.Pointer())
		if strings.Contains(file, "<autogenerated>") {
			t.Errorf("%s.%s is promoted from the embedded store, not declared on the decorator: "+
				"every call on that role goes unspanned", decorator, name)
		}
	}
}

// roleAccessorStore is a DoltStorage whose only real methods are the twenty-four
// role accessors, each answering with a distinguishable sentinel so a test can tell
// an instrumented surface from a passed-through one.
//
// TWO sentinels rather than one: memoryops.Memories.List and issueops.Reader.List
// are the same method name with different signatures, so no single Go type can
// satisfy both roles. Every assertion below therefore names the inner surface it
// expects rather than assuming there is only one.
type roleAccessorStore struct {
	storage.DoltStorage
	surface  *roleAccessorSentinel
	memories *memoryRoleSentinel
	err      error
}

func (s *roleAccessorStore) IssueLifecycle() (issueops.Lifecycle, error) { return s.surface, s.err }
func (s *roleAccessorStore) IssueReader() (issueops.Reader, error)       { return s.surface, s.err }
func (s *roleAccessorStore) IssueRelations() (issueops.Relations, error) { return s.surface, s.err }
func (s *roleAccessorStore) Counter() (issueops.Counter, error)          { return s.surface, s.err }
func (s *roleAccessorStore) WorkspaceConfig() (issueops.WorkspaceConfig, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) Memories() (memoryops.Memories, error) {
	return s.memories, s.err
}
func (s *roleAccessorStore) VersionReconciler() (issueops.VersionReconciler, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) StatsReporter() (issueops.StatsReporter, error) {
	return s.surface, s.err
}

func (s *roleAccessorStore) CycleDetector() (issueops.CycleDetector, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) EdgeReader() (issueops.EdgeReader, error) { return s.surface, s.err }
func (s *roleAccessorStore) TreeWalker() (issueops.TreeWalker, error) { return s.surface, s.err }
func (s *roleAccessorStore) BlockingAnnotator() (issueops.BlockingAnnotator, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) Commenter() (issueops.Commenter, error) { return s.surface, s.err }
func (s *roleAccessorStore) ReadyCounter() (issueops.ReadyCounter, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) Querier() (issueops.Querier, error) { return s.surface, s.err }
func (s *roleAccessorStore) Sweeper() (issueops.Sweeper, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) Deleter() (issueops.Deleter, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) Bootstrapper() (issueops.Bootstrapper, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) InitVerifier() (issueops.InitVerifier, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) ReadyClaimer() (issueops.ReadyClaimer, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) BatchCloser() (issueops.BatchCloser, error) { return s.surface, s.err }
func (s *roleAccessorStore) BatchCreator() (issueops.BatchCreator, error) {
	return s.surface, s.err
}
func (s *roleAccessorStore) DependencyEditor() (issueops.DependencyEditor, error) {
	return s.surface, s.err
}

// roleAccessorSentinel implements twenty-three of the twenty-four roles at once.
// Nothing calls its methods; identity is the whole point.
type roleAccessorSentinel struct{}

func (*roleAccessorSentinel) Create(context.Context, issueops.CreateRequest) (issueops.CreateResult, error) {
	return issueops.CreateResult{}, nil
}
func (*roleAccessorSentinel) Update(context.Context, issueops.UpdateRequest) (issueops.UpdateResult, error) {
	return issueops.UpdateResult{}, nil
}
func (*roleAccessorSentinel) Close(context.Context, issueops.CloseRequest) (issueops.CloseResult, error) {
	return issueops.CloseResult{}, nil
}
func (*roleAccessorSentinel) Reopen(context.Context, issueops.ReopenRequest) (issueops.ReopenResult, error) {
	return issueops.ReopenResult{}, nil
}
func (*roleAccessorSentinel) Ready(context.Context, issueops.ReadyRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}
func (*roleAccessorSentinel) List(context.Context, issueops.ListRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}
func (*roleAccessorSentinel) Get(context.Context, issueops.GetRequest) (*issueops.IssueDetails, error) {
	return nil, nil
}
func (*roleAccessorSentinel) Related(context.Context, issueops.RelatedRequest) ([]*issueops.RelatedIssue, error) {
	return nil, nil
}
func (*roleAccessorSentinel) ReadEdges(context.Context, issueops.EdgeReadRequest) (issueops.EdgeReadResult, error) {
	return issueops.EdgeReadResult{}, nil
}
func (*roleAccessorSentinel) AnnotateBlocking(context.Context, issueops.BlockingRequest) (issueops.BlockingResult, error) {
	return issueops.BlockingResult{}, nil
}

func (*roleAccessorSentinel) WalkTree(context.Context, issueops.WalkTreeRequest) (issueops.TreeResult, error) {
	return issueops.TreeResult{}, nil
}
func (*roleAccessorSentinel) Count(context.Context, issueops.CountRequest) (issueops.CountResult, error) {
	return issueops.CountResult{}, nil
}
func (*roleAccessorSentinel) CountByGroup(context.Context, issueops.CountByGroupRequest) (issueops.CountByGroupResult, error) {
	return issueops.CountByGroupResult{}, nil
}
func (*roleAccessorSentinel) GetSetting(context.Context, issueops.GetSettingRequest) (issueops.SettingResult, error) {
	return issueops.SettingResult{}, nil
}
func (*roleAccessorSentinel) ListSettings(context.Context, issueops.ListSettingsRequest) (issueops.ListSettingsResult, error) {
	return issueops.ListSettingsResult{}, nil
}
func (*roleAccessorSentinel) SetSetting(context.Context, issueops.SetSettingRequest) (issueops.SetSettingResult, error) {
	return issueops.SetSettingResult{}, nil
}
func (*roleAccessorSentinel) UnsetSetting(context.Context, issueops.UnsetSettingRequest) (issueops.UnsetSettingResult, error) {
	return issueops.UnsetSettingResult{}, nil
}
func (*roleAccessorSentinel) RecordedVersion(context.Context, issueops.RecordedVersionRequest) (issueops.RecordedVersionResult, error) {
	return issueops.RecordedVersionResult{}, nil
}
func (*roleAccessorSentinel) ReconcileVersion(context.Context, issueops.VersionReconcileRequest) (issueops.VersionReconcileResult, error) {
	return issueops.VersionReconcileResult{}, nil
}
func (*roleAccessorSentinel) Stats(context.Context, issueops.StatsRequest) (issueops.StatsResult, error) {
	return issueops.StatsResult{}, nil
}
func (*roleAccessorSentinel) AssigneeStats(context.Context, issueops.AssigneeStatsRequest) (issueops.StatsResult, error) {
	return issueops.StatsResult{}, nil
}

func (*roleAccessorSentinel) DetectCycles(context.Context, issueops.DetectCyclesRequest) (issueops.CycleReport, error) {
	return issueops.CycleReport{}, nil
}

func (*roleAccessorSentinel) CountReady(context.Context, issueops.ReadyRequest) (issueops.ReadyCountResult, error) {
	return issueops.ReadyCountResult{}, nil
}

func (*roleAccessorSentinel) Query(context.Context, issueops.QueryRequest) (issueops.IssuePage, error) {
	return issueops.IssuePage{}, nil
}

func (*roleAccessorSentinel) Delete(context.Context, issueops.DeleteRequest) (issueops.DeleteResult, error) {
	return issueops.DeleteResult{}, nil
}

func (*roleAccessorSentinel) Sweep(context.Context, issueops.SweepRequest) (issueops.SweepResult, error) {
	return issueops.SweepResult{}, nil
}
func (*roleAccessorSentinel) Bootstrap(context.Context, issueops.BootstrapRequest) (issueops.BootstrapResult, error) {
	return issueops.BootstrapResult{}, nil
}
func (*roleAccessorSentinel) VerifyIdentity(context.Context, issueops.VerifyIdentityRequest) (issueops.VerifyIdentityResult, error) {
	return issueops.VerifyIdentityResult{}, nil
}
func (*roleAccessorSentinel) AddComment(context.Context, issueops.AddCommentRequest) (issueops.AddCommentResult, error) {
	return issueops.AddCommentResult{}, nil
}
func (*roleAccessorSentinel) ClaimNext(context.Context, issueops.ClaimNextRequest) (issueops.ClaimNextResult, error) {
	return issueops.ClaimNextResult{}, nil
}
func (*roleAccessorSentinel) CloseBatch(context.Context, issueops.CloseBatchRequest) (issueops.CloseBatchResult, error) {
	return issueops.CloseBatchResult{}, nil
}
func (*roleAccessorSentinel) CreateBatch(context.Context, issueops.CreateBatchRequest) (issueops.CreateBatchResult, error) {
	return issueops.CreateBatchResult{}, nil
}
func (*roleAccessorSentinel) AddDependencies(context.Context, issueops.AddDependenciesRequest) (issueops.AddDependenciesResult, error) {
	return issueops.AddDependenciesResult{}, nil
}
func (*roleAccessorSentinel) RemoveDependency(context.Context, issueops.RemoveDependencyRequest) (issueops.RemoveDependencyResult, error) {
	return issueops.RemoveDependencyResult{}, nil
}

// memoryRoleSentinel is the twenty-fourth role's sentinel — see
// roleAccessorStore for why it cannot be a method set on the struct above.
type memoryRoleSentinel struct{}

func (*memoryRoleSentinel) Remember(context.Context, memoryops.RememberRequest) (memoryops.RememberResult, error) {
	return memoryops.RememberResult{}, nil
}
func (*memoryRoleSentinel) Recall(context.Context, memoryops.RecallRequest) (memoryops.RecallResult, error) {
	return memoryops.RecallResult{}, nil
}
func (*memoryRoleSentinel) Forget(context.Context, memoryops.ForgetRequest) (memoryops.ForgetResult, error) {
	return memoryops.ForgetResult{}, nil
}
func (*memoryRoleSentinel) List(context.Context, memoryops.ListRequest) (memoryops.ListResult, error) {
	return memoryops.ListResult{}, nil
}

// TestInstrumentedStorageInstrumentsEveryRoleAccessor catches what reflection
// cannot: an accessor that IS declared but reads
// `return s.Unwrap().Commenter()`. That edit compiles, keeps satisfying
// DoltStorage, and silently drops every span and timing on that role.
//
// Unlike the hook decorator, this one has no read-role exemption: telemetry
// spans reads as well as writes, so EVERY role must come back wrapped. Only
// IssueLifecycle and IssueReader had a recursion pin of their own before this
// test; the rest had no test at all.
//
// Each row names the INNER surface it must not be, rather than sharing one
// sentinel: the memory role has a sentinel of its own (its List collides with
// the reader's), and a row that compared against the wrong one would be a row
// that cannot fail.
func TestInstrumentedStorageInstrumentsEveryRoleAccessor(t *testing.T) {
	t.Setenv("BD_OTEL_STDOUT", "true")
	sentinel := &roleAccessorSentinel{}
	memorySentinel := &memoryRoleSentinel{}
	inner := &roleAccessorStore{surface: sentinel, memories: memorySentinel}
	wrapped, ok := WrapStorage(inner).(*InstrumentedStorage)
	if !ok {
		t.Fatal("WrapStorage did not instrument the store; telemetry is disabled in this environment")
	}

	for _, test := range []struct {
		name  string
		got   func() (any, error)
		inner any
	}{
		{"IssueLifecycle", func() (any, error) { return wrapped.IssueLifecycle() }, sentinel},
		{"IssueReader", func() (any, error) { return wrapped.IssueReader() }, sentinel},
		{"IssueRelations", func() (any, error) { return wrapped.IssueRelations() }, sentinel},
		{"EdgeReader", func() (any, error) { return wrapped.EdgeReader() }, sentinel},
		{"BlockingAnnotator", func() (any, error) { return wrapped.BlockingAnnotator() }, sentinel},
		{"TreeWalker", func() (any, error) { return wrapped.TreeWalker() }, sentinel},
		{"Counter", func() (any, error) { return wrapped.Counter() }, sentinel},
		{"WorkspaceConfig", func() (any, error) { return wrapped.WorkspaceConfig() }, sentinel},
		{"Memories", func() (any, error) { return wrapped.Memories() }, memorySentinel},
		{"VersionReconciler", func() (any, error) { return wrapped.VersionReconciler() }, sentinel},
		{"StatsReporter", func() (any, error) { return wrapped.StatsReporter() }, sentinel},
		{"CycleDetector", func() (any, error) { return wrapped.CycleDetector() }, sentinel},
		{"ReadyCounter", func() (any, error) { return wrapped.ReadyCounter() }, sentinel},
		{"Querier", func() (any, error) { return wrapped.Querier() }, sentinel},
		{"Sweeper", func() (any, error) { return wrapped.Sweeper() }, sentinel},
		{"Deleter", func() (any, error) { return wrapped.Deleter() }, sentinel},
		{"Bootstrapper", func() (any, error) { return wrapped.Bootstrapper() }, sentinel},
		{"InitVerifier", func() (any, error) { return wrapped.InitVerifier() }, sentinel},
		{"Commenter", func() (any, error) { return wrapped.Commenter() }, sentinel},
		{"ReadyClaimer", func() (any, error) { return wrapped.ReadyClaimer() }, sentinel},
		{"BatchCloser", func() (any, error) { return wrapped.BatchCloser() }, sentinel},
		{"BatchCreator", func() (any, error) { return wrapped.BatchCreator() }, sentinel},
		{"DependencyEditor", func() (any, error) { return wrapped.DependencyEditor() }, sentinel},
	} {
		t.Run(test.name, func(t *testing.T) {
			surface, err := test.got()
			if err != nil {
				t.Fatalf("%s() error = %v", test.name, err)
			}
			if surface == test.inner {
				t.Fatalf("%s() returned the inner surface uninstrumented, so every call on that role is unspanned and untimed", test.name)
			}
		})
	}
}

// TestInstrumentedStorageRoleAccessorsPropagateInnerErrors pins the other half
// of the recursion: an accessor that recurses must not swallow the inner
// store's refusal, nor hand back a wrapper around nothing.
func TestInstrumentedStorageRoleAccessorsPropagateInnerErrors(t *testing.T) {
	t.Setenv("BD_OTEL_STDOUT", "true")
	want := errors.New("inner refused")
	wrapped, ok := WrapStorage(&roleAccessorStore{err: want}).(*InstrumentedStorage)
	if !ok {
		t.Fatal("WrapStorage did not instrument the store; telemetry is disabled in this environment")
	}

	for _, test := range []struct {
		name string
		got  func() (any, error)
	}{
		{"IssueLifecycle", func() (any, error) { return wrapped.IssueLifecycle() }},
		{"IssueReader", func() (any, error) { return wrapped.IssueReader() }},
		{"IssueRelations", func() (any, error) { return wrapped.IssueRelations() }},
		{"EdgeReader", func() (any, error) { return wrapped.EdgeReader() }},
		{"BlockingAnnotator", func() (any, error) { return wrapped.BlockingAnnotator() }},
		{"TreeWalker", func() (any, error) { return wrapped.TreeWalker() }},
		{"Counter", func() (any, error) { return wrapped.Counter() }},
		{"WorkspaceConfig", func() (any, error) { return wrapped.WorkspaceConfig() }},
		{"Memories", func() (any, error) { return wrapped.Memories() }},
		{"VersionReconciler", func() (any, error) { return wrapped.VersionReconciler() }},
		{"StatsReporter", func() (any, error) { return wrapped.StatsReporter() }},
		{"CycleDetector", func() (any, error) { return wrapped.CycleDetector() }},
		{"ReadyCounter", func() (any, error) { return wrapped.ReadyCounter() }},
		{"Querier", func() (any, error) { return wrapped.Querier() }},
		{"Sweeper", func() (any, error) { return wrapped.Sweeper() }},
		{"Deleter", func() (any, error) { return wrapped.Deleter() }},
		{"Bootstrapper", func() (any, error) { return wrapped.Bootstrapper() }},
		{"InitVerifier", func() (any, error) { return wrapped.InitVerifier() }},
		{"Commenter", func() (any, error) { return wrapped.Commenter() }},
		{"ReadyClaimer", func() (any, error) { return wrapped.ReadyClaimer() }},
		{"BatchCloser", func() (any, error) { return wrapped.BatchCloser() }},
		{"BatchCreator", func() (any, error) { return wrapped.BatchCreator() }},
		{"DependencyEditor", func() (any, error) { return wrapped.DependencyEditor() }},
	} {
		t.Run(test.name, func(t *testing.T) {
			surface, err := test.got()
			if !errors.Is(err, want) {
				t.Fatalf("%s() error = %v, want %v", test.name, err, want)
			}
			if surface != nil {
				t.Fatalf("%s() = %#v alongside an error, want a nil surface", test.name, surface)
			}
		})
	}
}
