package conformance

import "testing"

// roleContractCases is the role tier's dispatch table: every contract file's
// exported cases, in the order that file declares them, under the bundle field
// that supplies their fixture.
//
// Adding a case to a contract file means adding it here too, and
// TestRoleContractCasesCoverEveryContractCase is what says so — it parses this
// package for the Run functions that take a fixture and fails on any the table
// omits, duplicates or reorders. Without that guard a case added later would
// simply stop being part of what an external backend is held to, which is the
// suite-level shape of a test that cannot fail.
var roleContractCases = []roleContract{
	roleCases("BatchApply", "BatchApplier()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BatchApplyFixture { return b.BatchApply },
		RunBatchApplyAppliesEveryItemInDeclarationOrder,
		RunBatchApplyBindsEachNamedKeyToItsMintedID,
		RunBatchApplyResolvesABackwardKeyRef,
		RunBatchApplyRefusesAKeyDeclaredLater,
		RunBatchApplyRefusesAKeyNoItemDeclares,
		RunBatchApplyRefusesARefNamingNeitherOrBoth,
		RunBatchApplyRollsBackEverythingWhenTheLastItemRefuses,
		RunBatchApplyNeverReordersItsItems,
		RunBatchApplyEndGateRefusesAHierarchyTheRequestBuilt,
		RunBatchApplyEndGateCycleSurvivesSkipPerEdgeCycleCheck,
		RunBatchApplyExpectedVersionThatMatchesLetsTheItemThrough,
		RunBatchApplyStaleExpectedVersionRefusesTheWholeRequest,
		RunBatchApplyRefusesExpectedVersionOnARowAnEarlierItemTouched,
		RunBatchApplyRefusesExpectedVersionOnARowAnEarlierItemCreated,
		RunBatchApplyEvaluatesExpectedStatusAsModified,
		RunBatchApplyEvaluatesExpectedAssigneeAsModified,
		RunBatchApplyClosePolicyEvaluatesAtTheCloseItem,
		RunBatchApplyAllowsAClosedParentToGainAnOpenChild,
		RunBatchApplyUpdateAfterCloseInOneRequest,
		RunBatchApplyReportsChangedPerItem,
		RunBatchApplyANoOpBatchRecordsNoHistory,
		RunBatchApplyRecordsOneEntryForAWriteThatLandedNothing,
		RunBatchApplyRecordsExactlyOneHistoryEntry,
		RunBatchApplyHistoryNamesTheActorAndReadsTheProvenance,
		RunBatchApplyARefusedRequestRecordsNoHistory,
		RunBatchApplyAnEphemeralBatchKeepsItsWispsAndRecordsNoDurableHistory,
		RunBatchApplyRefusesACrossPlaneEdgeBetweenRowsItCreated,
		RunBatchApplyAcceptsAnExternalEdgeTarget,
		RunBatchApplyNormalizesTheWaitsForGate,
		RunBatchApplySplicesAForwardMetadataRef,
		RunBatchApplySplicesASelfMetadataRef,
		RunBatchApplyRefusesAMetadataRefNoItemDeclares,
		RunBatchApplyTheSpliceRecordsAnUpdateEvent,
		RunBatchApplyKeepsAStoredNullApartFromAnEmptyString,
		RunBatchApplyLandsAnIdempotencyRecordWithItsWork,
		RunBatchApplyBoundsTheItemCount,
		RunBatchApplyReplayMintsANewSetOfRows,
		RunBatchApplyDoesNotMutateTheCallerRequest,
		RunBatchApplyRefusesAnUnusableRequest,
	),

	roleCases("BatchCloser", "BatchCloser()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BatchCloserFixture { return b.BatchCloser },
		RunBatchCloserOutcomesMirrorItemsIndexForIndex,
		RunBatchCloserPerItemRefusalIsAResultAndSurvivorsCommit,
		RunBatchCloserOutcomeSnapshotIsTheDocumentedShape,
		RunBatchCloserRequestValidationReturnsZeroResultAndChangesNothing,
		RunBatchCloserClaimFilterValueFailureIsARequestValidationFailure,
		RunBatchCloserBackendFailureReturnsNoOutcomes,
		RunBatchCloserIdempotentRecloseIsAPerItemSuccess,
		RunBatchCloserAllIdempotentBatchLandsNothing,
		RunBatchCloserDuplicateItemRecloseAtItsOwnIndex,
		RunBatchCloserWispItemClosesAndEarnsTheClaim,
		RunBatchCloserDurableHistoryNeverNamesAWisp,
		RunBatchCloserForceBypassesOnlyClosePolicy,
		RunBatchCloserClaimNextHydratesWhenSomethingClosed,
		RunBatchCloserClaimNextIsNilWhenNothingClosed,
		RunBatchCloserClaimNextIsNilWhenTheFrontIsEmpty,
		RunBatchCloserClaimNextSeesAnUnblockingFromItsOwnBatch,
		RunBatchCloserRecordsOneHistoryEntryForWhatLanded,
		RunBatchCloserAllRefusedBatchRecordsNoHistory,
		RunBatchCloserDoesNotMutateTheCallerRequest,
		RunBatchCloserSettlesTheDependersOfWhatItClosed,
	),

	roleCases("BatchCreator", "BatchCreator()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BatchCreatorFixture { return b.BatchCreator },
		RunBatchCreatorCreatesEveryItemAsOneAct,
		RunBatchCreatorRefusesEverythingWhenOneItemRefuses,
		RunBatchCreatorRejectsAnUnusableRequest,
		RunBatchCreatorRefusesACrossPlaneInBatchEdge,
		RunBatchCreatorLinksAnEarlierItemOfTheSameBatch,
		RunBatchCreatorLinksAnEarlierItemOnTheEphemeralPlane,
		RunBatchCreatorKeepsAnEphemeralItemsLabelsOffTheDurablePlane,
		RunBatchCreatorRefusesAnAbsentEdgeTarget,
		RunBatchCreatorAcceptsAForeignEdgeTarget,
		RunBatchCreatorRecordsOneHistoryEntry,
		RunBatchCreatorRecordsNoHistoryForAnEphemeralBatch,
		RunBatchCreatorDoesNotMutateTheCallerRequest,
	),

	roleCases("BlockingAnnotator", "BlockingAnnotator()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BlockingAnnotatorFixture { return b.BlockingAnnotator },
		RunBlockingAnnotatorAnswersOnePerIDInRequestOrder,
		RunBlockingAnnotatorCollapsesRepeatedIDs,
		RunBlockingAnnotatorReportsOpenBlockersOnly,
		RunBlockingAnnotatorReportsTheInboundDirection,
		RunBlockingAnnotatorSeparatesParentFromBlockers,
		RunBlockingAnnotatorDropsAClosedParent,
		RunBlockingAnnotatorOrdersAndCollapsesEachList,
		RunBlockingAnnotatorCountsAnUnresolvableBlockerAsOpen,
		RunBlockingAnnotatorReadsBothPlanes,
		RunBlockingAnnotatorIgnoresNonBlockingEdgeTypes,
		RunBlockingAnnotatorAnnotatesAnAbsentIDBare,
		RunBlockingAnnotatorResolvesExactIDsOnly,
		RunBlockingAnnotatorReportsAtMostOneParent,
		RunBlockingAnnotatorAnswersAnEmptyRequest,
		RunBlockingAnnotatorRefusesAnEmptyID,
		RunBlockingAnnotatorLeavesTheRequestAlone,
		RunBlockingAnnotatorWritesNothing,
	),

	// One contract file covers both halves of workspace identity: the eight
	// Bootstrapper cases write it and the four InitVerifier ones read it, and
	// the fixture carries both roles because the write cases assert through the
	// read one.
	roleCases("Bootstrapper", "Bootstrapper() and InitVerifier()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *BootstrapperFixture { return b.Bootstrapper },
		RunBootstrapperIdentifiesAFreshSubstrate,
		RunBootstrapperStoresThePrefixWithoutItsTrailingHyphen,
		RunBootstrapperRefusesAnIdentifiedSubstrate,
		RunBootstrapperRefusesASubstrateCarryingOnlyAPrefix,
		RunBootstrapperRefusesASubstrateCarryingOnlyAProjectID,
		RunBootstrapperRefusesAnInvalidRequestWithoutWriting,
		RunBootstrapperLeavesTheSubstrateUntouchedWhenItCannotComplete,
		// The bootstrap history pair is a ratified per-leg split (#5455): the
		// store legs record no entry of their own because `bd init` commits the
		// identity itself, and the proxied route records exactly one because it
		// has no other commit point. Both halves are listed because every case
		// in this package must be dispatched exactly once; a supplier that can
		// observe history answers one of them and leaves CountHistory nil if it
		// cannot state which side it is on, which skips both loudly.
		RunBootstrapperRecordsNoHistoryEntryOfItsOwn,
		RunBootstrapperRecordsExactlyOneHistoryEntry,
		RunInitVerifierAnswersEmptyForAnUnidentifiedSubstrate,
		RunInitVerifierReportsAPartialIdentityAsItStands,
		RunInitVerifierReportsAFailedReadAsAnError,
		RunInitVerifierWritesNothing,
	),

	roleCases("Claimer", "IssueClaimer()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ClaimerFixture { return b.Claimer },
		RunClaimerClaimsAnUnassignedOpenIssueAndAnswersTheBareRow,
		RunClaimerTakesAnOpenIssueTheActorAlreadyHolds,
		RunClaimerReclaimsItsOwnInProgressIssueWithoutWriting,
		RunClaimerReclaimsAcrossSpellingWithoutWriting,
		RunClaimerAcceptsAConfiguredActiveStatusAndRefusesAConfiguredWipOne,
		RunClaimerTakesAPoolAssignedIssueButRefusesAForeignHolder,
		RunClaimerRefusesABuiltInIneligibleStatusWithTheStateThatRefusedIt,
		RunClaimerRefusesAWispIDAsNotFound,
		RunClaimerRefusesIncompleteRequestsAndAnAbsentIDWithoutTouchingState,
		RunClaimerGrantsALiveLeaseOnTheRowItWonAndLeavesARefusedOneAlone,
		RunClaimerStampsStartedAtOnceAcrossTheTwoWritesItChoosesBetween,
		RunClaimerRefusalMessagesCarryTheirFragments,
	),

	roleCases("Commenter", "Commenter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *CommenterFixture { return b.Commenter },
		RunCommenterStoresTextVerbatim,
		RunCommenterResultMirrorsTheStoredRow,
		RunCommenterAdvancesALiveStampPastTheThreadsNewestComment,
		RunCommenterTakesTheClockWhenTheThreadIsBehindIt,
		RunCommenterCommentOnAWispLandsOnTheWispThread,
		RunCommenterRefusesAnIDOnNeitherPlane,
		RunCommenterRefusesAnEmptyIssueID,
		RunCommenterDoesNotResolvePrefixes,
		RunCommenterRecordsExactlyOneHistoryEntry,
		RunCommenterLeavesTheAnchorIssueUntouched,
		RunCommenterRefusesBlankText,
		RunCommenterRefusesAnEmptyAuthor,
		RunCommenterLeavesTheCallersRequestAlone,
	),

	roleCases("Counter", "Counter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *CounterFixture { return b.Counter },
		RunCounterCountsTheDurablePlaneByDefault,
		RunCounterIncludeInfraMergesTheWispTier,
		RunCounterIncludeInfraExcludesGates,
		RunCounterCountsClosedRows,
		RunCounterAnUnknownStatusMatchesNothing,
		RunCounterGroupsPartitionTheScalarSet,
		RunCounterLabelBucketsOverlapSoTotalIsNotTheirSum,
		RunCounterNamesTheEmptyBuckets,
		RunCounterPrefixesPriorityBuckets,
		RunCounterPriorityBucketsCountZeroAndCountEveryRow,
		RunCounterTheNoLabelBucketIsAbsentWhenEveryRowIsLabeled,
		RunCounterTypeBucketsAreTheRawTypeNames,
		RunCounterRefusesAnUnknownGroup,
		RunCounterNormalizesLabelsAndLeavesTheRequestAlone,
		RunCounterWritesNothing,
	),

	roleCases("CycleDetector", "CycleDetector()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *CycleDetectorFixture { return b.CycleDetector },
		RunCycleDetectorReportsNoCycleForAnAcyclicSubgraph,
		RunCycleDetectorFindsADurableCycleRotatedToItsLowestID,
		RunCycleDetectorReportsTheSameCyclesEveryRun,
		RunCycleDetectorMergesTheDurableAndEphemeralPlanes,
		RunCycleDetectorFollowsOnlyBlockingEdges,
		RunCycleDetectorReportsAnHonestPartial,
		RunCycleDetectorCountsAWhollyUndescribableCycle,
		RunCycleDetectorWritesNothing,
	),

	roleCases("Deleter", "Deleter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *DeleterFixture { return b.Deleter },
		RunDeleterRefusesAMalformedRequest,
		RunDeleterRefusesAnAbsentID,
		RunDeleterRefusesDependentsOutsideTheRequest,
		RunDeleterForceOrphansDependents,
		RunDeleterCascadeDeletesTheClosure,
		RunDeleterCascadeFromAWispRootDeletesTheClosure,
		RunDeleterGuardsAWispNamedWithADurableDependent,
		RunDeleterGuardsADurableNamedWithAWispDependent,
		RunDeleterCountsCrossPlaneEdgesItRemoves,
		RunDeleterNeverCallsALiveRowDeleted,
		RunDeleterErasesAcrossBothPlanes,
		RunDeleterCollapsesDuplicateIDs,
		RunDeleterRewritesReferencesInNeighbors,
		RunDeleterDryRunChangesNothing,
		RunDeleterRecordsExactlyOneHistoryEntry,
		RunDeleterDoesNotMutateTheCallerRequest,
		RunDeleterSettlesTheSurvivorsOfADeletedBlocker,
		RunDeleterSettlesTheChildrenOfADeletedParent,
		RunDeleterSettlesTheSurvivorsOfADeletedWispBlocker,
		RunDeleterDeletesOnAMatchingExpectedVersion,
		RunDeleterRefusesAStaleExpectedVersion,
		RunDeleterVersionOutranksForceAndCascade,
		RunDeleterRefusesAnExpectedVersionAcrossSeveralIDs,
	),

	roleCases("DependencyEditor", "DependencyEditor()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *DependencyEditorFixture { return b.DependencyEditor },
		RunDependencyEditorRoutesWispSourcedEdgeToTheWispPlane,
		RunDependencyEditorMixedBatchWritesBothPlanes,
		RunDependencyEditorMixedBatchRefusalRollsBackBothPlanes,
		RunDependencyEditorRefusesCrossPlaneCycle,
		RunDependencyEditorAddedEchoesTheRequestOrder,
		RunDependencyEditorSameTypeReAddIsIdempotent,
		RunDependencyEditorRepeatsWithinOneRequestCollapse,
		RunDependencyEditorAttributesItsEventsToTheActor,
		RunDependencyEditorRetypeRefusalLeavesTheOriginalEdge,
		RunDependencyEditorRefusalWritesNothing,
		RunDependencyEditorRemoveIsIdempotent,
		RunDependencyEditorAppliesParentChildBeforeBlockingEdges,
		RunDependencyEditorAcceptsAnExternalTarget,
		RunDependencyEditorAcceptsAForeignRepoTarget,
		RunDependencyEditorRefusesBlockingEdgeAcrossItsOwnHierarchy,
		RunDependencyEditorRefusesSelfDependencyWithTheProbeSkipped,
		RunDependencyEditorRecordsOneHistoryEntryPerLandedRequest,
		RunDependencyEditorRecordsNoHistoryForAnAllEphemeralRequest,
		RunDependencyEditorSnapshotsTheRequest,
		RunDependencyEditorValidationRefusalsWriteNothing,
		RunDependencyEditorRoutesWispSourcedRemovalToTheWispPlane,
		RunDependencyEditorRefusesAGhostSource,
		RunDependencyEditorRefusesAMissingLocalTarget,
		RunDependencyEditorAcceptsATypeOutsideTheConstants,
		RunDependencyEditorRemovesOnlyTheNamedEdge,
		RunDependencyEditorSkipPerEdgeCycleCheckDropsOnlyTheProbe,
		RunDependencyEditorRecordsOneHistoryEntryForAMixedPlaneRequest,
		RunDependencyEditorWritesTheTargetIntoItsTypedColumn,
		RunDependencyEditorRefusesBlockingEdgeAcrossAWispHierarchy,
		RunDependencyEditorRefusesACycleThroughAParentChildHop,
		RunDependencyEditorRefusesASamePlaneEdgeClosingACrossPlaneCycle,
		RunDependencyEditorAddMarksItsSourceInTheSameVerb,
		RunDependencyEditorRemoveUnmarksItsSourceAndDescendants,
		RunDependencyEditorMaintainsBlockedStateAcrossPlanes,
		RunDependencyEditorClosedChildAddSatisfiesAnAnyChildrenGate,
		RunDependencyEditorRelatesToAddLeavesItsSourceUnblocked,
		RunDependencyEditorAcceptsADiamond,
		RunDependencyEditorGateScopeFollowsTheEdgeType,
		RunDependencyEditorAcceptsBlockingAcrossIssueTypes,
	),

	roleCases("EdgeReader", "EdgeReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *EdgeReaderFixture { return b.EdgeReader },
		RunEdgeReaderAnswersOnePerAnchorInRequestOrder,
		RunEdgeReaderReportsAMissingAnchorRatherThanFailing,
		RunEdgeReaderDistinguishesNoEdgesFromNoAnchor,
		RunEdgeReaderReturnsTargetsVerbatim,
		RunEdgeReaderCollapsesRepeatedAnchors,
		RunEdgeReaderOrdersEdgesByTarget,
		RunEdgeReaderFiltersEdgesNotAnchors,
		RunEdgeReaderReadsBothPlanes,
		RunEdgeReaderResolvesExactIDsOnly,
		RunEdgeReaderAnswersAnEmptyRequest,
		RunEdgeReaderRefusesAnEmptyID,
		RunEdgeReaderRefusesAnUnusableType,
		RunEdgeReaderLeavesTheRequestAlone,
		RunEdgeReaderWritesNothing,
	),

	roleCases("GraphCounter", "GraphCounter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *GraphCounterFixture { return b.GraphCounter },
		RunGraphCounterCountsOutboundEdges,
		RunGraphCounterCountsInboundEdges,
		RunGraphCounterAnswersOnePerAnchorInRequestOrder,
		RunGraphCounterDistinguishesNoEdgesFromNoAnchor,
		RunGraphCounterCollapsesRepeatedAnchors,
		RunGraphCounterFiltersEdgesNotAnchors,
		RunGraphCounterNarrowsInboundByDependentStatus,
		RunGraphCounterCountsAcrossBothPlanes,
		RunGraphCounterNarrowsAWispDependentByStatus,
		RunGraphCounterResolvesIDsExactly,
		RunGraphCounterAnswersAnEmptyRequest,
		RunGraphCounterRefusesAnUnusableRequest,
		RunGraphCounterLeavesTheRequestAlone,
		RunGraphCounterWritesNothing,
	),

	// The accessor named here is NOT a storage.DoltStorage one, alone among
	// these rows: Importer is served only by uow.ImporterSource, so a backend
	// built on the store interface has nothing to fill this field with and
	// leaves it nil. See importer_contract.go's header.
	roleCases("Importer", "Importer()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ImporterFixture { return b.Importer },
		RunImporterRejectsAStaleRowAndNamesIt,
		RunImporterReportsTheAbsentTargetItDroppedOnce,
		RunImporterWiresTheCrossPlaneEdgeBetweenItsRows,
		RunImporterReportsTheCycleEdgeItDropped,
	),

	// Per case, not per role: see RoleContractBundle.IssueOperations.
	roleCases("IssueOperations", "IssueLifecycle()", oncePerCase,
		func(b RoleContractBundle) func(t *testing.T) *IssueOperationsStagingFixture { return b.IssueOperations },
		RunIssueOperationsCreateRoutesInfraTypesToWisps,
		RunIssueOperationsCreateUnderAParentMintsTheNextChildID,
		RunIssueOperationsUpdateFoldsMetadataIntoOneEvent,
		RunIssueOperationsUpdateClosedFieldsMatchClose,
		RunIssueOperationsUpdateClaimConflictCarriesTheLosingState,
		RunIssueOperationsUpdateClaimHonorsConfiguredActiveStatuses,
		RunIssueOperationsUpdateIssuePlaneOnlyRefusesWisps,
		RunIssueOperationsUpdateLabelPatchOrdering,
		RunIssueOperationsUpdateLabelPatchValueRules,
		RunIssueOperationsUpdateMetadataReplaceClearsAndValidates,
		RunIssueOperationsRequestValuesAreNotMutated,
		RunIssueOperationsCreateClosedDerivesTheClosedStamp,
		RunIssueOperationsUpdateWritesEveryScalarPatchField,
		RunIssueOperationsUpdateStampsStartedAtOnceOnTheFirstInProgress,
		RunIssueOperationsUpdateRawMetadataTakesTheFunnelsValueShapes,
		RunIssueOperationsUpdateRefusesATypeOutsideTheWorkspaceVocabulary,
		RunIssueOperationsUpdateStatusCrossingSettlesDependers,
		RunIssueOperationsUpdateStatusCrossingSettlesAConditionalBlocksDepender,
		RunIssueOperationsCreateWithDependenciesSettlesInTheCreatingTransaction,
		RunIssueOperationsClaimLeavesBlockedStateAlone,
	),

	// The versioned-store pair, separately nil-able: see
	// RoleContractBundle.IssueOperationsStaging.
	roleCases("IssueOperationsStaging", "IssueLifecycle()", oncePerCase,
		func(b RoleContractBundle) func(t *testing.T) *IssueOperationsStagingFixture {
			return b.IssueOperationsStaging
		},
		RunIssueOperationsCreateReverseNonBlockingStagesConcreteTables,
		RunIssueOperationsCreateParentChildRecomputesWaitsForClosure,
	),

	// The accessor named here is not an accessor at all, alone among these
	// rows. journalops.Journal is reached by TYPE ASSERTION on a store —
	// `bd serve` does exactly that (cmd/bd/serve.go, serveJournalCursor) — or
	// through uow.EventsJournalCursorSource on a unit-of-work provider, because
	// the journal is engine state on a dolt_ignored table that
	// storage.DoltStorage does not publish. A backend that cannot read it
	// leaves this field nil; see journal_contract.go's header.
	roleCases("Journal", "the storage.EventsJournalCursor type assertion (or uow.EventsJournalCursor())", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *JournalFixture { return b.Journal },
		RunJournalPagesAreSeqAscendingAndSinceExclusive,
		RunJournalHeadArrivesWithItsRowsAndDetectsCaughtUp,
		RunJournalLimitCapsRowsNotHead,
		RunJournalTruncationIsTypedAndNamesTheWindow,
		RunJournalHeadSurvivesAFullPrune,
		RunJournalEveryMutationKindLandsARow,
	),

	roleCases("LifecycleCloseReopen", "IssueLifecycle()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *LifecycleCloseReopenFixture {
			return b.LifecycleCloseReopen
		},
		RunLifecycleCloseRefusalsCarryTheirTypesAndWriteNothing,
		RunLifecycleCloseAdmitsATransitivelyBlockedTarget,
		RunLifecycleCloseCountsOpenChildrenInBothPlanes,
		RunLifecycleCloseAdmitsAStaleBlockFlagWhoseBlockersHaveClosed,
		RunLifecycleCloseIsIdempotentOnAClosedRowThatStillLooksBlocked,
		RunLifecycleCloseIsIdempotentAndKeepsTheFirstClose,
		RunLifecycleCloseAndReopenKeepTheClaimHolder,
		RunLifecycleReopenLeavesNonDoneStatusesUnchanged,
		RunLifecycleCloseAndReopenSpanTheConfiguredDoneCategory,
		RunLifecycleExpectedVersionIsCheckedBeforeTheNoOps,
		RunLifecycleReopenRecordsItsReason,
		RunLifecycleResultsAreHydratedPostStateSnapshots,
		RunLifecycleCloseAndReopenRequireActorAndIssueID,
		RunLifecycleReopenProvenanceLabelsHistory,
		RunLifecycleCloseSettlesItsTransitiveAndCrossPlaneDependers,
		RunLifecycleCloseSettlesTheClosedRowItselfAndItsChild,
		RunLifecycleCloseOnASpawnersLastChildSatisfiesAWaitsForGate,
		RunLifecycleReopenReblocksItsDependers,
	),

	// The accessor-reachable half of Lifecycle.Create, moved out of the staging
	// contract: see the header on lifecycle_create_contract.go.
	roleCases("LifecycleCreate", "IssueLifecycle()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *LifecycleCreateFixture { return b.LifecycleCreate },
		RunLifecycleCreateRejectsMissingDependencyTargets,
		RunLifecycleCreateRefusesAnOccupiedID,
		RunLifecycleCreateRefusesAForeignIDPrefix,
		RunLifecycleCreateInheritsParentLabels,
		RunLifecycleCreateWritesEveryScalarField,
	),

	roleCases("LifecycleUpdate", "IssueLifecycle()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *LifecycleUpdateFixture { return b.LifecycleUpdate },
		RunLifecycleUpdatePersistsThePatchAndHydratesTheResult,
		RunLifecycleUpdatePreservesTheCreationStamp,
		RunLifecycleUpdateReportsNoChangeForASameValuePatch,
		RunLifecycleUpdateAppendsNotesWithoutReplacingThem,
		RunLifecycleUpdateClearsTheNullableMembers,
		RunLifecycleUpdateReplacesTheLabelSet,
		RunLifecycleUpdateResolvesBothPlanesUnlessRestricted,
		RunLifecycleUpdateRefusesUnknownIDsAndActorlessRequests,
		RunLifecycleUpdateRefusalWritesNoMemberOfThePatch,
		RunLifecycleUpdateConditionalGuardsGateOrdinaryEdits,
		RunLifecycleUpdateConditionalGuardAcceptsRespelledAssignee,
		RunLifecycleUpdateMetadataPatchOrdersMergeSetUnset,
		RunLifecycleUpdateClosePolicy,
		RunLifecycleUpdateAssigneeTransferFence,
		RunLifecycleUpdateClaimIsAMutationWhenThePatchRestoresTheRow,
		RunLifecycleUpdateParentIDReplacesTheParentEdge,
		RunLifecycleUpdateParentIDReplacesEveryParent,
		RunLifecycleUpdatePersistentPreservesUnversionedClass,
		RunLifecycleUpdateProvenanceLabelsHistory,
	),

	roleCases("Memories", "Memories()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *MemoriesFixture { return b.Memories },
		RunMemoriesListOfAnEmptyPlaneAnswersAnEmptyMap,
		RunMemoriesRememberStoresContentVerbatim,
		RunMemoriesRememberDerivesTheKeyWhenAbsent,
		RunMemoriesRememberWithExplicitKeyStoresVerbatim,
		RunMemoriesRememberReplacesAndReportsIt,
		RunMemoriesRememberRefusesEmptyContent,
		RunMemoriesRememberRefusesAWhitespaceOnlyKey,
		RunMemoriesRememberRefusesAnUnderivableKey,
		RunMemoriesRecallAnswersTheStoredValue,
		RunMemoriesRecallReportsAMissAsNotFoundNotAnError,
		RunMemoriesRecallConflatesStoredEmptyWithAbsent,
		RunMemoriesForgetRemovesExactlyTheNamedRow,
		RunMemoriesForgetNeverTouchesTheSettingsPlane,
		RunMemoriesForgetReportsTheForgottenValue,
		RunMemoriesForgetOfAnAbsentKeyIsNotFoundAndDeletesNothing,
		RunMemoriesListReturnsOnlyTheMemoryPlane,
		RunMemoriesListSearchMatchesTheUserKeyNotTheStorageKey,
		RunMemoriesListSearchMatchesKeyOrValueCaseInsensitively,
		RunMemoriesARefusedWriteRecordsNoHistory,
	),

	roleCases("MetadataCAS", "MetadataCAS()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *MetadataCASFixture { return b.MetadataCAS },
		RunMetadataCASCreatesAKeyThatWasAbsent,
		RunMetadataCASRefusesASecondCreateAndReportsTheHolder,
		RunMetadataCASSwapsOnAMatchAndReportsTheNewValue,
		RunMetadataCASRefusalReportsTheCurrentValueAndWritesNothing,
		RunMetadataCASComparesCanonically,
		RunMetadataCASReportsTheValueTheRowHolds,
		RunMetadataCASDistinguishesAnAbsentKeyFromAStoredNull,
		RunMetadataCASRemovesTheKeyWhenTheValueIsAbsent,
		RunMetadataCASPreservesSiblingKeys,
		RunMetadataCASNoOpSwapWritesNothing,
		RunMetadataCASRefusesAnIDOnNeitherPlane,
		RunMetadataCASRefusesAnUnusableRequest,
		RunMetadataCASResolvesAWispAnchor,
		RunMetadataCASAWispSwapRecordsNoDurableHistory,
		RunMetadataCASRecordsExactlyOneHistoryEntry,
		RunMetadataCASHistoryEntryNamesTheActor,
		RunMetadataCASARefusedSwapRecordsNoHistory,
		RunMetadataCASDoesNotMutateTheCallerRequest,
	),

	roleCases("Querier", "Querier()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *QuerierFixture { return b.Querier },
		RunQuerierDisjunctionAnswersEveryMatch,
		RunQuerierPageIsAPrefixAndHasMoreIsExact,
		RunQuerierSortBoundsThePageInOrder,
		RunQuerierSortByTitleFoldsCaseBeforeItCutsThePage,
		RunQuerierSortByClosedPutsTheUnclosedRowsAtTheFarEnd,
		RunQuerierSortTieBreaksByIDInBothDirections,
		RunQuerierSortSeesTheWholeMatchingSet,
		RunQuerierHidesClosedUnlessTheExpressionOrTheFlagSaysOtherwise,
		RunQuerierRefusesAMalformedRequest,
		RunQuerierOffsetSkipsMatches,
		RunQuerierEmptyMatchIsAWellFormedPage,
		RunQuerierWritesNothing,
		RunQuerierDoesNotMutateTheCallerRequest,
	),

	roleCases("Reader", "IssueReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReaderFixture { return b.Reader },
		RunReaderReadyDefaultTypeExclusionsYieldToAnExplicitType,
		RunReaderReadyDeferredAndEphemeralGates,
		RunReaderReadyLimitBoundary,
		RunReaderOffsetSkipsTheRowsBeforeThePage,
		RunReaderReadySortPoliciesOrderTheSameRows,
		RunReaderListDefaultExclusionsAndTheirOverrides,
		RunReaderListRejectsATypeOutsideTheWorkspaceVocabulary,
		RunReaderListNaturalNumericIDSortTrimsAfterTheFetch,
		RunReaderListKeysetPositionResumesTheCreatedDescIDAscOrder,
		RunReaderListReadyFlagAnswersTheBlockerAwareSet,
		RunReaderListReadyFlagRefusesAFilterItCannotCarry,
		RunReaderListEmptyPageIsWellFormed,
		RunReaderListMaxRowsIsHonored,
		RunReaderListMaxRowsBoundaryIsLimitPlusOffset,
		RunReaderListSkipCountsDropsTheCardinalitiesAndNothingElse,
		RunReaderGetResolvesTheExactIDAcrossBothPlanes,
		RunReaderGetMissIsNotFoundAndBackendFailureDoesNotDecay,
		RunReaderGetOptionalRowListsAreOffByDefault,
		RunReaderGetBriefDepsProjectsTheDependencyRows,
		RunReaderGetDetailShapeMatchesTheSeededIssue,
		RunReaderDoesNotMutateTheCallerRequest,
		RunReaderListLimitBoundaryUnderASortTheDatabaseCanExpress,
		RunReaderReadySetOwnsItsStatusPinnedAndTemplateDecisions,
		RunReaderListReadyFlagCarriesTheAssigneeAndPriorityFilters,
		RunReaderListStatusAcceptsACommaSeparatedORSet,
		RunReaderReadyPageIsThePrefixOfTheUnboundedAnswerCountsIncluded,
		RunReaderReadyEphemeralPageKeepsBothPlanesCountsAtItsBoundary,
		RunReaderReadyPageWiderThanTheHydrationBatchIsStillThatPrefix,
		RunReaderListCountsAreBlocksOnlyWhereGetCountsEveryEdge,
		RunReaderReadyParentScopesToItsTransitiveDescendants,
		RunReaderListParentReachesEveryDescendantAndOnlyItsOwn,
		RunReaderListKeysetWalkOverAnOversizedGroupLosesNothingAndRepeatsNothing,
		RunReaderListPriorityKeysetWalkOverAnOversizedEqualKeyRunLosesNothingAndRepeatsNothing,
		RunReaderListKeysetPositionNarrowsWithoutReplacingTheOtherPredicates,
		RunReaderListIncludeEphemeralMergesThePlanesIntoOneOrder,
		RunReaderListWispTypeNarrowsTheAdmittedPlaneRatherThanAdmittingIt,
		RunReaderListBriefDropsTheFreeFormTextAndNothingElse,
		RunReaderReadyBriefDropsTheFreeFormTextAndNothingElse,
	),

	roleCases("ReadyClaimer", "ReadyClaimer() and IssueReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReadyClaimerFixture { return b.ReadyClaimer },
		RunReadyClaimerRejectsLimitOffsetBriefAndEmptyActor,
		RunReadyClaimerEmptyFrontIsNormal,
		RunReadyClaimerClaimsTheFrontRowAndReturnsThePostClaimState,
		RunReadyClaimerClaimsAnEphemeralRowTheFilterAdmits,
		RunReadyClaimerLeavesEphemeralRowsOutOfTheDefaultReadySet,
		RunReadyClaimerLeasesADurableWinButNotAnEphemeralOne,
		RunReadyClaimerAnswersTheQuestionReaderReadyLists,
		RunReadyClaimerSkipsIneligibleFrontRows,
		RunReadyClaimerRecordsOneHistoryEntryForAWin,
		RunReadyClaimerDoesNotMutateTheCallerRequest,
		RunReadyClaimerFencesTheClaimByEveryLabelSetAndTheParentItWasGiven,
		RunReadyClaimerHydratesOnlyItsBlocksEdgesIntoTheCardinalities,
	),

	roleCases("ReadyCounter", "ReadyCounter() and IssueReader()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReadyCounterFixture { return b.ReadyCounter },
		RunReadyCounterEqualsTheUnboundedPage,
		RunReadyCounterRejectsLimitAndOffset,
		RunReadyCounterCountsTheBlockerAwareSet,
		RunReadyCounterEphemeralGateMatchesTheListing,
		RunReadyCounterEmptyFrontIsZeroAndNil,
		RunReadyCounterWritesNothing,
		RunReadyCounterDoesNotMutateTheCallerRequest,
		RunReadyCounterCountsOnlyTheOpenRowsItsListingLists,
	),

	roleCases("Relations", "IssueRelations()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *RelationsFixture { return b.Relations },
		RunRelationsAnswersInThePinnedOrder,
		RunRelationsOrdersNeighborsFromBothPlanesTogether,
		RunRelationsAnswersAWispTargetInTheOutDirection,
		RunRelationsRefusesTheZeroDirection,
		RunRelationsSeparatesNoNeighborsFromNoSuchIssue,
		RunRelationsResolvesAWispAnchor,
		RunRelationsFiltersByAnOpenTypeVocabulary,
		RunRelationsRefusesAnUnusableTypeFilter,
		RunRelationsRefusesATypeFilterOverTheColumnLength,
		RunRelationsDirectionSelectsTheInverseGraph,
		RunRelationsLeavesTheCallersRequestAlone,
		RunRelationsLeavesAnExternalTargetOutOfTheAnswer,
		RunRelationsResolvesTheAnchorIDExactly,
	),

	roleCases("Releaser", "Releaser()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *ReleaserFixture { return b.Releaser },
		RunReleaserReleasesItsOwnClaim,
		RunReleaserRefusesAForeignClaimUntilForced,
		RunReleaserReleasesOnlyTheExpectedHolder,
		RunReleaserRefusesAnUnheldIssue,
		RunReleaserRefusesAStatusThatCannotBeReleased,
		RunReleaserRefusesAMalformedRequest,
		RunReleaserRefusesAnAbsentID,
		RunReleaserAttributesTheReleaseToTheActor,
		RunReleaserRecordsExactlyOneHistoryEntry,
		RunReleaserReleasesAWispClaimWithoutVersioning,
		RunReleaserDoesNotMutateTheCallerRequest,
	),

	roleCases("StatsReporter", "StatsReporter()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *StatsReporterFixture { return b.StatsReporter },
		RunStatsReporterCountsEveryDurableRowByStatus,
		RunStatsReporterExcludesTheWispTier,
		RunStatsReporterAStatusOutsideTheTalliesIsCountedOnlyInTotal,
		RunStatsReporterBlockedCountsTheGraphNotTheStatus,
		RunStatsReporterBlockedExcludesByStatusNotByThePinnedFlag,
		RunStatsReporterBlockedCountsEveryUnfinishedStatusNotJustOpen,
		RunStatsReporterReadyIsOpenMinusBlocked,
		RunStatsReporterSkipBlockedPairsTheTwoPointers,
		RunStatsReporterExtendedFieldsAreAlwaysZero,
		RunStatsReporterWritesNothing,
		RunStatsReporterAssigneeStatsScopesToOneActor,
		RunStatsReporterAssigneeBlockedCountsTheStatusNotTheGraph,
		RunStatsReporterAssigneeStatsMergesTheWispTier,
		RunStatsReporterAssigneeStatsPopulatesBothPointers,
		RunStatsReporterAssigneeStatsRefusesAnEmptyAssignee,
	),

	roleCases("Sweeper", "Sweeper()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *SweeperFixture { return b.Sweeper },
		RunSweeperRefusesAnUnfilteredDurableSweep,
		RunSweeperRefusesAMalformedRequest,
		RunSweeperClearsOneTierAndLeavesTheOther,
		RunSweeperTreatsALegacyTypedWispAsEphemeralTier,
		RunSweeperLeavesNoHistoryBeadsToTheDurableTier,
		RunSweeperProtectsPinnedRows,
		RunSweeperHonorsTheCutoffAndThePattern,
		RunSweeperDryRunChangesNothing,
		RunSweeperProtectsRowsCitedFromAWispComment,
		RunSweeperProtectsCitedRows,
		RunSweeperEmptyMatchIsZeroAndNil,
		RunSweeperRecordsExactlyOneHistoryEntry,
		RunSweeperDoesNotMutateTheCallerRequest,
	),

	roleCases("TreeWalker", "TreeWalker()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *TreeWalkerFixture { return b.TreeWalker },
		RunTreeWalkerWalksTheDependenciesOfARoot,
		RunTreeWalkerWalksDependentsWhenAskedUp,
		RunTreeWalkerBoundsTheDescentAtMaxDepth,
		RunTreeWalkerTerminatesOnACycle,
		RunTreeWalkerRendersASharedSubtreeOnce,
		RunTreeWalkerMergesTheDurableAndEphemeralPlanes,
		RunTreeWalkerFollowsEveryTypeButRelatesTo,
		RunTreeWalkerPrunesEachHalfOfABothWalk,
		RunTreeWalkerAnswersBothDirectionsWithTheRootOnce,
		RunTreeWalkerPrunesByStatusKeepingAncestors,
		RunTreeWalkerPrunesEverythingWhenNothingMatches,
		RunTreeWalkerAnswersARootWithNoEdges,
		RunTreeWalkerRefusesAnAbsentRoot,
		RunTreeWalkerResolvesTheRootIDExactly,
		RunTreeWalkerCrossesPlanesFromAWispRootAndUpward,
		RunTreeWalkerRefusesAnInvalidRequest,
		RunTreeWalkerRefusesAWalkOverTheRowCap,
		RunTreeWalkerWritesNothing,
	),

	roleCases("VersionReconciler", "VersionReconciler()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *VersionReconcilerFixture { return b.VersionReconciler },
		RunVersionReconcilerRecordsAWorkspaceWithNoMarkers,
		RunVersionReconcilerAdvancesBothMarkersOnAnUpgrade,
		RunVersionReconcilerTreatsTheSameVersionAsANoOp,
		RunVersionReconcilerRefusesADowngradeWithoutAnError,
		RunVersionReconcilerRefusesAVersionBelowTheHighWaterMark,
		RunVersionReconcilerCatchesUpToTheHighWaterMark,
		RunVersionReconcilerRefusesAnEmptyVersion,
		RunVersionReconcilerLeavesTheMarkersStandingWhenItCannotComplete,
		RunVersionReconcilerRecordsNoHistory,
	),

	roleCases("WorkspaceConfig", "WorkspaceConfig()", oncePerRole,
		func(b RoleContractBundle) func(t *testing.T) *WorkspaceConfigFixture { return b.WorkspaceConfig },
		RunWorkspaceConfigStoresAValueVerbatim,
		RunWorkspaceConfigReplacesAnExistingValue,
		RunWorkspaceConfigConflatesAnUnsetKeyWithAnEmptyValue,
		RunWorkspaceConfigListsEveryStoredSetting,
		RunWorkspaceConfigListExcludesTheKVPlane,
		RunWorkspaceConfigPointReadRefusesTheKVPlane,
		RunWorkspaceConfigUnsetRemovesTheSetting,
		RunWorkspaceConfigUnsetOfAnAbsentKeySucceeds,
		RunWorkspaceConfigRefusesAnEmptyKey,
		RunWorkspaceConfigRefusesTheProtectedKeyOnSet,
		RunWorkspaceConfigUnsetDoesNotRefuseTheProtectedKey,
		RunWorkspaceConfigRefusesAnUnparseableCustomStatus,
		RunWorkspaceConfigProjectsCustomStatuses,
		RunWorkspaceConfigProjectsCustomTypes,
		RunWorkspaceConfigUnsetLeavesTheProjectionBehind,
		RunWorkspaceConfigARefusedWriteRecordsNoHistory,
		RunWorkspaceConfigKeysAreCaseSensitive,
		RunWorkspaceConfigCustomStatusReadsAreOrderedByName,
		RunWorkspaceConfigCustomTypeReadsAreOrderedByName,
		RunWorkspaceConfigConfiguredInfraTypesReplaceTheDefaultSet,
		RunWorkspaceConfigUnconfiguredVocabularyReadsAreEmptyNotErrors,
	),
}
