package golangci_test

import (
	"go/ast"
	"testing"

	"golang.org/x/tools/go/analysis"

	"github.com/steveyegge/beads/tools/nogo/internal/analyzertest"
	"github.com/steveyegge/beads/tools/nogo/internal/golangci"
)

// funcs reports every function declaration as "func <name>".
var funcs = &analysis.Analyzer{
	Name: "funcs",
	Doc:  "reports every function",
	Run: func(pass *analysis.Pass) (any, error) {
		for _, f := range pass.Files {
			for _, d := range f.Decls {
				if fn, ok := d.(*ast.FuncDecl); ok {
					pass.Report(analysis.Diagnostic{Pos: fn.Pos(), Message: "func " + fn.Name.Name})
				}
			}
		}
		return nil, nil
	},
}

func wrapped(t *testing.T, yml string) *analysis.Analyzer {
	t.Helper()
	cfg, err := golangci.Parse([]byte(yml))
	if err != nil {
		t.Fatal(err)
	}
	return &analysis.Analyzer{
		Name: "fake",
		Doc:  "funcs under cfg",
		Run: func(pass *analysis.Pass) (any, error) {
			return golangci.Run(cfg, "fake", funcs, pass)
		},
	}
}

const header = `version: "2"
linters:
  default: none
  enable: [fake]
`

func TestNotEnabledReportsNothing(t *testing.T) {
	a := wrapped(t, "version: \"2\"\nlinters:\n  default: none\n  enable: [other]\n")
	got := analyzertest.RunInRepo(t, a, "p", map[string]string{"p.go": "package p\n\nfunc f() {}\n"})
	analyzertest.Equal(t, got, nil)
}

func TestTestsFalseSkipsTestUnits(t *testing.T) {
	a := wrapped(t, header+"run:\n  tests: false\n")
	lib := map[string]string{"p.go": "package p\n\nfunc f() {}\n"}
	analyzertest.Equal(t, analyzertest.RunInRepo(t, a, "p", lib),
		[]analyzertest.Diagnostic{{File: "p.go", Line: 3, Message: "func f"}})
	withTest := map[string]string{
		"p.go":      "package p\n\nfunc f() {}\n",
		"p_test.go": "package p\n\nfunc g() {}\n",
	}
	analyzertest.Equal(t, analyzertest.RunInRepo(t, a, "p", withTest), nil)
}

func TestTestsDefaultAnalyzesTestUnits(t *testing.T) {
	a := wrapped(t, header)
	got := analyzertest.RunInRepo(t, a, "p", map[string]string{
		"p.go":      "package p\n\nfunc f() {}\n",
		"p_test.go": "package p\n\nfunc g() {}\n",
	})
	analyzertest.Equal(t, got, []analyzertest.Diagnostic{
		{File: "p.go", Line: 3, Message: "func f"},
		{File: "p_test.go", Line: 3, Message: "func g"},
	})
}

func TestGeneratedFilesAreSkipped(t *testing.T) {
	files := map[string]string{
		// lax: any marker before the first declaration, in any case.
		"gen.go":  "// Package p is AutoGenerated File output.\npackage p\n\nfunc g() {}\n",
		"late.go": "package p\n\nfunc h() {}\n\n// Code generated by nothing; a marker after the first declaration.\n",
		"p.go":    "package p\n\n// Do Not Edit this one, says a lax reader.\nfunc f() {}\n",
	}
	analyzertest.Equal(t, analyzertest.RunInRepo(t, wrapped(t, header), "p", files),
		[]analyzertest.Diagnostic{{File: "late.go", Line: 3, Message: "func h"}})
	strict := header + "  exclusions:\n    generated: strict\n"
	analyzertest.Equal(t, analyzertest.RunInRepo(t, wrapped(t, strict), "p", files),
		[]analyzertest.Diagnostic{
			{File: "gen.go", Line: 4, Message: "func g"},
			{File: "late.go", Line: 3, Message: "func h"},
			{File: "p.go", Line: 4, Message: "func f"},
		})
}

func TestExclusionRules(t *testing.T) {
	yml := header + `  exclusions:
    rules:
      - path: '^a/'
        text: 'func drop'
        linters: [fake]
      - path-except: '^a/'
        linters: [fake]
      - text: 'func other'
        linters: [other]
`
	a := wrapped(t, yml)
	src := map[string]string{"p.go": "package p\n\nfunc keep() {}\n\nfunc drop() {}\n\nfunc other() {}\n"}
	analyzertest.Equal(t, analyzertest.RunInRepo(t, a, "a", src), []analyzertest.Diagnostic{
		{File: "p.go", Line: 3, Message: "func keep"},
		{File: "p.go", Line: 7, Message: "func other"},
	})
	// Outside a/, the path-except rule drops everything.
	analyzertest.Equal(t, analyzertest.RunInRepo(t, a, "b", src), nil)
}

func TestParseIsStrict(t *testing.T) {
	for name, yml := range map[string]string{
		"unknown key":        header + "  settings:\n    gosec:\n      config: {}\n",
		"unknown linter key": header + "  settings:\n    revive: {}\n",
		"version":            "version: \"1\"\nlinters:\n  default: none\n",
		"default":            "version: \"2\"\nlinters:\n  default: standard\n",
		"bad regexp":         header + "  exclusions:\n    rules:\n      - text: '('\n",
		"empty rule":         header + "  exclusions:\n    rules:\n      - {}\n",
	} {
		if _, err := golangci.Parse([]byte(yml)); err == nil {
			t.Errorf("%s: Parse accepted %q", name, yml)
		}
	}
}

func TestRepositoryConfigLoads(t *testing.T) {
	if _, err := golangci.Load(); err != nil {
		t.Fatal(err)
	}
}

func TestRelPath(t *testing.T) {
	for _, c := range []struct{ dir, name, want string }{
		{"/x/root", "/x/root/cmd/bd/a.go", "cmd/bd/a.go"},
		{"/x/root", "cmd/bd/a.go", "cmd/bd/a.go"},
		{"", "/abs/a.go", "/abs/a.go"},
	} {
		if got := golangci.RelPath(c.dir, c.name); got != c.want {
			t.Errorf("RelPath(%q, %q) = %q, want %q", c.dir, c.name, got, c.want)
		}
	}
}
