package golangci

import (
	"go/ast"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/analysis"
)

// Wrap returns an analyzer named linter that runs inner the way golangci-lint
// ran that linter under .golangci.yml:
//
//   - nothing, unless linters.enable lists it;
//   - with run.tests false, only on compile units without _test.go files.
//     golangci-lint then loads each package without its tests; Bazel compiles
//     that library unit on its own (go_library) beside the test unit, so the
//     library unit sees exactly what golangci-lint saw, unused-parameter and
//     unused-result verdicts included;
//   - no findings in generated files (linters.exclusions.generated);
//   - no findings an exclusion rule matches (linters.exclusions.rules).
//
// nogo honors //nolint itself (MODULE.bazel's rules_go patch).
func Wrap(linter string, inner *analysis.Analyzer) *analysis.Analyzer {
	return &analysis.Analyzer{
		Name:             linter,
		Doc:              inner.Doc,
		URL:              inner.URL,
		Flags:            inner.Flags,
		Requires:         inner.Requires,
		ResultType:       inner.ResultType,
		FactTypes:        inner.FactTypes,
		RunDespiteErrors: inner.RunDespiteErrors,
		Run: func(pass *analysis.Pass) (any, error) {
			cfg, err := Load()
			if err != nil {
				return nil, err
			}
			return Run(cfg, linter, inner, pass)
		},
	}
}

// Run runs inner on pass under cfg's rules for linter (see Wrap).
func Run(cfg *Config, linter string, inner *analysis.Analyzer, pass *analysis.Pass) (any, error) {
	if !cfg.Enabled(linter) {
		return nil, nil
	}
	if !cfg.TestsAnalyzed() && HasTestFiles(pass) {
		return nil, nil
	}
	generated := generatedFiles(cfg.GeneratedMode(), pass)
	cwd, err := os.Getwd()
	if err != nil {
		return nil, err
	}
	filtered := *pass
	filtered.Report = func(d analysis.Diagnostic) {
		tf := pass.Fset.File(d.Pos)
		if tf != nil && generated[tf.Name()] {
			return
		}
		path := RelPath(cwd, pass.Fset.Position(d.Pos).Filename)
		if cfg.Excluded(linter, path, d.Message) {
			return
		}
		pass.Report(d)
	}
	return inner.Run(&filtered)
}

// HasTestFiles reports whether the pass's compile unit includes _test.go
// files: Bazel's test unit of a package, not its library unit.
func HasTestFiles(pass *analysis.Pass) bool {
	for _, f := range pass.Files {
		if strings.HasSuffix(pass.Fset.File(f.Pos()).Name(), "_test.go") {
			return true
		}
	}
	return false
}

// RelPath returns name relative to dir (nogo runs in the execution root, the
// repository root for source files) with / separators, the form
// golangci-lint's exclusion paths match.
func RelPath(dir, name string) string {
	if filepath.IsAbs(name) && dir != "" {
		if rel, err := filepath.Rel(dir, name); err == nil {
			name = rel
		}
	}
	return filepath.ToSlash(name)
}

// The markers golangci-lint's lax mode looks for, lower case.
var laxGeneratedMarkers = []string{
	"code generated",
	"do not edit",
	"autogenerated file",
	"* generated by: swagger codegen ",
}

// generatedFiles returns the names of the pass's generated files, as
// golangci-lint's generated-file matcher decides them.
func generatedFiles(mode string, pass *analysis.Pass) map[string]bool {
	out := map[string]bool{}
	if mode == GeneratedDisable {
		return out
	}
	for _, f := range pass.Files {
		var gen bool
		if mode == GeneratedStrict {
			gen = ast.IsGenerated(f)
		} else {
			gen = IsGeneratedLax(f)
		}
		if gen {
			out[pass.Fset.File(f.Pos()).Name()] = true
		}
	}
	return out
}

// IsGeneratedLax is golangci-lint's lax test: a comment before the first
// token after the package clause (what parser.PackageClauseOnly reads)
// contains one of the markers, in any case.
func IsGeneratedLax(f *ast.File) bool {
	var doc []string
	for _, group := range f.Comments {
		if len(f.Decls) > 0 && group.Pos() >= f.Decls[0].Pos() {
			break
		}
		doc = append(doc, strings.TrimSpace(group.Text()))
	}
	text := strings.ToLower(strings.Join(doc, "\n"))
	for _, marker := range laxGeneratedMarkers {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}
