#!/usr/bin/env bash
# types_gen_drift_test.sh: `make api-check`'s drift half under Bazel. Regenerate
# types.gen.go from the spec as doc.go's `go generate` does, and fail with the
# diff when the committed copy is stale. Inputs are rlocation paths (BUILD
# env): COMMITTED, SPEC, GO_MOD, OAPI_CODEGEN and GO.
set -euo pipefail

r="${TEST_SRCDIR:?}"
work="${TEST_TMPDIR:?}/apigen"
rm -rf "$work"
mkdir -p "$work"

# The Bazel-built oapi-codegen has no module build info, so its "Code
# generated by" header names an unknown version; `go tool oapi-codegen` names
# go.mod's.
version=$(awk '$1 == "github.com/oapi-codegen/oapi-codegen/v2" { print $2; exit }' "$r/$GO_MOD")
if [[ -z "$version" ]]; then
	echo "go.mod does not require github.com/oapi-codegen/oapi-codegen/v2" >&2
	exit 1
fi

# oapi-codegen formats its output with golang.org/x/tools/imports, which runs
# `go env`: the registered SDK, outside any module, with a private, empty
# module cache and no network.
(
	cd "$work"
	PATH="$(dirname "$r/$GO"):$PATH" HOME="$work" GOPATH="$work/gopath" \
		GOMODCACHE="$work/gopath/pkg/mod" GOCACHE="$work/gocache" GOENV=off \
		GOFLAGS='' GOTOOLCHAIN=local GOPROXY=off \
		"$r/$OAPI_CODEGEN" -generate types,skip-prune -package apigen \
		-o "$work/types.raw.go" "$r/$SPEC"
)
sed "s|^// Code generated by unknown module path version unknown version DO NOT EDIT[.]$|// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version $version DO NOT EDIT.|" \
	"$work/types.raw.go" >"$work/types.gen.go"

if ! diff -u "$r/$COMMITTED" "$work/types.gen.go"; then
	echo "openapi drift: internal/httpapi/apigen/types.gen.go is stale for the current spec (regenerating it changed it)."
	echo "run 'make api-gen' and commit the result."
	exit 1
fi
echo "internal/httpapi/apigen/types.gen.go matches internal/httpapi/spec/openapi.v0.yaml (oapi-codegen $version)"
