// Code generated by internal/formula/cmd/schemagen. DO NOT EDIT.

package formula

// Primitives is the discoverability index of every exported struct in
// types.go. Surfaced via `bd formula schema`. Regenerate with `go generate ./...`.
var Primitives = []PrimitiveDoc{
	{
		Name: "AdviceRule",
		Doc: `AdviceRule defines a step transformation rule.
Advice operators insert steps before, after, or around matching targets.`,
		Fields: []FieldDoc{
			{
				Name:     "Target",
				Type:     "string",
				JSONName: "target",
				Required: true,
				Doc: `Target is a glob pattern matching step IDs to apply advice to.
Examples: "*.implement", "design", "shiny.*"`,
			},
			{
				Name:     "Before",
				Type:     "*AdviceStep",
				JSONName: "before",
				Doc:      `Before inserts a step before the target.`,
			},
			{
				Name:     "After",
				Type:     "*AdviceStep",
				JSONName: "after",
				Doc:      `After inserts a step after the target.`,
			},
			{
				Name:     "Around",
				Type:     "*AroundAdvice",
				JSONName: "around",
				Doc:      `Around wraps the target with before and after steps.`,
			},
		},
	},
	{
		Name: "AdviceStep",
		Doc:  `AdviceStep defines a step to insert via advice.`,
		Fields: []FieldDoc{
			{
				Name:     "ID",
				Type:     "string",
				JSONName: "id",
				Required: true,
				Doc:      `ID is the step identifier. Supports {step.id} substitution.`,
			},
			{
				Name:     "Title",
				Type:     "string",
				JSONName: "title",
				Doc:      `Title is the step title. Supports {step.id} substitution.`,
			},
			{
				Name:     "Description",
				Type:     "string",
				JSONName: "description",
				Doc:      `Description is the step description.`,
			},
			{
				Name:     "Type",
				Type:     "string",
				JSONName: "type",
				Doc:      `Type is the issue type (task, bug, etc).`,
			},
			{
				Name:     "Args",
				Type:     "map[string]string",
				JSONName: "args",
				Doc:      `Args are additional context passed to the step.`,
			},
			{
				Name:     "Output",
				Type:     "map[string]string",
				JSONName: "output",
				Doc:      `Output defines expected outputs from this step.`,
			},
		},
	},
	{
		Name: "AroundAdvice",
		Doc:  `AroundAdvice wraps a target with before and after steps.`,
		Fields: []FieldDoc{
			{
				Name:     "Before",
				Type:     "[]*AdviceStep",
				JSONName: "before",
				Doc:      `Before is a list of steps to insert before the target.`,
			},
			{
				Name:     "After",
				Type:     "[]*AdviceStep",
				JSONName: "after",
				Doc:      `After is a list of steps to insert after the target.`,
			},
		},
	},
	{
		Name: "BondPoint",
		Doc:  `BondPoint is a named attachment site for composition.`,
		Fields: []FieldDoc{
			{
				Name:     "ID",
				Type:     "string",
				JSONName: "id",
				Required: true,
				Doc:      `ID is the unique identifier for this bond point.`,
			},
			{
				Name:     "Description",
				Type:     "string",
				JSONName: "description",
				Doc:      `Description explains what should be attached here.`,
			},
			{
				Name:     "AfterStep",
				Type:     "string",
				JSONName: "after_step",
				Doc: `AfterStep is the step ID after which to attach.
Mutually exclusive with BeforeStep.`,
			},
			{
				Name:     "BeforeStep",
				Type:     "string",
				JSONName: "before_step",
				Doc: `BeforeStep is the step ID before which to attach.
Mutually exclusive with AfterStep.`,
			},
			{
				Name:     "Parallel",
				Type:     "bool",
				JSONName: "parallel",
				Doc:      `Parallel makes attached steps run in parallel with the anchor step.`,
			},
		},
	},
	{
		Name: "BranchRule",
		Doc: `BranchRule defines parallel execution paths that rejoin.
Creates a fork-join pattern: from -> [parallel steps] -> join.`,
		Fields: []FieldDoc{
			{
				Name:     "From",
				Type:     "string",
				JSONName: "from",
				Required: true,
				Doc: `From is the step ID that precedes the parallel paths.
All branch steps will depend on this step.`,
			},
			{
				Name:     "Steps",
				Type:     "[]string",
				JSONName: "steps",
				Required: true,
				Doc: `Steps are the step IDs that run in parallel.
These steps will all depend on From.`,
			},
			{
				Name:     "Join",
				Type:     "string",
				JSONName: "join",
				Required: true,
				Doc: `Join is the step ID that follows all parallel paths.
This step will depend on all Steps completing.`,
			},
		},
	},
	{
		Name: "ComposeRules",
		Doc:  `ComposeRules define how formulas can be bonded together.`,
		Fields: []FieldDoc{
			{
				Name:     "BondPoints",
				Type:     "[]*BondPoint",
				JSONName: "bond_points",
				Doc:      `BondPoints are named locations where other formulas can attach.`,
			},
			{
				Name:     "Hooks",
				Type:     "[]*Hook",
				JSONName: "hooks",
				Doc:      `Hooks are automatic attachments triggered by labels or conditions.`,
			},
			{
				Name:     "Expand",
				Type:     "[]*ExpandRule",
				JSONName: "expand",
				Doc: `Expand applies an expansion template to a single target step.
The target step is replaced by the expanded template steps.`,
			},
			{
				Name:     "Map",
				Type:     "[]*MapRule",
				JSONName: "map",
				Doc: `Map applies an expansion template to all steps matching a pattern.
Each matching step is replaced by the expanded template steps.`,
			},
			{
				Name:     "Branch",
				Type:     "[]*BranchRule",
				JSONName: "branch",
				Doc: `Branch defines fork-join parallel execution patterns.
Each rule creates dependencies for parallel paths that rejoin.`,
			},
			{
				Name:     "Gate",
				Type:     "[]*GateRule",
				JSONName: "gate",
				Doc: `Gate defines conditional waits before steps.
Each rule adds a condition that must be satisfied at runtime.`,
			},
			{
				Name:     "Aspects",
				Type:     "[]string",
				JSONName: "aspects",
				Doc: `Aspects lists aspect formula names to apply to this formula.
Aspects are applied after expansions, adding before/after/around
steps to matching targets based on the aspect's advice rules.
Example: ["security-audit", "logging"]`,
			},
		},
	},
	{
		Name: "ExpandRule",
		Doc:  `ExpandRule applies an expansion template to a single target step.`,
		Fields: []FieldDoc{
			{
				Name:     "Target",
				Type:     "string",
				JSONName: "target",
				Required: true,
				Doc:      `Target is the step ID to expand.`,
			},
			{
				Name:     "With",
				Type:     "string",
				JSONName: "with",
				Required: true,
				Doc:      `With is the name of the expansion formula to apply.`,
			},
			{
				Name:     "Vars",
				Type:     "map[string]string",
				JSONName: "vars",
				Doc:      `Vars are variable overrides for the expansion.`,
			},
		},
	},
	{
		Name: "Formula",
		Doc:  `Formula is the root structure for .formula.json files.`,
		Fields: []FieldDoc{
			{
				Name:     "Formula",
				Type:     "string",
				JSONName: "formula",
				Required: true,
				Doc: `Formula is the unique identifier/name for this formula.
Convention: mol-<name> for molecules, exp-<name> for expansions.`,
			},
			{
				Name:     "Description",
				Type:     "string",
				JSONName: "description",
				Doc:      `Description explains what this formula does.`,
			},
			{
				Name:     "Version",
				Type:     "int",
				JSONName: "version",
				Required: true,
				Doc:      `Version is the schema version (currently 1).`,
			},
			{
				Name:     "Type",
				Type:     "FormulaType",
				JSONName: "type",
				Required: true,
				Doc:      `Type categorizes the formula: workflow, expansion, or aspect.`,
			},
			{
				Name:     "Extends",
				Type:     "[]string",
				JSONName: "extends",
				Doc: `Extends is a list of parent formulas to inherit from.
The child formula inherits all vars, steps, and compose rules.
Child definitions override parent definitions with the same ID.`,
			},
			{
				Name:     "Vars",
				Type:     "map[string]*VarDef",
				JSONName: "vars",
				Doc:      `Vars defines template variables with defaults and validation.`,
			},
			{
				Name:     "Steps",
				Type:     "[]*Step",
				JSONName: "steps",
				Doc:      `Steps defines the work items to create.`,
			},
			{
				Name:     "Template",
				Type:     "[]*Step",
				JSONName: "template",
				Doc: `Template defines expansion template steps (for TypeExpansion formulas).
Template steps use {target} and {target.description} placeholders
that get substituted when the expansion is applied to a target step.`,
			},
			{
				Name:     "Compose",
				Type:     "*ComposeRules",
				JSONName: "compose",
				Doc:      `Compose defines composition/bonding rules.`,
			},
			{
				Name:     "Advice",
				Type:     "[]*AdviceRule",
				JSONName: "advice",
				Doc: `Advice defines step transformations (before/after/around).
Applied during cooking to insert steps around matching targets.`,
			},
			{
				Name:     "Pointcuts",
				Type:     "[]*Pointcut",
				JSONName: "pointcuts",
				Doc: `Pointcuts defines target patterns for aspect formulas.
Used with TypeAspect to specify which steps the aspect applies to.`,
			},
			{
				Name:     "Phase",
				Type:     "string",
				JSONName: "phase",
				Doc: `Phase indicates the recommended instantiation phase: "liquid" (pour) or "vapor" (wisp).
If "vapor", bd pour will warn and suggest using bd mol wisp instead.
Patrol and release workflows should typically use "vapor" since they're operational.`,
			},
			{
				Name:     "Pour",
				Type:     "bool",
				JSONName: "pour",
				Doc: `Pour controls whether steps are materialized as individual child issues.
If true, each step becomes a DB row with dependency tracking (checkpoint recovery).
If false (default), only the root issue is created; steps are read inline at prime time.
Reserve pour=true for critical, infrequent work (e.g. releases) where step-level
tracking is worth the DB overhead. Patrol formulas should NOT set this.`,
			},
			{
				Name:     "Source",
				Type:     "string",
				JSONName: "source",
				Doc:      `Source tracks where this formula was loaded from (set by parser).`,
			},
			{
				Name:     "Intent",
				Type:     "string",
				JSONName: "intent",
				Doc: `Intent is an optional caller-defined hint about the formula's runtime
intent (e.g. "mail_only"). Opaque to bd; consumed by downstream tools.`,
			},
		},
	},
	{
		Name: "Gate",
		Doc: `Gate defines an async wait condition for formula steps.
When a step has a Gate, bd cook creates a gate issue that blocks the step.
The gate must be closed (manually or via watchers) to unblock the step.`,
		Fields: []FieldDoc{
			{
				Name:     "Type",
				Type:     "string",
				JSONName: "type",
				Required: true,
				Doc:      `Type is the condition type: gh:run, gh:pr, timer, human, mail.`,
			},
			{
				Name:     "ID",
				Type:     "string",
				JSONName: "id",
				Doc:      `ID is the condition identifier (e.g., workflow name for gh:run).`,
			},
			{
				Name:     "AwaitID",
				Type:     "string",
				JSONName: "await_id",
				Doc: `AwaitID is the runtime condition identifier. This is preferred by
formula authors because it maps directly to Issue.AwaitID.`,
			},
			{
				Name:     "Timeout",
				Type:     "string",
				JSONName: "timeout",
				Doc:      `Timeout is how long to wait before escalation (e.g., "1h", "24h").`,
			},
		},
	},
	{
		Name: "GateRule",
		Doc: `GateRule defines a condition that must be satisfied before a step proceeds.
Gates are evaluated at runtime by the patrol executor.`,
		Fields: []FieldDoc{
			{
				Name:     "Before",
				Type:     "string",
				JSONName: "before",
				Required: true,
				Doc: `Before is the step ID that the gate applies to.
The condition must be satisfied before this step can start.`,
			},
			{
				Name:     "Condition",
				Type:     "string",
				JSONName: "condition",
				Required: true,
				Doc: `Condition is the expression to evaluate.
Format matches condition evaluator syntax (e.g., "tests.status == 'complete'").`,
			},
		},
	},
	{
		Name: "Hook",
		Doc:  `Hook defines automatic formula attachment based on conditions.`,
		Fields: []FieldDoc{
			{
				Name:     "Trigger",
				Type:     "string",
				JSONName: "trigger",
				Required: true,
				Doc: `Trigger is what activates this hook.
Formats: "label:security", "type:bug", "priority:0-1".`,
			},
			{
				Name:     "Attach",
				Type:     "string",
				JSONName: "attach",
				Required: true,
				Doc:      `Attach is the formula to attach when triggered.`,
			},
			{
				Name:     "At",
				Type:     "string",
				JSONName: "at",
				Doc:      `At is the bond point to attach at (default: end).`,
			},
			{
				Name:     "Vars",
				Type:     "map[string]string",
				JSONName: "vars",
				Doc:      `Vars are variable overrides for the attached formula.`,
			},
		},
	},
	{
		Name: "LoopSpec",
		Doc: `LoopSpec defines iteration over a body of steps.
One of Count, Until, or Range must be specified.`,
		Fields: []FieldDoc{
			{
				Name:     "Count",
				Type:     "int",
				JSONName: "count",
				Doc: `Count is the fixed number of iterations.
When set, the loop body is expanded Count times.`,
			},
			{
				Name:     "Until",
				Type:     "string",
				JSONName: "until",
				Doc: `Until is a condition that ends the loop.
Format matches condition evaluator syntax (e.g., "step.status == 'complete'").`,
			},
			{
				Name:     "Max",
				Type:     "int",
				JSONName: "max",
				Doc: `Max is the maximum iterations for conditional loops.
Required when Until is set, to prevent unbounded loops.`,
			},
			{
				Name:     "Range",
				Type:     "string",
				JSONName: "range",
				Doc: `Range specifies a computed range for iteration.
Format: "start..end" where start and end can be:
  - Integers: "1..10"
  - Expressions: "1..2^{disks}" (evaluated at cook time)
  - Variables: "{start}..{count}" (substituted from Vars)
Supports: + - * / ^ (power) and parentheses.`,
			},
			{
				Name:     "Var",
				Type:     "string",
				JSONName: "var",
				Doc: `Var is the variable name exposed to body steps.
For Range loops, this is set to the current iteration value.
Example: var: "move_num" with range: "1..7" exposes {move_num}=1,2,...,7`,
			},
			{
				Name:     "Body",
				Type:     "[]*Step",
				JSONName: "body",
				Required: true,
				Doc:      `Body contains the steps to repeat.`,
			},
		},
	},
	{
		Name: "MapRule",
		Doc:  `MapRule applies an expansion template to all matching steps.`,
		Fields: []FieldDoc{
			{
				Name:     "Select",
				Type:     "string",
				JSONName: "select",
				Required: true,
				Doc: `Select is a glob pattern matching step IDs to expand.
Examples: "*.implement", "shiny.*"`,
			},
			{
				Name:     "With",
				Type:     "string",
				JSONName: "with",
				Required: true,
				Doc:      `With is the name of the expansion formula to apply.`,
			},
			{
				Name:     "Vars",
				Type:     "map[string]string",
				JSONName: "vars",
				Doc:      `Vars are variable overrides for the expansion.`,
			},
		},
	},
	{
		Name: "OnCompleteSpec",
		Doc: `OnCompleteSpec defines actions triggered when a step completes.
Used for runtime expansion over step output (the for-each construct).

Example YAML:

	step: survey-workers
	on_complete:
	  for_each: output.workers
	  bond: mol-worker-arm
	  vars:
	    worker_name: "{item.name}"
	    rig: "{item.rig}"
	  parallel: true`,
		Fields: []FieldDoc{
			{
				Name:     "ForEach",
				Type:     "string",
				JSONName: "for_each",
				Doc: `ForEach is the path to the iterable collection in step output.
Format: "output.<field>" or "output.<field>.<nested>"
The collection must be an array at runtime.`,
			},
			{
				Name:     "Bond",
				Type:     "string",
				JSONName: "bond",
				Doc: `Bond is the formula to instantiate for each item.
A new molecule is created for each element in the ForEach collection.`,
			},
			{
				Name:     "Vars",
				Type:     "map[string]string",
				JSONName: "vars",
				Doc: `Vars are variable bindings for each iteration.
Supports placeholders:
  - {item} - the current item value (for primitives)
  - {item.field} - a field from the current item (for objects)
  - {index} - the zero-based iteration index`,
			},
			{
				Name:     "Parallel",
				Type:     "bool",
				JSONName: "parallel",
				Doc: `Parallel runs all bonded molecules concurrently (default behavior).
Set to true to make this explicit.`,
			},
			{
				Name:     "Sequential",
				Type:     "bool",
				JSONName: "sequential",
				Doc: `Sequential runs bonded molecules one at a time.
Each molecule starts only after the previous one completes.
Mutually exclusive with Parallel.`,
			},
		},
	},
	{
		Name: "Pointcut",
		Doc: `Pointcut defines a target pattern for advice application.
Used in aspect formulas to specify which steps the advice applies to.`,
		Fields: []FieldDoc{
			{
				Name:     "Glob",
				Type:     "string",
				JSONName: "glob",
				Doc: `Glob is a glob pattern to match step IDs.
Examples: "*.implement", "shiny.*", "review"`,
			},
			{
				Name:     "Type",
				Type:     "string",
				JSONName: "type",
				Doc: `Type matches steps by their type field.
Examples: "task", "bug", "epic"`,
			},
			{
				Name:     "Label",
				Type:     "string",
				JSONName: "label",
				Doc:      `Label matches steps that have a specific label.`,
			},
		},
	},
	{
		Name: "Step",
		Doc:  `Step defines a work item to create when the formula is instantiated.`,
		Fields: []FieldDoc{
			{
				Name:     "ID",
				Type:     "string",
				JSONName: "id",
				Required: true,
				Doc: `ID is the unique identifier within this formula.
Used for dependency references and bond points.`,
			},
			{
				Name:     "Title",
				Type:     "string",
				JSONName: "title",
				Required: true,
				Doc:      `Title is the issue title (supports {{variable}} substitution).`,
			},
			{
				Name:     "Description",
				Type:     "string",
				JSONName: "description",
				Doc:      `Description is the issue description (supports substitution).`,
			},
			{
				Name:     "Notes",
				Type:     "string",
				JSONName: "notes",
				Doc:      `Notes are additional notes for the issue (supports substitution).`,
			},
			{
				Name:     "Type",
				Type:     "string",
				JSONName: "type",
				Doc:      `Type is the issue type: task, bug, feature, epic, chore.`,
			},
			{
				Name:     "Priority",
				Type:     "*int",
				JSONName: "priority",
				Doc:      `Priority is the issue priority (0-4).`,
			},
			{
				Name:     "Labels",
				Type:     "[]string",
				JSONName: "labels",
				Doc:      `Labels are applied to the created issue.`,
			},
			{
				Name:     "Metadata",
				Type:     "map[string]interface{}",
				JSONName: "metadata",
				Doc: `Metadata is carried through to the created issue's Metadata field as
JSON. Lets formulas pre-declare keys that downstream tooling can project
without a post-pour compose step.`,
			},
			{
				Name:     "DependsOn",
				Type:     "[]string",
				JSONName: "depends_on",
				Doc:      `DependsOn lists step IDs this step blocks on (within the formula).`,
			},
			{
				Name:     "Needs",
				Type:     "[]string",
				JSONName: "needs",
				Doc: `Needs is a simpler alias for DependsOn - lists sibling step IDs that must complete first.
Either Needs or DependsOn can be used; they are merged during cooking.`,
			},
			{
				Name:     "WaitsFor",
				Type:     "string",
				JSONName: "waits_for",
				Doc: `WaitsFor specifies a fanout gate type for this step.
Values: "all-children" (wait for all dynamic children) or "any-children" (wait for first).
When set, the cooked issue gets a "gate:<value>" label.`,
			},
			{
				Name:     "Assignee",
				Type:     "string",
				JSONName: "assignee",
				Doc:      `Assignee is the default assignee (supports substitution).`,
			},
			{
				Name:     "Expand",
				Type:     "string",
				JSONName: "expand",
				Doc: `Expand references an expansion formula to inline here.
When set, this step is replaced by the expansion's template steps.
See ApplyInlineExpansions in expand.go for implementation.`,
			},
			{
				Name:     "ExpandVars",
				Type:     "map[string]string",
				JSONName: "expand_vars",
				Doc: `ExpandVars are variable overrides for the expansion.
Merged with the expansion formula's default vars during inline expansion.`,
			},
			{
				Name:     "Condition",
				Type:     "string",
				JSONName: "condition",
				Doc: `Condition makes this step optional based on a variable.
Format: "{{var}}" (truthy), "!{{var}}" (negated), "{{var}} == value", "{{var}} != value".
Evaluated at cook/pour time via FilterStepsByCondition.`,
			},
			{
				Name:     "Children",
				Type:     "[]*Step",
				JSONName: "children",
				Doc:      `Children are nested steps (for creating epic hierarchies).`,
			},
			{
				Name:     "Gate",
				Type:     "*Gate",
				JSONName: "gate",
				Doc: `Gate defines an async wait condition for this step.
When set, bd cook creates a gate issue that blocks this step.
Close the gate issue (bd close bd-xxx.gate-stepid) to unblock.`,
			},
			{
				Name:     "Loop",
				Type:     "*LoopSpec",
				JSONName: "loop",
				Doc: `Loop defines iteration for this step.
When set, the step becomes a container that expands its body.`,
			},
			{
				Name:     "OnComplete",
				Type:     "*OnCompleteSpec",
				JSONName: "on_complete",
				Doc: `OnComplete defines actions triggered when this step completes.
Used for runtime expansion over step output (the for-each construct).`,
			},
		},
	},
	{
		Name: "VarDef",
		Doc:  `VarDef defines a template variable with optional validation.`,
		Fields: []FieldDoc{
			{
				Name:     "Description",
				Type:     "string",
				JSONName: "description",
				Doc:      `Description explains what this variable is for.`,
			},
			{
				Name:     "Default",
				Type:     "*string",
				JSONName: "default",
				Doc: `Default is the value to use if not provided.
nil means no default (variable must be provided if referenced).
Non-nil (including &"") means the variable has an explicit default.`,
			},
			{
				Name:     "Required",
				Type:     "bool",
				JSONName: "required",
				Doc:      `Required indicates the variable must be provided (no default).`,
			},
			{
				Name:     "Enum",
				Type:     "[]string",
				JSONName: "enum",
				Doc:      `Enum lists the allowed values (if non-empty).`,
			},
			{
				Name:     "Pattern",
				Type:     "string",
				JSONName: "pattern",
				Doc:      `Pattern is a regex pattern the value must match.`,
			},
			{
				Name:     "Type",
				Type:     "string",
				JSONName: "type",
				Doc:      `Type is the expected value type: string (default), int, bool.`,
			},
		},
	},
	{
		Name: "WaitsForSpec",
		Doc:  `WaitsForSpec holds the parsed waits_for field.`,
		Fields: []FieldDoc{
			{
				Name:     "Gate",
				Type:     "string",
				JSONName: "Gate",
				Required: true,
				Doc:      `Gate is the gate type: "all-children" or "any-children"`,
			},
			{
				Name:     "SpawnerID",
				Type:     "string",
				JSONName: "SpawnerID",
				Required: true,
				Doc: `SpawnerID is the step ID whose children to wait for.
Empty means infer from context (typically first step in needs).`,
			},
		},
	},
}
