package schema

import (
	"context"
	"fmt"
	"log"
	"strings"

	"github.com/steveyegge/beads/internal/debug"
	"github.com/steveyegge/beads/internal/storage/dberrors"
)

// The ignored-lane migration cursor is dolt_ignore'd on every database this
// binary opens, but dolt_ignore only exempts tables that have never been
// committed: like git's .gitignore, an ignore entry has no effect on a path
// that is already tracked. On lineages old enough to predate the pattern the
// cursor table WAS committed, and nothing in bd can ever clean it again —
// every staging path anti-joins dolt_ignore, so each migration pass re-dirties
// a tracked table that no commit will ever pick up. Dolt's merge preflight
// refuses to start while a tracked table is dirty, so those databases push
// fine and every single `bd dolt pull` dies with
//
//	Error 1105: cannot merge with uncommitted changes
//
// permanently (gastownhall/beads#4356; confirmed on two fleets, 24 and 17
// databases).
//
// The only way to make dolt_ignore effective again is to turn the table's
// presence back into an ADD delta: commit a deletion of the table into HEAD,
// then recreate it in the working set. That is exactly what migration
// 0062_events_dolt_ignore did for `events`, down to the transaction-pinning
// and force-staging quirks; this file is that same operation for the cursor
// table, in Go and re-entrant.
//
// It is deliberately NOT a numbered migration. A one-shot migration runs only
// while the main cursor is behind, and the affected databases are at-latest
// (their dirt is residue of a COMPLETED pass). Worse, a pull that merges a
// not-yet-healed peer's commits re-introduces the tracked table afterwards,
// and a spent migration never re-runs — the multi-machine fleets that are the
// entire affected population would re-wedge permanently. Re-probing at every
// writable open is what makes the heal converge instead of expire.
const (
	// ignoredCursorUntrackTempTable holds the cursor rows across the drop.
	// Dolt persists the working set to disk, so an uncommitted scratch table
	// survives a crash: whatever phase is interrupted, the next open finds
	// the rows and finishes the job. The name is deliberately not matched by
	// any dolt_ignore pattern — a straggler must show up in dolt_status
	// rather than hide.
	ignoredCursorUntrackTempTable = "__temp__ignored_schema_migrations_untrack"

	ignoredCursorUntrackCommitMessage = "schema: untrack legacy ignored_schema_migrations so dolt_ignore can apply (gastownhall/beads#4356)"

	ignoredCursorTempSweepCommitMessage = "schema: drop stray ignored_schema_migrations untrack scratch table (gastownhall/beads#4356)"
)

// ignoredCursorScratch exists so the scratch table's DDL is generated by the
// SAME bootstrapSQL that builds the real cursor table. The shape has already
// drifted once out of band (#4259 added content_hash); a hand-copied CREATE
// would silently stop carrying the next column, and this table is the only
// copy of the cursor while the repair runs.
var ignoredCursorScratch = migrationSource{cursorTable: ignoredCursorUntrackTempTable}

// ignoredCursorAdvisory reports a reconcile step that declined without
// changing anything. Overridable in tests: the whole point of the advisory
// path is that it is invisible in production, which is exactly how a missing
// sqlmock expectation used to pass as a healthy run.
var ignoredCursorAdvisory = func(format string, args ...any) {
	debug.Logf(format, args...)
}

// ignoredCursorState is the reconcile's read-only gate. Both callers evaluate
// it — MigrateUp to decide what to do, alreadyConverged to decide whether the
// locked path has anything to do at all. Keeping it one function is not
// tidiness: a term present here but forgotten in alreadyConverged is silently
// unreachable in server mode, because that fast path short-circuits before
// MigrateUp ever runs.
type ignoredCursorState struct {
	// needsUntrack: the legacy shape — cursor table committed at HEAD while
	// dolt_ignore genuinely covers it.
	needsUntrack bool
	// strayScratch: a scratch table survives from an interrupted repair.
	// Left alone it is eventually committed into HEAD by an unrelated
	// auto-commit and replicated fleet-wide, and it keeps the resurrection
	// hazard armed (see resumeIgnoredCursorUntrack).
	strayScratch bool
}

func (s ignoredCursorState) reconcileNeeded() bool {
	return s.needsUntrack || s.strayScratch
}

// readIgnoredCursorState answers both halves of the gate in two
// always-succeeding reads. That property is not incidental: a Dolt session
// that issues a FAILING statement stays pinned to its pre-statement catalog
// snapshot for the rest of its pooled life (be-bv7x), and this runs on every
// writable open and every lock-free fast-path evaluation.
//
// qualifier is the identifier-quoted database name selectTargetDatabase
// returned, or empty when the session is already on the target database. The
// scratch probe needs no qualifier: it reads information_schema against
// DATABASE(), which both callers have already put on the target.
func readIgnoredCursorState(ctx context.Context, db DBConn, qualifier string) (ignoredCursorState, error) {
	var state ignoredCursorState

	needsUntrack, err := ignoredCursorNeedsUntrack(ctx, db, qualifier)
	if err != nil {
		return state, err
	}
	state.needsUntrack = needsUntrack

	stray, err := schemaTableExists(ctx, db, ignoredCursorUntrackTempTable)
	if err != nil {
		return state, fmt.Errorf("probing %s: %w", ignoredCursorUntrackTempTable, err)
	}
	state.strayScratch = stray
	return state, nil
}

// healTrackedIgnoredCursorTable untracks a legacy tracked-at-HEAD
// ignored_schema_migrations table and restores its rows, reporting whether it
// changed anything. It runs on every writable open and costs two reads on a
// healthy database.
//
// Failure policy, straight from the #5816 lesson that a heal must never mint a
// new class of un-openable database: everything up to and including the
// unstage sweep is advisory — a read that fails, a fenced client with no DDL
// or DOLT_RESET grant, a database an operator deliberately opted out of — and
// degrades to "log it and carry on", leaving the caller exactly as well off as
// it was before this function existed (open works, reads/writes/push work,
// pull stays wedged until some privileged open heals it). From the DROP onward
// a failure is returned: the pass must not continue without a cursor table,
// and every intermediate state that can persist is one the next open resumes
// from.
func healTrackedIgnoredCursorTable(ctx context.Context, db DBConn) (bool, error) {
	state, err := readIgnoredCursorState(ctx, db, "")
	if err != nil {
		ignoredCursorAdvisory("schema: cannot read the %s reconcile gate, leaving it alone: %v\n",
			ignoredSource.cursorTable, err)
		return false, nil
	}
	if !state.reconcileNeeded() {
		return false, nil
	}
	if !state.needsUntrack {
		return resumeIgnoredCursorUntrack(ctx, db)
	}

	// Advisory zone. Nothing here is destructive: a partial scratch table is
	// harmless, and the next open re-runs from the top.
	if err := backupIgnoredCursorRows(ctx, db); err != nil {
		ignoredCursorAdvisory("schema: cannot back up %s rows, leaving the tracked table in place: %v\n",
			ignoredSource.cursorTable, err)
		return false, nil
	}
	if err := unstageBeforeIgnoredCursorUntrack(ctx, db); err != nil {
		ignoredCursorAdvisory("schema: cannot clear the staging area before untracking %s, leaving it in place: %v\n",
			ignoredSource.cursorTable, err)
		return false, nil
	}

	// Announced here and nowhere earlier: every step above can decline, and a
	// fleet whose clients cannot run DDL would otherwise be told its database
	// was being repaired on every single open, forever, while the only
	// truthful record was debug-gated.
	log.Printf("schema: %s is tracked at HEAD on this database, which permanently wedges `bd dolt pull`; untracking it and preserving its rows (gastownhall/beads#4356)",
		ignoredSource.cursorTable)

	if err := commitIgnoredCursorUntrack(ctx, db); err != nil {
		return false, err
	}
	if err := restoreIgnoredCursorRows(ctx, db); err != nil {
		return false, err
	}
	return true, nil
}

// resumeIgnoredCursorUntrack finishes a repair some earlier open started and
// did not complete. The cursor table is not in the legacy shape — it may be
// healthy, or missing entirely — and a scratch table survives.
//
// It deliberately does NOT trust that scratch as a source of rows unless the
// cursor table is actually absent. The restore's union semantics exist so no
// recorded migration version is lost across a crash, but pointed at a LIVE
// cursor table they invert the sanctioned bad-release recovery, which is a
// cursor ROLLBACK: the operator deletes cursor rows so a corrected migration
// series re-applies (docs/recovery). Re-inserting exactly those versions, with
// their old applied_at, would silently skip the corrected migrations. When the
// cursor table is present the scratch is stale bookkeeping and the only
// correct action is to remove it.
func resumeIgnoredCursorUntrack(ctx context.Context, db DBConn) (bool, error) {
	// The operator veto is re-read here, not inherited: an operator who
	// resolved a crashed repair by deliberately versioning the cursor table
	// must not have stale rows pushed back into it on the next open.
	ignored, err := tableActivelyIgnored(ctx, db, "", ignoredSource.cursorTable)
	if err != nil {
		ignoredCursorAdvisory("schema: cannot read dolt_ignore, leaving %s alone: %v\n",
			ignoredCursorUntrackTempTable, err)
		return false, nil
	}
	cursorPresent, err := schemaTableExists(ctx, db, ignoredSource.cursorTable)
	if err != nil {
		ignoredCursorAdvisory("schema: cannot probe %s, leaving %s alone: %v\n",
			ignoredSource.cursorTable, ignoredCursorUntrackTempTable, err)
		return false, nil
	}

	log.Printf("schema: cleaning up after an interrupted %s untrack (gastownhall/beads#4356)",
		ignoredSource.cursorTable)

	restore := !cursorPresent && ignored
	if restore {
		err = restoreIgnoredCursorRows(ctx, db)
	} else {
		err = dropIgnoredCursorScratch(ctx, db)
	}
	if err != nil {
		// A client with no DDL grant can REACH this state without having
		// created it — some privileged opener crashed mid-repair — and the
		// database is fully usable in it. Bricking every open of that client
		// would be a brand-new failure class, which is the one thing #5816
		// says a heal must never do. Everything here is idempotent, so
		// declining costs only the cleanup, until a privileged open finishes.
		if dberrors.IsAccessDenied(err) {
			ignoredCursorAdvisory("schema: not permitted to finish the interrupted %s untrack; continuing without it: %v\n",
				ignoredSource.cursorTable, err)
			return false, nil
		}
		return false, err
	}
	return true, nil
}

// ignoredCursorNeedsUntrack reports whether this database carries the legacy
// shape: the ignored-lane cursor table committed at HEAD *and* covered by an
// active dolt_ignore pattern. Both terms matter. The first is the wedge
// itself. The second is the operator's veto.
func ignoredCursorNeedsUntrack(ctx context.Context, db DBConn, qualifier string) (bool, error) {
	tracked, err := tableTrackedAtHead(ctx, db, qualifier, ignoredSource.cursorTable)
	if err != nil || !tracked {
		return false, err
	}
	return tableActivelyIgnored(ctx, db, qualifier, ignoredSource.cursorTable)
}

// tableTrackedAtHead reports whether table is committed at HEAD, which is the
// only question dolt_ignore's ADD-delta semantics actually turn on.
//
// It asks by LISTING HEAD rather than by selecting from the table itself. The
// direct spelling (`SELECT … AS OF 'HEAD'`, table-not-found means untracked)
// is the one the field diagnosed with and is unambiguous, but as a probe it is
// exactly the mistake be-bv7x cost us: a Dolt session that issues a FAILING
// statement stays pinned to its pre-statement catalog snapshot for the rest of
// its pooled life, and on a healthy database that probe fails EVERY time, on
// EVERY open. The LIKE form always succeeds and returns at most one row, so
// this costs the same as every other steady-state scalar probe.
//
// The returned name is compared exactly rather than trusted from the LIKE:
// '_' is a LIKE single-character wildcard and the cursor table's name is full
// of them.
func tableTrackedAtHead(ctx context.Context, db DBConn, qualifier, table string) (bool, error) {
	from := ""
	if qualifier != "" {
		// The AS OF clause must trail the FROM; `SHOW TABLES AS OF … FROM x`
		// is a syntax error.
		from = " FROM " + qualifier
	}
	//nolint:gosec // G201: both the qualifier and the table name are package constants.
	query := "SHOW TABLES" + from + " AS OF 'HEAD' LIKE '" + table + "'"
	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return false, fmt.Errorf("listing %s at HEAD: %w", table, err)
	}
	defer func() { _ = rows.Close() }()

	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return false, fmt.Errorf("listing %s at HEAD: %w", table, err)
		}
		if strings.EqualFold(name, table) {
			return true, nil
		}
	}
	if err := rows.Err(); err != nil {
		return false, fmt.Errorf("listing %s at HEAD: %w", table, err)
	}
	return false, nil
}

// tableActivelyIgnored reports whether dolt_ignore genuinely exempts table.
//
// Dolt does not treat dolt_ignore as "any matching row wins": conflicting
// patterns resolve MOST SPECIFIC FIRST (doltdb's resolveConflictingPatterns).
// Counting any matching ignored=1 row therefore gets the answer backwards on a
// database that carries a broad house pattern next to an exact override —
// verified against the engine: with ('zz%', 1) and ('zzprobe', 0), Dolt
// TRACKS zzprobe while a naive count calls it ignored. Believing the count
// there would make this file drop and commit away a table the operator
// explicitly chose to keep versioned, which is unrecoverable.
//
// Rather than re-implement Dolt's specificity ordering (and its LIKE
// semantics) in Go, this resolves the two cases it can prove and declines
// otherwise:
//
//   - an exact-name row is maximally specific, so it always wins outright;
//   - with no exact row, any matching ignored=0 pattern means the operator's
//     intent cannot be established from a wildcard comparison we are not
//     doing — decline.
//
// Declining is always safe: it skips the repair, and the database is exactly
// as it was. Every canonical pattern this file cares about is seeded by
// seedDoltIgnorePatterns as an exact name, so the common paths take the first
// branch.
func tableActivelyIgnored(ctx context.Context, db DBConn, qualifier, table string) (bool, error) {
	doltIgnore := "dolt_ignore"
	if qualifier != "" {
		doltIgnore = qualifier + ".dolt_ignore"
	}
	rows, err := db.QueryContext(ctx,
		"SELECT pattern, ignored FROM "+doltIgnore+" WHERE ? LIKE pattern", table)
	if err != nil {
		return false, fmt.Errorf("reading dolt_ignore: %w", err)
	}
	defer func() { _ = rows.Close() }()

	wildcardIgnored, wildcardTracked := false, false
	for rows.Next() {
		var pattern string
		var ignored bool
		if err := rows.Scan(&pattern, &ignored); err != nil {
			return false, fmt.Errorf("reading dolt_ignore: %w", err)
		}
		if strings.EqualFold(pattern, table) {
			return ignored, nil
		}
		if ignored {
			wildcardIgnored = true
		} else {
			wildcardTracked = true
		}
	}
	if err := rows.Err(); err != nil {
		return false, fmt.Errorf("reading dolt_ignore: %w", err)
	}
	if wildcardTracked {
		return false, nil
	}
	return wildcardIgnored, nil
}

// backupIgnoredCursorRows mirrors the cursor rows into the scratch table.
//
// It MIRRORS rather than unions. A scratch table left by an earlier
// interrupted run can hold versions the operator has since deliberately
// deleted (the sanctioned bad-release recovery is a cursor rollback), and
// unioning them back in would silently skip the corrected migrations. The live
// table is the truth right up until the drop, so the scratch is made to match
// it exactly.
//
// A source table that is missing is not an error. It is the crash window
// between the drop and its commit: HEAD still carries the table (which is why
// the gate sent us here), the working set no longer does, and the rows are
// already safe in the scratch table from the interrupted run — which is then
// the only copy, and is left untouched.
func backupIgnoredCursorRows(ctx context.Context, db DBConn) error {
	if _, err := db.ExecContext(ctx, ignoredCursorScratch.bootstrapSQL()); err != nil {
		return fmt.Errorf("creating %s: %w", ignoredCursorUntrackTempTable, err)
	}
	present, err := schemaTableExists(ctx, db, ignoredSource.cursorTable)
	if err != nil {
		return fmt.Errorf("probing %s: %w", ignoredSource.cursorTable, err)
	}
	if !present {
		return nil
	}
	columns, err := ignoredCursorCopyColumns(ctx, db, ignoredSource.cursorTable)
	if err != nil {
		return err
	}
	//nolint:gosec // G201: the table name is a constant.
	if _, err := db.ExecContext(ctx, "DELETE FROM "+ignoredCursorUntrackTempTable); err != nil {
		return fmt.Errorf("clearing %s: %w", ignoredCursorUntrackTempTable, err)
	}
	//nolint:gosec // G201: both table names are constants and the column list is a fixed allowlist.
	copySQL := "INSERT IGNORE INTO " + ignoredCursorUntrackTempTable + " (" + columns + ") SELECT " + columns +
		" FROM " + ignoredSource.cursorTable
	if _, err := db.ExecContext(ctx, copySQL); err != nil {
		return fmt.Errorf("copying %s rows to %s: %w", ignoredSource.cursorTable, ignoredCursorUntrackTempTable, err)
	}
	return nil
}

// unstageBeforeIgnoredCursorUntrack clears the staging area so the scoped
// commit below carries nothing but the table deletion — the hazard 0040/0041's
// commitNonlocalRepair documents. It is the last advisory step: a client whose
// grant covers CREATE and INSERT but not CALL DOLT_RESET must decline here
// rather than fail its open forever.
func unstageBeforeIgnoredCursorUntrack(ctx context.Context, db DBConn) error {
	dirty, err := dirtyTables(ctx, db, false)
	if err != nil {
		return fmt.Errorf("reading working set: %w", err)
	}
	return unstagePreExistingTables(ctx, db, dirty)
}

// commitIgnoredCursorUntrack drops the tracked cursor table and commits the
// deletion into HEAD, which is the whole point: after this commit the table's
// presence is an ADD delta again and dolt_ignore genuinely exempts it.
//
// Every statement here is load-bearing, and each one is a lesson 0062 already
// paid for:
//
//   - the bare COMMIT, because on the sql-server path migrations run on a
//     transaction-pinned connection and Dolt's staging procedures read the
//     working set, which an open transaction has not published yet. It is a
//     no-op on the autocommit paths (embedded engine, dolt CLI);
//   - the '-f' on DOLT_ADD, because a plain add of a dolt_ignore'd table is a
//     silent no-op, and the table is ignored by construction here — without
//     the force the drop never stages, the recreate below nets it back out,
//     and the database stays exactly as wedged as it started;
//   - '--skip-empty', because a replay from an intermediate state would
//     otherwise die on "nothing to commit" (the 0040/0041 lesson).
func commitIgnoredCursorUntrack(ctx context.Context, db DBConn) error {
	//nolint:gosec // G201: the table name is a constant.
	if _, err := db.ExecContext(ctx, "DROP TABLE IF EXISTS "+ignoredSource.cursorTable); err != nil {
		return fmt.Errorf("dropping tracked %s: %w", ignoredSource.cursorTable, err)
	}
	if _, err := db.ExecContext(ctx, "COMMIT"); err != nil {
		return fmt.Errorf("publishing the %s drop: %w", ignoredSource.cursorTable, err)
	}
	if err := DrainCall(ctx, db, "CALL DOLT_ADD('-f', ?)", ignoredSource.cursorTable); err != nil {
		return fmt.Errorf("staging the %s drop: %w", ignoredSource.cursorTable, err)
	}
	if err := DrainCall(ctx, db, "CALL DOLT_COMMIT('--skip-empty', '-m', ?)", ignoredCursorUntrackCommitMessage); err != nil {
		return fmt.Errorf("committing the %s drop: %w", ignoredSource.cursorTable, err)
	}
	return nil
}

// restoreIgnoredCursorRows recreates the cursor table in the working set and
// puts the rows back. The recreated table has never been committed on this
// lineage, so it is an ADD delta — the same shape a fresh clone has, on which
// this wedge is impossible by construction.
//
// Only ever called with the cursor table absent, so the INSERT cannot
// resurrect rows a live table no longer has.
func restoreIgnoredCursorRows(ctx context.Context, db DBConn) error {
	if _, err := db.ExecContext(ctx, ignoredSource.bootstrapSQL()); err != nil {
		return fmt.Errorf("recreating %s: %w", ignoredSource.cursorTable, err)
	}
	// The column list is read off the SCRATCH table: it may have been written
	// by an older binary whose cursor shape had fewer columns.
	columns, err := ignoredCursorCopyColumns(ctx, db, ignoredCursorUntrackTempTable)
	if err != nil {
		return err
	}
	//nolint:gosec // G201: both table names are constants and the column list is a fixed allowlist.
	restoreSQL := "INSERT IGNORE INTO " + ignoredSource.cursorTable + " (" + columns + ") SELECT " + columns +
		" FROM " + ignoredCursorUntrackTempTable
	if _, err := db.ExecContext(ctx, restoreSQL); err != nil {
		return fmt.Errorf("restoring %s rows: %w", ignoredSource.cursorTable, err)
	}
	return dropIgnoredCursorScratch(ctx, db)
}

// dropIgnoredCursorScratch removes the scratch table and cleans up after the
// one window in which it can end up tracked: it carries a perfectly
// committable name, so a concurrent writer's blanket commit can sweep it into
// HEAD during the repair. Dropping it locally would then leave a permanent
// delete delta — the same class of tracked residue this whole fix exists to
// remove — so the deletion is committed, scoped to that table.
func dropIgnoredCursorScratch(ctx context.Context, db DBConn) error {
	//nolint:gosec // G201: the table name is a constant.
	if _, err := db.ExecContext(ctx, "DROP TABLE IF EXISTS "+ignoredCursorUntrackTempTable); err != nil {
		return fmt.Errorf("dropping %s: %w", ignoredCursorUntrackTempTable, err)
	}

	// Publish this session's work before asking Dolt what the working set
	// looks like, for exactly the reason commitIgnoredCursorUntrack does it:
	// on the transaction-pinned server path the CREATE/INSERT/DROP above sit
	// in an unpublished transaction, and the staging procedure would see the
	// pre-drop scratch still matching HEAD, stage an empty diff, and
	// --skip-empty would commit nothing — leaving the tracked residue to ride
	// some later unscoped auto-commit instead.
	if _, err := db.ExecContext(ctx, "COMMIT"); err != nil {
		return fmt.Errorf("publishing the %s drop: %w", ignoredCursorUntrackTempTable, err)
	}

	tracked, err := tableTrackedAtHead(ctx, db, "", ignoredCursorUntrackTempTable)
	if err != nil || !tracked {
		return err
	}
	// The resume path reaches here without any unstage having run in this
	// process, so scope the commit the same way its sibling does or unrelated
	// staged tables ride into HEAD under a "drop stray scratch table" message.
	if err := unstageBeforeIgnoredCursorUntrack(ctx, db); err != nil {
		return fmt.Errorf("unstaging before dropping %s: %w", ignoredCursorUntrackTempTable, err)
	}
	return commitScopedTableChange(ctx, db, ignoredCursorUntrackTempTable, ignoredCursorTempSweepCommitMessage)
}

// ignoredCursorCopyColumns is the column list to move out of source, which is
// cursorTableColumns narrowed to what that table actually has. Reading the
// shape instead of assuming it is what lets one code path serve both a
// pre-#4259 lineage (no content_hash) and a scratch table written by an older
// binary — and what stops the next column added to bootstrapSQL from being
// silently dropped on every database this repairs.
func ignoredCursorCopyColumns(ctx context.Context, db DBConn, source string) (string, error) {
	present := make([]string, 0, len(cursorTableColumns))
	for _, column := range cursorTableColumns {
		has, err := schemaColumnExists(ctx, db, source, column)
		if err != nil {
			return "", fmt.Errorf("reading %s.%s: %w", source, column, err)
		}
		if has {
			present = append(present, column)
		}
	}
	if len(present) == 0 {
		return "", fmt.Errorf("%s carries none of the cursor columns %v", source, cursorTableColumns)
	}
	return strings.Join(present, ", "), nil
}
