package main

import (
	"bytes"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dolthub/dolt/go/libraries/doltcore/servercfg"
	"github.com/dolthub/dolt/go/libraries/utils/filesys"
	"gopkg.in/yaml.v3"

	"github.com/steveyegge/beads/internal/config"
	"github.com/steveyegge/beads/internal/configfile"
	"github.com/steveyegge/beads/internal/doltserver"
	"github.com/steveyegge/beads/internal/storage/dbproxy/proxy"
)

const managedListenerHostRemediation = "set listener.host to 127.0.0.1 (or another 127.0.0.0/8 / ::1 " +
	"loopback address); for non-local topology use " +
	"--proxied-server-external-host with --proxied-server-external-port, " +
	"--proxied-server-external-socket-path, or switch to non-proxied server mode"

const managedProxiedServerConfigMarker = "# Generated by Beads on first run - safe to delete (will be regenerated). " +
	"Never rewritten afterward; hand edits are preserved. See gastownhall/beads#4986.\n"

func isManagedProxiedServerConfig(body []byte) bool {
	return bytes.HasPrefix(body, []byte(managedProxiedServerConfigMarker))
}

const (
	proxiedServerConfigName = "config.yaml"
	proxiedServerLogName    = "server.log"
)

func proxiedServerRoot(beadsDir string) string {
	return doltserver.ResolveDoltDir(beadsDir)
}

func proxiedServerConfigPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerConfigName)
}

func proxiedServerLogPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerLogName)
}

func envOrAbsJoin(envName, beadsDir string) string {
	p := os.Getenv(envName)
	if p == "" {
		return ""
	}
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(beadsDir, p)
}

// resolveProxiedServerRootPath delegates to the exported implementation in
// internal/doltserver so the workspace-gate resolver and the proxy plumbing
// share one root derivation (env → client-info sidecar → default data dir)
// and cannot drift. Note the shared implementation resolves the default via
// the side-effect-free DoltDirPath — same path as proxiedServerRoot, but it
// never mkdirs the shared-server tree just to answer "where is the root".
func resolveProxiedServerRootPath(beadsDir string) (string, error) {
	return doltserver.ResolveProxiedServerRootPath(beadsDir)
}

func resolveProxiedServerConfigPath(beadsDir string) (path string, isCustom bool, err error) {
	if p := envOrAbsJoin("BEADS_PROXIED_SERVER_CONFIG", beadsDir); p != "" {
		return p, true, nil
	}
	info, err := configfile.LoadProxiedServerClientInfo(beadsDir)
	if err != nil {
		return "", false, err
	}
	if p := info.ResolvedConfigPath(beadsDir); p != "" {
		return p, true, nil
	}
	root, err := resolveProxiedServerRootPath(beadsDir)
	if err != nil {
		return "", false, err
	}
	return filepath.Join(root, proxiedServerConfigName), false, nil
}

func resolveProxiedServerLogPath(beadsDir string) (path string, isCustom bool, err error) {
	if p := envOrAbsJoin("BEADS_PROXIED_SERVER_LOG", beadsDir); p != "" {
		return p, true, nil
	}
	info, err := configfile.LoadProxiedServerClientInfo(beadsDir)
	if err != nil {
		return "", false, err
	}
	if p := info.ResolvedLogPath(beadsDir); p != "" {
		return p, true, nil
	}
	root, err := resolveProxiedServerRootPath(beadsDir)
	if err != nil {
		return "", false, err
	}
	return filepath.Join(root, proxiedServerLogName), false, nil
}

func ensureProxiedServerConfig(beadsDir string) (string, error) {
	path, err := resolveOrCreateProxiedServerConfig(beadsDir)
	if err != nil {
		return "", err
	}
	if err := validateProxiedServerConfig(path); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: %w", err)
	}
	return path, nil
}

func resolveOrCreateProxiedServerConfig(beadsDir string) (string, error) {
	path, isCustom, err := resolveProxiedServerConfigPath(beadsDir)
	if err != nil {
		return "", err
	}

	if isCustom {
		info, err := os.Stat(path)
		if err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: %w", path, err)
		}
		if !info.Mode().IsRegular() {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: not a regular file", path)
		}
		return path, nil
	}

	root := filepath.Dir(path)
	if err := os.MkdirAll(root, config.BeadsDirPerm); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: mkdir %s: %w", root, err)
	}

	switch _, err := os.Stat(path); {
	case err == nil:
		return path, nil
	case !os.IsNotExist(err):
		return "", fmt.Errorf("ensureProxiedServerConfig: stat %s: %w", path, err)
	}

	port, err := proxy.PickFreePort()
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: pick free port: %w", err)
	}

	body, err := renderProxiedServerConfig(port)
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: render YAML: %w", err)
	}
	if err := atomicWriteFile(resolveConfigWriteTarget(path), body); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: write %s: %w", path, err)
	}
	return path, nil
}

// resolveConfigWriteTarget resolves path to its physical location before
// an atomic rewrite. os.Rename's destination argument does not follow
// symlinks — it unlinks and replaces whatever is AT that path, symlink or
// not — so writing straight to a symlinked config.yaml would silently
// replace the symlink itself with a regular file instead of updating the
// file it points at. Falls back to path unresolved when it does not exist
// yet (filepath.EvalSymlinks errors on a missing path), which covers both
// the ordinary "no config.yaml yet" case and a dangling symlink.
func resolveConfigWriteTarget(path string) string {
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil {
		return path
	}
	return resolved
}

// Validators below emit source-neutral errors. Callers wrap with whichever
// label is meaningful at their site: CLI callers prepend the flag name
// (e.g. "--proxied-server-config-path"); runtime callers (uow factory, etc.)
// prepend whatever label fits — the path may have come from env var or
// the proxied_server_client_info.json sidecar, not necessarily a flag.

func validateProxiedServerConfig(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s: not a regular file", path)
	}
	cfg, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path)
	if err != nil {
		return fmt.Errorf("%s: parse: %w", path, err)
	}
	if err := validateManagedServerConfigPolicy(cfg); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

// validateManagedServerConfigPolicy enforces the trust boundary for the Dolt
// child that Beads launches with root and an empty password: every listener
// the config can open must stay loopback-only, so the whole config is in
// scope, not just listener.host. External proxied topology never calls this
// validator because it launches no managed child.
func validateManagedServerConfigPolicy(cfg servercfg.ServerConfig) error {
	// listener.host policy: an explicit numeric loopback IP, nothing else.
	// An omitted host is rejected rather than trusted: servercfg resolves it
	// to DefaultHost ("localhost"), and CheckForUnixSocket treats a
	// "localhost" host as license to also open the shared-namespace default
	// unix socket — strictly worse than the explicit hostname it looks like.
	if yc, ok := cfg.(*servercfg.YAMLConfig); ok && yc.ListenerConfig.HostStr == nil {
		return fmt.Errorf(
			"managed proxied-server listener.host is omitted (Dolt would default to %q, "+
				"which can also open the default unix socket) and must be a numeric loopback IP literal: %s",
			servercfg.DefaultHost, managedListenerHostRemediation,
		)
	}
	host := cfg.Host()
	ip := net.ParseIP(host)
	if ip == nil || !ip.IsLoopback() {
		return fmt.Errorf(
			"managed proxied-server listener.host %q must be a numeric loopback IP literal: %s",
			host, managedListenerHostRemediation,
		)
	}
	// A unix socket bypasses the loopback TCP trust boundary entirely
	// (shared filesystem namespace). Socket() maps an explicitly empty
	// listener.socket to Dolt's default socket path, so it is rejected too.
	if socket := cfg.Socket(); socket != "" {
		return fmt.Errorf(
			"managed proxied-server config sets listener.socket %q, which bypasses the loopback trust boundary: "+
				"remove listener.socket; %s",
			socket, managedListenerHostRemediation,
		)
	}
	// remotesapi.port opens an HTTP+gRPC listener on all interfaces; there
	// is no host knob for it, so its presence alone breaks the boundary.
	if port := cfg.RemotesapiPort(); port != nil {
		return fmt.Errorf(
			"managed proxied-server config sets remotesapi.port %d, which listens on all interfaces: "+
				"remove the remotesapi block; %s",
			*port, managedListenerHostRemediation,
		)
	}
	// cluster.remotesapi.port likewise listens on all interfaces.
	if cfg.ClusterConfig() != nil {
		return fmt.Errorf(
			"managed proxied-server config sets a cluster block, whose remotesapi listens on all interfaces: "+
				"remove the cluster block; %s",
			managedListenerHostRemediation,
		)
	}
	return nil
}

// validateManagedProxiedServerConfigAtInit validates the effective existing
// managed-local config before init performs filesystem mutations. A missing
// Beads-default path is valid because init/runtime will generate the
// loopback-only config. Missing custom paths remain hard errors.
//
// explicitRootPath is the --proxied-server-root-path flag value: at this
// point the sidecar is not persisted yet, so resolveProxiedServerConfigPath
// cannot see the flag and it must be applied here. An explicit
// --proxied-server-config-path needs no handling here — init.go already
// validated it at flag-parse time, and when no config env override is set it
// IS the effective config, so there is nothing further to check.
func validateManagedProxiedServerConfigAtInit(beadsDir, explicitPath, explicitRootPath string) error {
	if explicitPath != "" && os.Getenv("BEADS_PROXIED_SERVER_CONFIG") == "" {
		return nil
	}
	path, isCustom, err := resolveProxiedServerConfigPath(beadsDir)
	if err != nil {
		return err
	}
	if !isCustom && explicitRootPath != "" && os.Getenv("BEADS_PROXIED_SERVER_ROOT_PATH") == "" {
		path = filepath.Join(explicitRootPath, proxiedServerConfigName)
	}
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) && !isCustom {
			return nil
		}
		return fmt.Errorf("%s: %w", path, err)
	}
	return validateProxiedServerConfig(path)
}

func validateProxiedServerRootPath(path string) error {
	switch info, err := os.Stat(path); {
	case err == nil:
		if !info.IsDir() {
			return fmt.Errorf("%s: not a directory", path)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

func validateProxiedServerLogPath(path string) error {
	parent := filepath.Dir(path)
	parentInfo, err := os.Stat(parent)
	if err != nil {
		return fmt.Errorf("%s: parent directory: %w", path, err)
	}
	if !parentInfo.IsDir() {
		return fmt.Errorf("%s: parent %s is not a directory", path, parent)
	}
	switch info, err := os.Stat(path); {
	case err == nil:
		if !info.Mode().IsRegular() {
			return fmt.Errorf("%s: not a regular file", path)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

func renderProxiedServerConfig(port int) ([]byte, error) {
	host := proxiedServerListenerHost
	logLevel := string(servercfg.LogLevel_Info)
	yc := &servercfg.YAMLConfig{
		LogLevelStr: &logLevel,
		ListenerConfig: servercfg.ListenerYAMLConfig{
			HostStr:    &host,
			PortNumber: &port,
		},
	}
	archiveLevel := 0
	yc.BehaviorConfig.AutoGCBehavior = &servercfg.AutoGCBehaviorYAMLConfig{
		ArchiveLevel_: &archiveLevel,
	}
	body, err := yaml.Marshal(yc)
	if err != nil {
		return nil, err
	}
	return append([]byte(managedProxiedServerConfigMarker), body...), nil
}

const proxiedServerListenerHost = "127.0.0.1"

// TODO: this needs to return a dolt server uow provider as the global
// uow provider used by all commands

//	func newProxiedServerStore(ctx context.Context, cfg *dolt.Config) (storage.DoltStorage, error) {
//		if cfg == nil {
//			return nil, fmt.Errorf("newProxiedServerStore: cfg is nil")
//		}
//		if cfg.BeadsDir == "" {
//			return nil, fmt.Errorf("newProxiedServerStore: cfg.BeadsDir must be set")
//		}
//		if cfg.Database == "" {
//			return nil, fmt.Errorf("newProxiedServerStore: cfg.Database must be set")
//		}
//
//		doltBin, err := exec.LookPath("dolt")
//		if err != nil {
//			return nil, fmt.Errorf("newProxiedServerStore: dolt is not installed (not found in PATH); install from https://docs.dolthub.com/introduction/installation: %w", err)
//		}
//
//		persisted, _ := configfile.Load(cfg.BeadsDir)
//
//		rootPath, isCustomRoot := resolveProxiedServerRootPath(cfg.BeadsDir, persisted)
//		if isCustomRoot {
//			if err := validateProxiedServerRootPath(rootPath); err != nil {
//				return nil, err
//			}
//		}
//
//		configPath, err := ensureProxiedServerConfig(cfg.BeadsDir, persisted)
//		if err != nil {
//			return nil, err
//		}
//
//		logPath, isCustomLog := resolveProxiedServerLogPath(cfg.BeadsDir, persisted)
//		if isCustomLog {
//			if err := validateProxiedServerLogPath(logPath); err != nil {
//				return nil, err
//			}
//		}
//
//		name, email := cfg.CommitterName, cfg.CommitterEmail
//		if name == "" || email == "" {
//			fallbackName, fallbackEmail := proxiedServerCommitter()
//			if name == "" {
//				name = fallbackName
//			}
//			if email == "" {
//				email = fallbackEmail
//			}
//		}
//
//		return doltserver.NewDoltServerStore(
//			ctx,
//			rootPath,
//			cfg.BeadsDir,
//			cfg.Database,
//			name, email,
//			logPath,
//			configPath,
//			proxy.BackendLocalServer,
//			false, // autoSyncToOriginRemote — wired in a future iteration
//			"root",
//			"", // rootPassword: proxy is loopback-only, no auth
//			doltBin,
//		)
//	}
func proxiedServerCommitter() (string, string) {
	name, email := "beads", "beads@localhost"
	if out, err := exec.Command("git", "config", "user.name").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			name = v
		}
	}
	if out, err := exec.Command("git", "config", "user.email").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			email = v
		}
	}
	return name, email
}
