package main

import (
	"reflect"

	"github.com/invopop/jsonschema"
	"github.com/spf13/cobra"

	"github.com/steveyegge/beads/internal/types"
)

// schemaCmd emits the JSON Schema for bd's canonical --json / export output
// record types.
//
// The schema is generated by reflection from the same internal/types structs
// that bd serializes, so by construction it cannot drift from the actual output
// the way a hand-maintained doc (docs/JSON_SCHEMA.md) or a downstream consumer
// model (e.g. beads-mcp's Pydantic models) can. The named string enums (status,
// issue_type, dependency type) are enriched with their allowed values, sourced
// from the same internal/types lists that validation uses. The emitted
// schema_version matches JSONSchemaVersion and bumps with it.
//
// Consumers can codegen typed models from this output (datamodel-code-generator
// for Python/Pydantic, quicktype, etc.) instead of hand-mirroring the format.
var schemaCmd = &cobra.Command{
	Use:   "schema",
	Short: "Print the JSON Schema for bd's --json / export output",
	// The schema is reflected from static Go types; no store is needed, and
	// opening one would make this fail outside a workspace (or on a CGO-less
	// build) for no reason.
	Annotations: map[string]string{skipStoreAnnotation: "1"},
	Long: `Print the JSON Schema for bd's canonical output record types.

The schema is reflected from the same Go structs bd serializes, so it stays in
lockstep with the actual --json / export output. Use it to generate typed
consumer models (datamodel-code-generator, quicktype, ...) rather than
hand-maintaining them.

  bd schema | jq '.types.issue'        # the issue record schema
  bd schema | jq '.types.dependency'   # the dependency record schema`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Raw: the document carries its own schema_version; do not double-wrap
		// it in the --json envelope.
		return outputJSONRaw(schemaDocument())
	},
}

// schemaDocument builds the JSON Schema document for bd's canonical output
// record types. Split out from the command so it can be unit-tested without a
// workspace or database.
func schemaDocument() map[string]interface{} {
	reflector := &jsonschema.Reflector{
		// Inline referenced types so each record schema is self-contained and
		// directly consumable by codegen tools.
		DoNotReference: true,
		// Enrich bd's named string enums with their allowed values.
		Mapper: enumMapper,
	}
	return map[string]interface{}{
		"schema_version": JSONSchemaVersion,
		"types": map[string]*jsonschema.Schema{
			"issue":      reflector.Reflect(&types.Issue{}),
			"dependency": reflector.Reflect(&types.Dependency{}),
		},
	}
}

// enumMapper maps bd's named string enum types to a string schema enumerating
// their allowed values, so the published schema constrains them instead of
// emitting a bare "string". Values come from the canonical internal/types lists
// that validation also consults, so the schema cannot drift from them.
func enumMapper(t reflect.Type) *jsonschema.Schema {
	switch t {
	case reflect.TypeOf(types.Status("")):
		return stringEnum(types.AllStatuses)
	case reflect.TypeOf(types.IssueType("")):
		return stringEnum(types.AllIssueTypes)
	case reflect.TypeOf(types.DependencyType("")):
		return stringEnum(types.AllDependencyTypes)
	}
	return nil
}

func stringEnum[T ~string](values []T) *jsonschema.Schema {
	enum := make([]any, len(values))
	for i, v := range values {
		enum[i] = string(v)
	}
	return &jsonschema.Schema{Type: "string", Enum: enum}
}

func init() {
	rootCmd.AddCommand(schemaCmd)
}
