package main

import (
	"fmt"
	"strings"
)

// Legacy-emitter support. Release tags before the docsmint pipeline (bd
// v1.1.0 and earlier) emit Docusaurus-style pages to
// website/docs/cli-reference/ instead of the generic staging tree at
// build/cli-docs/. While docs/cli-docs.pin points at such a release, docsmint
// converts those pages to the generic form here and then runs its normal
// Mintlify transform. This shim is removable once the pin reaches a release
// whose emitter writes build/cli-docs/ natively.

const autoGeneratedComment = "<!-- AUTO-GENERATED: do not edit manually -->"

// convertLegacyPage converts one Docusaurus-form command page (frontmatter
// with id/title/slug/sidebar_position, an H2 command heading, subcommands one
// heading level deeper) into the generic staging form the modern emitter
// writes (title/description frontmatter, no top command heading, subcommands
// at H2).
func convertLegacyPage(content string) (string, error) {
	body, err := stripFrontmatter(content)
	if err != nil {
		return "", err
	}
	lines := trimLeadingBlank(strings.Split(body, "\n"))
	if len(lines) == 0 || lines[0] != autoGeneratedComment {
		return "", fmt.Errorf("missing %q marker", autoGeneratedComment)
	}
	if len(lines) < 2 || !strings.HasPrefix(lines[1], "Generated from") {
		return "", fmt.Errorf("missing Generated-from line")
	}
	genLine := strings.TrimRight(lines[1], " ")
	if !strings.HasSuffix(genLine, ".") {
		genLine += "."
	}

	rest := trimLeadingBlank(lines[2:])
	if len(rest) == 0 || !strings.HasPrefix(rest[0], "## bd ") {
		return "", fmt.Errorf("expected '## bd <command>' heading")
	}
	title := strings.TrimPrefix(rest[0], "## ")

	rest = trimLeadingBlank(rest[1:])
	// The Cobra Short line doubles as the page description and stays in the
	// body, exactly as the modern emitter leaves it.
	short := ""
	if len(rest) > 0 {
		first := strings.TrimSpace(rest[0])
		if first != "" && !strings.HasPrefix(first, "#") && !strings.HasPrefix(first, "```") {
			short = first
		}
	}
	rest = promoteHeadings(rest)

	var b strings.Builder
	b.WriteString("---\n")
	// #nosec G705: not a web-output sink — this developer tool emits repo
	// Markdown frontmatter; title/description are %q-quoted strings taken
	// from the repo's own generated staging pages.
	fmt.Fprintf(&b, "title: %q\ndescription: %q\n", title, short)
	b.WriteString("---\n\n")
	b.WriteString(autoGeneratedComment + "\n\n")
	b.WriteString(genLine + "\n\n")
	b.WriteString(strings.Join(rest, "\n"))
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// convertLegacyIndex converts the Docusaurus-form index page (H1 title,
// versioned intro line) into the generic staging index form.
func convertLegacyIndex(content string) (string, error) {
	body, err := stripFrontmatter(content)
	if err != nil {
		return "", err
	}
	lines := trimLeadingBlank(strings.Split(body, "\n"))
	if len(lines) == 0 || lines[0] != "# CLI Reference" {
		return "", fmt.Errorf("expected '# CLI Reference' heading")
	}
	lines = trimLeadingBlank(lines[1:])
	if len(lines) == 0 || lines[0] != autoGeneratedComment {
		return "", fmt.Errorf("missing %q marker", autoGeneratedComment)
	}
	if len(lines) < 2 || !strings.HasPrefix(lines[1], "Reference for bd") {
		return "", fmt.Errorf("missing 'Reference for bd' line")
	}
	rest := trimLeadingBlank(lines[2:])

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: CLI Reference\n")
	b.WriteString("description: Generated reference for every bd command\n")
	b.WriteString("---\n\n")
	b.WriteString(autoGeneratedComment + "\n\n")
	b.WriteString("Generated from `bd help --docs-root`.\n\n")
	b.WriteString(strings.Join(rest, "\n"))
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// stripFrontmatter removes the leading YAML frontmatter block and returns the
// remaining body.
func stripFrontmatter(content string) (string, error) {
	lines := strings.Split(content, "\n")
	if len(lines) == 0 || lines[0] != "---" {
		return "", fmt.Errorf("missing frontmatter")
	}
	for i := 1; i < len(lines); i++ {
		if lines[i] == "---" {
			return strings.Join(lines[i+1:], "\n"), nil
		}
	}
	return "", fmt.Errorf("unterminated frontmatter")
}

// promoteHeadings lifts every H3+ heading one level (### -> ##) outside code
// fences: the legacy layout nests subcommands under the page's own command
// heading, which the generic form does not have.
func promoteHeadings(lines []string) []string {
	out := make([]string, len(lines))
	inFence := false
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "```") {
			inFence = !inFence
			out[i] = line
			continue
		}
		if !inFence && strings.HasPrefix(line, "###") {
			line = line[1:]
		}
		out[i] = line
	}
	return out
}

func trimLeadingBlank(lines []string) []string {
	for len(lines) > 0 && strings.TrimSpace(lines[0]) == "" {
		lines = lines[1:]
	}
	return lines
}
