// Package batchfixtures builds issueops.ApplyBatchRequest values shaped like
// the plans measured for the large-batch-apply work: the mol-normalized
// issue/PR work plan (and its 2x variant) and a "classic" hand-authored
// plan. It does no I/O — every fixture here is pure data construction — so a
// benchmark or test in any backend package can import it without risking an
// import cycle with internal/storage/issueops (which the backend packages
// already import for ApplyBatchInTx itself).
package batchfixtures

import (
	"encoding/json"
	"fmt"

	"github.com/steveyegge/beads/internal/types"
	"github.com/steveyegge/beads/issueops"
)

// createKey names the Nth created work item across every shape here, so a
// caller inspecting a failure can tell which fixture minted a given key.
func createKey(prefix string, n int) string {
	return fmt.Sprintf("%s-w%d", prefix, n)
}

// molCounts is the sub-item composition mol-normalized-issue-pr-work-v1
// measures at 1x: 102 creates, 136 blocks edges, 102 tracks-to-root edges,
// 16 assign updates == 356 items total.
type molCounts struct {
	creates     int
	blocksEdges int
	tracksEdges int
	assignItems int
}

var mol1x = molCounts{creates: 102, blocksEdges: 136, tracksEdges: 102, assignItems: 16}

// mol2x is the design's explicit 2x test point (712 items): every
// sub-category of mol1x doubled, rather than a differently-shaped plan. That
// is a modeling decision the design doc leaves open ("...2x the above
// shape") — doubling each sub-count is the literal reading and keeps the
// edge/create ratio identical between the two measured shapes, which is what
// makes them comparable points on the same curve.
var mol2x = molCounts{creates: 204, blocksEdges: 272, tracksEdges: 204, assignItems: 32}

// molCap is mol1x's sub-category ratio scaled up to land exactly on
// issueops.MaxApplyBatchItems (1000): the top of the large-apply envelope the
// server's --large-apply-ceiling default (5 minutes) is sized against, so a
// wall-clock measurement at this shape is a measurement AT the cap, not an
// extrapolation from a smaller one.
var molCap = molCounts{creates: 286, blocksEdges: 382, tracksEdges: 286, assignItems: 46}

// buildMolShape builds a mol-normalized-issue-pr-work-v1-shaped request: a
// flat batch of work-item creates (each carrying metadata), a blocks chain
// wiring them together, every created item tracking back to an
// already-existing root issue, and a tail of assignee updates on a subset of
// the created items.
//
// rootID must already exist in the target store — it is NOT created by this
// request, matching the shape's own description ("...tracks to the root"):
// the root is the pre-existing issue or PR the batch's new work tracks
// against, not itself a member of the batch.
func buildMolShape(actor, prefix string, c molCounts, rootID string) issueops.ApplyBatchRequest {
	items := make([]issueops.ApplyItem, 0, c.creates+c.blocksEdges+c.tracksEdges+c.assignItems)

	// Creates, each carrying a small metadata blob — "creates with metadata"
	// per the design's shape description.
	for i := 1; i <= c.creates; i++ {
		key := createKey(prefix, i)
		meta, err := json.Marshal(map[string]any{
			"source": "mol-normalized-issue-pr-work-v1",
			"seq":    i,
		})
		if err != nil {
			panic(fmt.Sprintf("batchfixtures: marshal create metadata: %v", err))
		}
		items = append(items, issueops.ApplyItem{
			Kind: issueops.ItemCreate,
			Create: &issueops.CreateItem{
				Key: key,
				Issue: &types.Issue{
					Title:     fmt.Sprintf("%s work item %d", prefix, i),
					Status:    types.StatusOpen,
					Priority:  2,
					IssueType: types.TypeTask,
					Metadata:  meta,
				},
			},
		})
	}

	// Blocks edges: a deterministic, duplicate-free set of (source, source+skip)
	// pairs over the created keys, generated by widening the skip distance
	// once every (creates-1) edges are exhausted at the current skip. Every
	// pair names two ALREADY-DECLARED create keys (both appear earlier in
	// Items), which is what a backward-only Ref requires.
	edgesAdded := 0
	for skip := 1; edgesAdded < c.blocksEdges; skip++ {
		for i := 1; i+skip <= c.creates && edgesAdded < c.blocksEdges; i++ {
			items = append(items, issueops.ApplyItem{
				Kind: issueops.ItemDepAdd,
				DepAdd: &issueops.DepAddItem{
					Source: issueops.Ref{Key: createKey(prefix, i)},
					Target: issueops.Ref{Key: createKey(prefix, i+skip)},
					Type:   issueops.DepBlocks,
				},
			})
			edgesAdded++
		}
	}

	// Tracks-to-root edges: every created item tracks the pre-existing root.
	for i := 1; i <= c.tracksEdges; i++ {
		srcN := ((i - 1) % c.creates) + 1
		items = append(items, issueops.ApplyItem{
			Kind: issueops.ItemDepAdd,
			DepAdd: &issueops.DepAddItem{
				Source: issueops.Ref{Key: createKey(prefix, srcN)},
				Target: issueops.Ref{ID: rootID},
				Type:   issueops.DepTracks,
			},
		})
	}

	// Assign updates on a subset of the created items.
	for i := 1; i <= c.assignItems; i++ {
		assignee := fmt.Sprintf("agent-%d", i)
		items = append(items, issueops.ApplyItem{
			Kind: issueops.ItemUpdate,
			Update: &issueops.UpdateItem{
				Target: issueops.Ref{Key: createKey(prefix, i)},
				Patch: issueops.IssuePatch{
					Assignee: issueops.Field[string]{Set: true, Value: assignee},
				},
			},
		})
	}

	return issueops.ApplyBatchRequest{
		Actor:      actor,
		Items:      items,
		Provenance: fmt.Sprintf("batchfixtures: mol-normalized-issue-pr-work-v1 (%d items)", len(items)),
	}
}

// Shape356 builds the design's primary measured shape: 102 creates with
// metadata, 238 edges (136 blocks + 102 tracks-to-root) and 16 assign
// updates, for 356 items total. rootID must already exist in the target
// store.
func Shape356(actor, rootID string) issueops.ApplyBatchRequest {
	return buildMolShape(actor, "mol1x", mol1x, rootID)
}

// Shape712 builds the design's 2x test point: every Shape356 sub-category
// doubled (204 creates, 476 edges [272 blocks + 204 tracks], 32 assign
// updates), for 712 items total. rootID must already exist in the target
// store.
func Shape712(actor, rootID string) issueops.ApplyBatchRequest {
	return buildMolShape(actor, "mol2x", mol2x, rootID)
}

// Shape1000 builds a plan at exactly issueops.MaxApplyBatchItems (286
// creates, 668 edges [382 blocks + 286 tracks], 46 assign updates), for 1000
// items total: the top of the large-apply envelope, for measuring wall-clock
// time at the cap rather than only at the design doc's 356/712 sample
// points. rootID must already exist in the target store.
func Shape1000(actor, rootID string) issueops.ApplyBatchRequest {
	return buildMolShape(actor, "molcap", molCap, rootID)
}

// ShapeClassic40 builds a 40-item "classic" (non-mol) plan: 10 creates, 20
// edges (12 blocks + 8 parent-child) and 10 assign updates.
//
// The design doc does not pin exact sub-counts for the classic shape — it
// only describes MC's classic formulas qualitatively as "at most 9 source
// steps, so roughly 40 items or fewer". This composition is this
// implementation's modeling decision for a comparison point below the mol
// shape's edge-heavy ratio: parent-child plus blocks rather than
// tracks-to-root, because a classic (non-convoy) plan has no single root
// every item reports to.
func ShapeClassic40(actor string) issueops.ApplyBatchRequest {
	const (
		creates    = 10
		blocks     = 12
		parentKids = 8
		assigns    = 10
	)
	prefix := "classic"
	items := make([]issueops.ApplyItem, 0, creates+blocks+parentKids+assigns)

	for i := 1; i <= creates; i++ {
		items = append(items, issueops.ApplyItem{
			Kind: issueops.ItemCreate,
			Create: &issueops.CreateItem{
				Key: createKey(prefix, i),
				Issue: &types.Issue{
					Title:     fmt.Sprintf("%s item %d", prefix, i),
					Status:    types.StatusOpen,
					Priority:  2,
					IssueType: types.TypeTask,
				},
			},
		})
	}

	edgesAdded := 0
	for skip := 1; edgesAdded < blocks; skip++ {
		for i := 1; i+skip <= creates && edgesAdded < blocks; i++ {
			items = append(items, issueops.ApplyItem{
				Kind: issueops.ItemDepAdd,
				DepAdd: &issueops.DepAddItem{
					Source: issueops.Ref{Key: createKey(prefix, i)},
					Target: issueops.Ref{Key: createKey(prefix, i+skip)},
					Type:   issueops.DepBlocks,
				},
			})
			edgesAdded++
		}
	}

	// Parent-child edges: item 1 is the parent of item 4 through creates,
	// cycling within that range if parentKids exceeds it. Items 2 and 3 are
	// skipped deliberately — the blocks loop above always wires (1,2) and
	// (1,3) first (skip=1's first pair and skip=2's first pair), and a pair
	// may carry only one dependency TYPE: a parent-child edge on the same
	// pair a blocks edge already claimed is refused as a type conflict, not
	// silently added as a second edge.
	for i := 1; i <= parentKids; i++ {
		childN := 4 + ((i - 1) % (creates - 3)) // 4..creates, cycling
		items = append(items, issueops.ApplyItem{
			Kind: issueops.ItemDepAdd,
			DepAdd: &issueops.DepAddItem{
				Source: issueops.Ref{Key: createKey(prefix, 1)},
				Target: issueops.Ref{Key: createKey(prefix, childN)},
				Type:   issueops.DepParentChild,
			},
		})
	}

	for i := 1; i <= assigns; i++ {
		assignee := fmt.Sprintf("agent-%d", i)
		items = append(items, issueops.ApplyItem{
			Kind: issueops.ItemUpdate,
			Update: &issueops.UpdateItem{
				Target: issueops.Ref{Key: createKey(prefix, i)},
				Patch: issueops.IssuePatch{
					Assignee: issueops.Field[string]{Set: true, Value: assignee},
				},
			},
		})
	}

	return issueops.ApplyBatchRequest{
		Actor:      actor,
		Items:      items,
		Provenance: fmt.Sprintf("batchfixtures: classic (%d items)", len(items)),
	}
}
