package uow

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/steveyegge/beads/internal/storage/domain"
)

// The structural parity guard.
//
// The first attempt at unit-of-work hooks overrode a HAND-PICKED list of use
// case methods, which is a coverage claim that decays silently: the list is
// right the day it is written and wrong the first time someone adds a verb.
// This file replaces the claim with a PARTITION. Every method of every surface
// the notifying wrapper stands in front of is either recorded or listed below
// with the reason it records nothing, and the tests fail on anything that is
// neither, on anything that is both, and on an exemption that no longer names a
// real method.
//
// Adding a mutating verb to a use case therefore breaks this test until someone
// decides what hook it fires. That decision is the point.
//
// WHY REFLECTION AND A WRITTEN PARTITION rather than deriving "is this a
// mutator?" from the SQL each method reaches (the shape a journal completeness
// guard uses): the derivation needs a call graph, and a name-resolved one over
// domain + domain/db + issueops collapses — every repository body calls
// rows.Close(), which resolves to IssueSQLRepository.Close, so every read looks
// like a mutation. Dropping issueops from the scan loses the closes instead,
// which is the half that matters most here. A partition needs no classifier and
// cannot drift: the compiler supplies the method set, and reflection tells a
// DECLARED override from one promoted by the embedded interface.

// declaredOn reports whether typ declares name itself rather than inheriting it
// from an embedded field. The compiler reports a promoted method's
// implementation as living in "<autogenerated>" — the same discriminator
// internal/storage/role_accessor_decorator_test.go uses, and the only way to
// tell "wrapped" from "passed straight through" on a type that embeds the
// surface it decorates.
func declaredOn(typ reflect.Type, name string) (declared, exists bool) {
	method, ok := typ.MethodByName(name)
	if !ok {
		return false, false
	}
	file, _ := runtime.FuncForPC(method.Func.Pointer()).FileLine(method.Func.Pointer())
	return !strings.Contains(file, "<autogenerated>"), true
}

// assertPartition is the shared body of every guard below: recorded and
// exempted must together cover surface exactly, with no overlap and no
// exemption for a method that no longer exists.
func assertPartition(t *testing.T, what string, surface []string, recorder reflect.Type, exempt map[string]string) {
	t.Helper()
	present := make(map[string]bool, len(surface))
	for _, name := range surface {
		present[name] = true
		declared, exists := declaredOn(recorder, name)
		reason, exempted := exempt[name]
		switch {
		case exempted && declared:
			t.Errorf("%s.%s is both recorded and exempted (%q) — delete the exemption", what, name, reason)
		case exempted && strings.TrimSpace(reason) == "":
			t.Errorf("%s.%s is exempted with no reason", what, name)
		case exempted:
		case declared:
		case !exists:
			t.Errorf("%s.%s is not answered by %s at all: a caller asks for it with a type assertion, "+
				"which simply stops matching, so the wrapper loses the capability along with its hooks. "+
				"Declare it, or exempt it in this file with the reason it offers nothing", what, name, recorder)
		default:
			t.Errorf("%s.%s is inherited from the embedded surface, so it records nothing: add an "+
				"override that buffers the hook the DoltStorage chain fires for it "+
				"(internal/storage/hook_decorator.go), or exempt it in this file with the reason it fires none",
				what, name)
		}
	}
	for name := range exempt {
		if !present[name] {
			t.Errorf("%s.%s is exempted but no longer exists — delete the exemption", what, name)
		}
	}
}

func interfaceMethods(iface reflect.Type) []string {
	names := make([]string, 0, iface.NumMethod())
	for i := 0; i < iface.NumMethod(); i++ {
		names = append(names, iface.Method(i).Name)
	}
	sort.Strings(names)
	return names
}

// ── The unit of work's use cases ────────────────────────────────────

// TestNotifyingUOWWrapsEveryMutatingUseCase pins which use cases the notifying
// unit of work stands in front of. A use case added to the UnitOfWork interface
// lands here first, before any of its methods can be forgotten.
func TestNotifyingUOWWrapsEveryMutatingUseCase(t *testing.T) {
	assertPartition(t, "UnitOfWork", interfaceMethods(reflect.TypeOf((*UnitOfWork)(nil)).Elem()),
		reflect.TypeOf((*notifyingUOW)(nil)), map[string]string{
			"SwitchDatabase": "DDL against the connection, not a write to any bead",
			"ConfigUseCase": "workspace settings and metadata, not beads: the DoltStorage chain's " +
				"WorkspaceConfig role passes through undecorated for the same reason (hook_workspace_config.go)",
			"DoltRemoteUseCase": "Dolt remotes are repository plumbing; no bead changes and no event to name",
			"RawSQLUseCase": "the raw escape hatch executes statements this layer cannot read, so it " +
				"cannot say which bead changed; the DoltStorage chain fires nothing for raw access either",
		})
}

// TestRecordingIssueUseCaseCoversItsSurface and its three siblings are the
// method-level halves. The exemption reasons are the parity argument itself:
// each one says what the DoltStorage plumbing fires for the same operation,
// which is nothing.
func TestRecordingIssueUseCaseCoversItsSurface(t *testing.T) {
	reads := "reads state, changes none"
	deletes := "deletes fire no script hook on the DoltStorage plumbing either — the vocabulary " +
		"has no name for a deletion and the row is gone (hook_deleter.go, hookTrackingTransaction.DeleteIssue)"
	leases := "lease and claim bookkeeping the DoltStorage plumbing fires no hook for: " +
		"HookFiringStore overrides neither UnclaimIssue, UnclaimIssueIfAssignee, HeartbeatIssue nor " +
		"ReclaimExpiredLeases, so `bd unclaim` and `bd heartbeat` run no script on either plumbing"

	assertPartition(t, "IssueUseCase", interfaceMethods(reflect.TypeOf((*domain.IssueUseCase)(nil)).Elem()),
		reflect.TypeOf((*recordingIssueUC)(nil)), map[string]string{
			"AsOf":                         reads,
			"CountIssues":                  reads,
			"CountIssuesByGroup":           reads,
			"CountOpenChildren":            reads,
			"CountOpenWispChildren":        reads,
			"FindWispDependentsRecursive":  reads,
			"GetBlockedIssues":             reads,
			"GetDescendants":               reads,
			"GetEpicsEligibleForClosure":   reads,
			"GetIssue":                     reads,
			"GetIssuesByIDs":               reads,
			"GetNewlyUnblockedByClose":     reads,
			"GetNewlyUnblockedByCloseWisp": reads,
			"GetReadyWork":                 reads,
			"GetReadyWorkWithCounts":       reads,
			"GetStaleIssues":               reads,
			"GetStatistics":                reads,
			"GetWisp":                      reads,
			"GetWispsByIDs":                reads,
			"History":                      reads,
			"IterEvents":                   reads,
			"PreviewDelete":                reads,
			"PreviewDeleteWisp":            reads,
			"SearchIssueIDs":               reads,
			"SearchIssues":                 reads,
			"SearchIssuesWithCounts":       reads,
			"DeleteIssue":                  deletes,
			"DeleteIssues":                 deletes,
			"DeleteWisp":                   deletes,
			"DeleteWisps":                  deletes,
			"Unclaim":                      leases,
			"UnclaimIfAssignee":            leases,
			"Heartbeat":                    leases,
			"ReclaimExpiredLeases":         leases,
			"WakeExpiredDefers": "the deferred-work sweep is a clock crossing rather than a user's " +
				"mutation, and the DoltStorage plumbing fires nothing for it",
			"PromoteWisp": "moves a row between planes without changing the bead; the DoltStorage " +
				"plumbing has no promote hook either",
		})
}

func TestRecordingDependencyUseCaseCoversItsSurface(t *testing.T) {
	reads := "reads the graph, changes none"
	assertPartition(t, "DependencyUseCase", interfaceMethods(reflect.TypeOf((*domain.DependencyUseCase)(nil)).Elem()),
		reflect.TypeOf((*recordingDepUC)(nil)), map[string]string{
			"CountByIssueID":            reads,
			"CountByWispID":             reads,
			"CountsByIssueIDs":          reads,
			"CountsByWispIDs":           reads,
			"DetectCycleReport":         reads,
			"DetectCycles":              reads,
			"GetBlockingInfo":           reads,
			"GetDependencyTree":         reads,
			"GetForIssueIDs":            reads,
			"GetIssueDependencyRecords": reads,
			"GetWispDependencyRecords":  reads,
			"IsBlocked":                 reads,
			"IsWispBlocked":             reads,
			"IterWispWithIssueMetadata": reads,
			"IterWithIssueMetadata":     reads,
			"ListByIssueIDs":            reads,
			"ListByWispIDs":             reads,
			"ListWispWithIssueMetadata": reads,
			"ListWithIssueMetadata":     reads,
			"WalkDependencyTree":        reads,
		})
}

func TestRecordingLabelUseCaseCoversItsSurface(t *testing.T) {
	reads := "reads labels, changes none"
	assertPartition(t, "LabelUseCase", interfaceMethods(reflect.TypeOf((*domain.LabelUseCase)(nil)).Elem()),
		reflect.TypeOf((*recordingLabelUC)(nil)), map[string]string{
			"GetLabels":          reads,
			"GetLabelsForIssues": reads,
			"GetLabelsForWisps":  reads,
			"GetWispLabels":      reads,
		})
}

func TestRecordingCommentUseCaseCoversItsSurface(t *testing.T) {
	reads := "reads comments, changes none"
	assertPartition(t, "CommentUseCase", interfaceMethods(reflect.TypeOf((*domain.CommentUseCase)(nil)).Elem()),
		reflect.TypeOf((*recordingCommentUC)(nil)), map[string]string{
			"CountCommentsForIssue": reads,
			"CountCommentsForWisp":  reads,
			"GetCommentCounts":      reads,
			"GetCommentsForIssue":   reads,
			"GetCommentsForIssues":  reads,
			"GetCommentsForWisp":    reads,
			"GetCommentsForWisps":   reads,
			"GetWispCommentCounts":  reads,
			"IterCommentsForIssue":  reads,
			"IterCommentsForWisp":   reads,
		})
}

// ── The provider's capability surface ───────────────────────────────

// TestNotifyingProviderAnswersTheWholeProviderSurface enumerates what a
// provider offers by PARSING doltSQLProvider's methods out of this package,
// rather than listing them: doltSQLProvider is what every constructor in this
// package returns, so its method set is the surface a caller can reach through
// a UnitOfWorkProvider.
//
// A capability the wrapper does not answer is not a compile error — callers ask
// for these with a type assertion, which simply stops matching — so a role
// accessor added to the provider and forgotten here would silently lose both
// its hooks AND its feature in proxied mode. That is the failure this catches.
func TestNotifyingProviderAnswersTheWholeProviderSurface(t *testing.T) {
	surface := methodsDeclaredOnType(t, "doltSQLProvider")
	if len(surface) < 25 {
		t.Fatalf("parsed only %d methods off doltSQLProvider — the scan is broken, not the provider", len(surface))
	}
	assertPartition(t, "UnitOfWorkProvider", surface, reflect.TypeOf((*notifyingProvider)(nil)), map[string]string{
		"BeginTx": "TxProvider hands out a bare transaction with no unit of work around it, so " +
			"there is nothing to buffer and nothing to drain: the wrapper deliberately does not " +
			"offer it, and only this package's own NewUOW asks a provider for one",
		"initSchema": "unexported provider setup, not a capability any caller can reach",
	})
}

// TestNotifyingProviderBuildsRolesOnItself is the other half of the accessor
// story, and the one reflection cannot see: an accessor that IS declared but
// reads `return NewCommenter(p.inner)` compiles, keeps every type assertion
// working, and silently builds the role on the UNWRAPPED provider — so its
// units of work are plain ones and every hook stops firing. The bodies are
// one-liners, so requiring the receiver to be the constructor's argument is an
// exact check rather than a heuristic.
// It scans the WHOLE package, not notifying.go: this package's convention is a
// file per role, so the accessor most likely to be written next — and to be
// written as a delegation — is the one in the new role's own file.
func TestNotifyingProviderBuildsRolesOnItself(t *testing.T) {
	// The accessors are the provider methods that construct a role; the
	// non-role capabilities forward to the inner provider on purpose.
	forwarders := map[string]bool{
		"NewUOW":        true,
		"Close":         true,
		"RunNonTx":      true,
		"SetPoolLimits": true,
		"Unwrap":        true,
	}

	var checked int
	for _, fn := range funcsDeclaredOnType(t, "notifyingProvider") {
		if forwarders[fn.Name.Name] {
			continue
		}
		receiver := ""
		if len(fn.Recv.List[0].Names) > 0 {
			receiver = fn.Recv.List[0].Names[0].Name
		}
		if !passesReceiver(fn, receiver) {
			t.Errorf("notifyingProvider.%s does not build its role on the wrapper: the role's units "+
				"of work are then the inner provider's, and nothing it writes fires a hook", fn.Name.Name)
		}
		checked++
	}
	if checked < 25 {
		t.Fatalf("checked only %d role accessors — the scan is broken", checked)
	}
}

// TestUnitOfWorkBypassesAreAccountedFor is the third structural guard, and it
// closes the one hole the other two cannot see.
//
// The recorder sits at the USE-CASE seam, so it sees a write only if the write
// passed a use case. A caller that reaches the transaction directly — by
// peeling the decorator with unwrapUOW, or by asserting the concrete unit of
// work — writes rows no hook is fired for, and nothing about that is visible in
// a method set. Today there is exactly one such caller, and it is deliberate;
// the guard is here so that the SECOND one is a decision rather than an
// accident.
func TestUnitOfWorkBypassesAreAccountedFor(t *testing.T) {
	bypasses := map[string]string{
		"importStatementRunner": "the import role runs the shared batch-upsert engine on the " +
			"transaction's statement runner (importer.go), so its writes never pass a use case. " +
			"Import fires no hooks on the DoltStorage plumbing either — it runs the same engine " +
			"there — so this is parity, not a gap. A hook per imported issue would be new " +
			"behavior on both plumbings.",
	}

	found := map[string]bool{}
	for _, fn := range funcsInPackage(t) {
		if !reachesConcreteUOW(fn) {
			continue
		}
		name := fn.Name.Name
		found[name] = true
		reason, ok := bypasses[name]
		switch {
		case !ok:
			t.Errorf("%s reaches the unit of work beneath the recording layer, so whatever it "+
				"writes fires no hook. Route the write through a use case, or list it in this "+
				"test with the reason it fires none", name)
		case strings.TrimSpace(reason) == "":
			t.Errorf("%s is listed as a bypass with no reason", name)
		}
	}
	for name := range bypasses {
		if !found[name] {
			t.Errorf("%s is listed as a bypass but no longer reaches past the recording layer — "+
				"delete the entry", name)
		}
	}
}

// reachesConcreteUOW reports whether fn peels a unit of work down to the
// concrete type — by calling unwrapUOW, or by asserting baseUOW directly.
func reachesConcreteUOW(fn *ast.FuncDecl) bool {
	reaches := false
	ast.Inspect(fn, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.CallExpr:
			if ident, ok := node.Fun.(*ast.Ident); ok && ident.Name == "unwrapUOW" {
				reaches = true
			}
		case *ast.TypeAssertExpr:
			if receiverTypeName(node.Type) == "baseUOW" {
				reaches = true
			}
		}
		return true
	})
	return reaches
}

// funcsInPackage parses every non-test file in this package and returns all of
// its function and method declarations.
func funcsInPackage(t *testing.T) []*ast.FuncDecl {
	t.Helper()
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, ".", func(fi fs.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		t.Fatalf("parse package: %v", err)
	}
	var found []*ast.FuncDecl
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				if fn, ok := decl.(*ast.FuncDecl); ok {
					found = append(found, fn)
				}
			}
		}
	}
	return found
}

// passesReceiver reports whether fn hands the receiver itself to a call.
func passesReceiver(fn *ast.FuncDecl, receiver string) bool {
	found := false
	ast.Inspect(fn, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		for _, arg := range call.Args {
			if ident, ok := arg.(*ast.Ident); ok && ident.Name == receiver {
				found = true
			}
		}
		return true
	})
	return found
}

// methodsDeclaredOnType returns the names of the methods this package declares
// on the named receiver type.
func methodsDeclaredOnType(t *testing.T, typeName string) []string {
	t.Helper()
	var names []string
	for _, fn := range funcsDeclaredOnType(t, typeName) {
		names = append(names, fn.Name.Name)
	}
	sort.Strings(names)
	return names
}

// funcsDeclaredOnType parses EVERY non-test file in this package and returns
// the declarations whose receiver is typeName. Both structural guards read the
// package rather than one file: a role lives in its own file here, so a scan
// pinned to notifying.go would not see the accessor a new role adds — which is
// the one most likely to be written as a delegation.
func funcsDeclaredOnType(t *testing.T, typeName string) []*ast.FuncDecl {
	t.Helper()
	var found []*ast.FuncDecl
	for _, fn := range funcsInPackage(t) {
		if fn.Recv == nil || len(fn.Recv.List) == 0 {
			continue
		}
		if receiverTypeName(fn.Recv.List[0].Type) == typeName {
			found = append(found, fn)
		}
	}
	return found
}

func receiverTypeName(expr ast.Expr) string {
	if star, ok := expr.(*ast.StarExpr); ok {
		expr = star.X
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return ident.Name
	}
	return ""
}
