name: nix build

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'default.nix'
      - 'flake.nix'
      - 'flake.lock'
  push:
    branches: [main]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'default.nix'
      - 'flake.nix'
      - 'flake.lock'
  workflow_dispatch:

env:
  BD_DISABLE_METRICS: "1"
  BD_DISABLE_EVENT_FLUSH: "1"

jobs:
  nix-build:
    name: nix build .#default
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@9adf02b41cfdac2632e1c16f0480ff5bf3b05dd6 # v3
      - name: Build
        run: nix build .#default --print-build-logs
