// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apigen

import (
	"time"

	types "github.com/steveyegge/beads/internal/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ListReadyWorkParamsSort.
const (
	Hybrid   ListReadyWorkParamsSort = "hybrid"
	Oldest   ListReadyWorkParamsSort = "oldest"
	Priority ListReadyWorkParamsSort = "priority"
)

// Valid indicates whether the value is a known member of the ListReadyWorkParamsSort enum.
func (e ListReadyWorkParamsSort) Valid() bool {
	switch e {
	case Hybrid:
		return true
	case Oldest:
		return true
	case Priority:
		return true
	default:
		return false
	}
}

// BondRef A constituent of a compound molecule.
type BondRef = types.BondRef

// ClaimRequest defines model for ClaimRequest.
type ClaimRequest struct {
	// Actor Who is claiming the issue. The server trims it, then refuses an empty result, anything longer than 256 BYTES (the `maxLength` above counts characters — the byte limit is the binding one), and any control character including newline. The value is persisted as the assignee and interpolated into the storage commit message, so an unvalidated newline would forge audit-trail lines.
	Actor string `json:"actor"`
}

// ClaimResponse defines model for ClaimResponse.
type ClaimResponse struct {
	// AlreadyClaimed True when the caller already held the issue and this call changed nothing — the idempotent re-claim. A claim held by a DIFFERENT actor is a 409, not a 200 with this flag.
	AlreadyClaimed bool `json:"already_claimed"`

	// Issue A tracked work item. Property semantics documented here apply to every schema that repeats them below.
	Issue Issue `json:"issue"`
}

// Comment defines model for Comment.
type Comment = types.Comment

// ContextResponse The server's identity handshake. Every member is a deliberate, permanent choice; the field set is an allowlist frozen by a test that checks it against BOTH this document and the generated Go struct, so a field cannot arrive here as a side effect of the server's configuration growing one. In particular the workspace's sync remote is EXCLUDED, in this and every future version, because remote URLs routinely embed credentials — as are the database bind host/port (advertising them invites clients to bypass this API and dial the database directly) and the loopback/non-loopback bind mode.
type ContextResponse struct {
	// ApiVersion The path major this server serves. `v0` for this document.
	ApiVersion string `json:"api_version"`

	// Backend Storage backend name.
	Backend string `json:"backend"`

	// BdVersion The release version of the serving binary. The only field a client may compare as a version, and only for behavioral changes tied to a release.
	BdVersion string `json:"bd_version"`

	// BeadsDir Absolute path of the served workspace's `.beads` directory. A host path, kept because it is the single-workspace server's only workspace-identity handshake; disclosing it to network peers is part of what an operator accepts when binding beyond loopback.
	BeadsDir string `json:"beads_dir"`

	// Capabilities The operations this server actually implements, derived from its route table. v0's vocabulary is `ready.list`, `issues.list`, `issues.get`, `issues.claim`; it grows additively, and an operation never appears here unless it is fully implemented. This is how a client checks for an operation — never the version string.
	Capabilities []string `json:"capabilities"`

	// Database Logical database name (not a host or a DSN).
	Database string `json:"database"`

	// DoltMode Which storage mode this workspace is served from.
	DoltMode string `json:"dolt_mode"`

	// ProjectId Logical project identifier.
	ProjectId string `json:"project_id"`

	// RepoRoot Absolute path of the served repository root. See `beads_dir`.
	RepoRoot string `json:"repo_root"`

	// SchemaVersion The shared JSON schema version — the same constant the CLI's stdout JSON envelope reports. Diagnostic only: it can move for CLI-only reasons with no HTTP wire change, so clients MUST NOT branch on it.
	SchemaVersion int `json:"schema_version"`
}

// Dependency A dependency edge between two issues.
type Dependency = types.Dependency

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Issue A tracked work item. Property semantics documented here apply to every schema that repeats them below.
type Issue = types.Issue

// IssueDetails An `Issue` with its labels, dependency edges and cardinalities — the body of `GET /v0/beads/issues/{id}`. `dependencies` and `dependents` carry FULL issue objects plus the edge type, not bare edges. Property semantics are documented on `Issue`.
type IssueDetails = types.IssueDetails

// IssueWithCounts An `Issue` plus relationship cardinalities. This is the element type of both `/v0/beads/ready` and `/v0/beads/issues`, matching what `bd ready --json` and `bd list --json` emit. Property semantics are documented on `Issue`.
type IssueWithCounts = types.IssueWithCounts

// IssueWithDependencyMetadata A full issue plus the type of the dependency edge that led to it. Property semantics are documented on `Issue`.
type IssueWithDependencyMetadata = types.IssueWithDependencyMetadata

// IssuesPage defines model for IssuesPage.
type IssuesPage struct {
	HasMore bool `json:"has_more"`

	// Items Empty array (never null) when nothing matches.
	Items []IssueWithCounts `json:"items"`

	// NextCursor Present if and only if `has_more` is true. Pass it back verbatim as `cursor` to fetch the next page. Opaque and server-private.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Problem RFC 9457 problem detail. This is the only error shape on this surface. The core declares `type`; this server never emits it, so `about:blank` is implied throughout.
type Problem struct {
	// Assignee With `already_claimed`: the actor currently holding the issue.
	Assignee *string `json:"assignee,omitempty"`

	// Code The stable machine-readable reason, and the ONLY member a client may dispatch on. v0's vocabulary: `invalid_argument` (400, also emitted by the Host-header middleware on any route), `invalid_cursor` (400), `not_found` (404), `already_claimed` (409), `not_claimable` (409), `busy` (503), `db_unavailable` (503), `internal` (500). Renaming or removing a status+code pair is a breaking change; ADDING one is not, so clients MUST default-branch on unknown values and fall back to the status class (unknown 4xx → client bug, fail loud; unknown 503 → retry per `Retry-After`; other unknown 5xx → server fault).
	Code string `json:"code"`

	// Detail Optional prose, never load-bearing. For 5xx codes it is a FIXED string per code and carries nothing about the underlying failure: driver and dial errors routinely embed the DSN, database user and host:port, and this API supports binding beyond loopback. 4xx details reflect the caller's own input back and are specific.
	Detail *string `json:"detail,omitempty"`

	// IssueStatus With `already_claimed` or `not_claimable`: the issue's status at the moment of refusal.
	IssueStatus *string `json:"issue_status,omitempty"`

	// Param With `invalid_argument`: the offending query parameter, body member or header name. Present on every 400 except a body that fails to parse at all.
	Param *string `json:"param,omitempty"`

	// Reason With `invalid_argument`: `unknown_parameter` (this server does not know that parameter — version skew; degrade or fall back) or `invalid_value` (the value is not one this server will act on: malformed, out of vocabulary, or — for `limit=0` under `--allow-non-loopback` — legal but refused in this server's configuration; `detail` says which). Either way `invalid_value` means send something different, never retry the same request. The set may grow; default-branch on unknown values.
	Reason *string `json:"reason,omitempty"`

	// RequestId Opaque correlation id for this request, echoed in the server's request log line. Never a dispatch key and never a retry key. (This server mints per-process ids that do not survive a restart; a deployment may substitute any identifier with the same log-correlation property, such as an edge trace id.)
	RequestId string `json:"request_id"`

	// Status The HTTP status code, repeated in the body.
	Status int `json:"status"`

	// Title The status phrase. Human-facing; never dispatch on it.
	Title string `json:"title"`

	// Type RFC 9457 problem type. This server never emits it, so `about:blank` is implied. A deployment that hosts problem documentation MAY supply it: one stable URI per status+code pair, dereferencing to documentation for that pair. It restates identity that `code` already carries, so a client MUST NOT dispatch on it and a server MUST NOT use it to subdivide a code.
	Type *string `json:"type,omitempty"`
}

// ReadyPage defines model for ReadyPage.
type ReadyPage struct {
	// HasMore True when the limit truncated the result. There is no cursor on this operation; narrow the filters or raise the limit.
	HasMore bool `json:"has_more"`

	// Items Empty array (never null) when nothing is ready.
	Items []IssueWithCounts `json:"items"`
}

// IssueID defines model for IssueID.
type IssueID = string

// InternalError RFC 9457 problem detail. This is the only error shape on this surface. The core declares `type`; this server never emits it, so `about:blank` is implied throughout.
type InternalError = Problem

// InvalidArgument RFC 9457 problem detail. This is the only error shape on this surface. The core declares `type`; this server never emits it, so `about:blank` is implied throughout.
type InvalidArgument = Problem

// NotFound RFC 9457 problem detail. This is the only error shape on this surface. The core declares `type`; this server never emits it, so `about:blank` is implied throughout.
type NotFound = Problem

// Unavailable RFC 9457 problem detail. This is the only error shape on this surface. The core declares `type`; this server never emits it, so `about:blank` is implied throughout.
type Unavailable = Problem

// ListIssuesParams defines parameters for ListIssues.
type ListIssuesParams struct {
	// Status Status filter. Repeat the parameter, or pass a comma-separated list. Custom statuses configured for the workspace are honored.
	//
	// Setting this REPLACES the default status exclusions rather than fighting with them: `status=closed` on its own returns closed issues, and does NOT also need `all=true`. Leave it unset to get the default view described above.
	Status *[]string `form:"status,omitempty" json:"status,omitempty"`

	// Type Issue type. Shorthand aliases are expanded exactly as `bd list --type` expands them (`mr`, `feat`, `mol`, `enhancement`, `dec`, `adr`); there is no plural folding. Unlike on `ready`, an unknown type is a 400 `invalid_argument` with `reason: "invalid_value"`, because `bd list` validates the type against the workspace's configured vocabulary and this operation keeps that behavior.
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Assignee Only issues assigned to this actor.
	Assignee *string `form:"assignee,omitempty" json:"assignee,omitempty"`

	// Label Labels that must ALL be present (AND).
	Label *[]string `form:"label,omitempty" json:"label,omitempty"`

	// LabelAny Labels of which at least one must be present (OR).
	LabelAny *[]string `form:"label_any,omitempty" json:"label_any,omitempty"`

	// ExcludeLabel Labels that must not be present.
	ExcludeLabel *[]string `form:"exclude_label,omitempty" json:"exclude_label,omitempty"`

	// Parent Restrict to recursive descendants of this issue.
	Parent *string `form:"parent,omitempty" json:"parent,omitempty"`

	// All Drop the default status exclusions (closed plus any custom statuses in the done/frozen categories). Redundant when `status` is set, which drops them already.
	All *bool `form:"all,omitempty" json:"all,omitempty"`

	// IncludeTemplates Include template molecules.
	IncludeTemplates *bool `form:"include_templates,omitempty" json:"include_templates,omitempty"`

	// IncludeGates Include gate issues.
	IncludeGates *bool `form:"include_gates,omitempty" json:"include_gates,omitempty"`

	// IncludeInfra Include the workspace's configured infrastructure issue types.
	IncludeInfra *bool `form:"include_infra,omitempty" json:"include_infra,omitempty"`

	// CreatedBefore Only issues created strictly before this instant (RFC 3339).
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`

	// CreatedAfter Only issues created strictly after this instant (RFC 3339).
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// MetadataField Top-level metadata equality filter as `key=value`, split on the first `=`. Repeatable. An invalid key is a 400.
	MetadataField *[]string `form:"metadata_field,omitempty" json:"metadata_field,omitempty"`

	// HasMetadataKey Only issues carrying this top-level metadata key.
	HasMetadataKey *string `form:"has_metadata_key,omitempty" json:"has_metadata_key,omitempty"`

	// Cursor Opaque keyset position, taken verbatim from a previous response's `next_cursor`. Clients MUST NOT construct, parse or mutate it: its encoding is server-private and versioned, and an undecodable or unknown-version value is refused with 400 `invalid_cursor`. The recovery for that refusal is normative: restart paging with no `cursor` at all — the position cannot be salvaged, and re-sending the same value cannot succeed.
	//
	// LIFETIME: a cursor holds a position and a private encoding version, and nothing else. The server keeps no state for it, so it does not expire, does not become invalid when the server restarts, and is not tied to the connection that issued it; the only thing that invalidates one is a change to the encoding, which surfaces as `invalid_cursor`.
	//
	// MISUSE IS NOT DETECTABLE, which is why repeating the filters matters. Because the token carries no filters, a page fetched with a cursor minted under DIFFERENT filters is not refused: the server applies the filters of the current request from the position of the old one, silently skipping every row the new filter set would have placed before that position. Repeat every filter verbatim for the whole traversal, and start a new traversal when they change.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return. `0` means unlimited, exactly as `bd list --limit 0` does — the two surfaces read the same shared default and the same zero semantics, so they cannot diverge. An unlimited page reports `has_more: false` and carries no `next_cursor`. A negative value is a 400.
	//
	// The default below is the shared list limit constant (`workapi.DefaultListLimit`, the value `bd list`'s `--limit` flag registers).
	//
	// One exception, and it is mode-dependent: when the server was started with `--allow-non-loopback`, `limit=0` is refused with 400 `invalid_argument`, `param: "limit"`, `reason: "invalid_value"` and detail "unlimited reads are loopback-only; pass an explicit limit". An unlimited read buffers the whole active set and its JSON encoding inside one shared process, which must not be reachable by arbitrary network peers. The bind mode is deliberately NOT advertised in `ContextResponse` — a client that wants an unlimited read asks for one and, on that 400, re-issues with an explicit limit (and pages with `cursor`); it is a client-side fix, never a retry.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListReadyWorkParams defines parameters for ListReadyWork.
type ListReadyWorkParams struct {
	// Assignee Only issues assigned to this actor.
	Assignee *string `form:"assignee,omitempty" json:"assignee,omitempty"`

	// Unassigned Only issues with no assignee.
	Unassigned *bool `form:"unassigned,omitempty" json:"unassigned,omitempty"`

	// Type Issue type. The only normalization is shorthand ALIAS expansion, exactly what `bd ready --type` does: `mr` → `merge-request`, `feat` → `feature`, `mol` → `molecule`, `enhancement` → `feature`, `dec`/`adr` → `decision`. Every other value is used as written — there is NO plural folding, so `bugs` is not `bug`.
	//
	// An unrecognized type is not an error here: the type vocabulary is workspace-configurable, and `bd ready` does not validate it either, so it simply matches nothing and `items` comes back empty. (The list operation differs — `bd list` DOES validate the type, so `GET /v0/beads/issues?type=bugs` is a 400.)
	//
	// When set, `exclude_type` is ignored, and so are the default type exclusions described above.
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// ExcludeType Issue types to exclude. Repeat the parameter, or pass a comma-separated list. Ignored when `type` is set.
	ExcludeType *[]string `form:"exclude_type,omitempty" json:"exclude_type,omitempty"`

	// Label Labels that must ALL be present (AND).
	Label *[]string `form:"label,omitempty" json:"label,omitempty"`

	// LabelAny Labels of which at least one must be present (OR).
	LabelAny *[]string `form:"label_any,omitempty" json:"label_any,omitempty"`

	// ExcludeLabel Labels that must not be present.
	ExcludeLabel *[]string `form:"exclude_label,omitempty" json:"exclude_label,omitempty"`

	// LabelPattern Glob matched against labels.
	LabelPattern *string `form:"label_pattern,omitempty" json:"label_pattern,omitempty"`

	// LabelRegex Regular expression matched against labels.
	LabelRegex *string `form:"label_regex,omitempty" json:"label_regex,omitempty"`

	// Priority Exact priority (0 is a real value, not "unset").
	Priority *int `form:"priority,omitempty" json:"priority,omitempty"`

	// Parent Restrict to recursive descendants of this issue.
	Parent *string `form:"parent,omitempty" json:"parent,omitempty"`

	// MetadataField Top-level metadata equality filter as `key=value`, split on the first `=`. Repeatable. An invalid key is a 400.
	MetadataField *[]string `form:"metadata_field,omitempty" json:"metadata_field,omitempty"`

	// HasMetadataKey Only issues carrying this top-level metadata key.
	HasMetadataKey *string `form:"has_metadata_key,omitempty" json:"has_metadata_key,omitempty"`

	// IncludeEphemeral Include ephemeral (non-synced) rows.
	IncludeEphemeral *bool `form:"include_ephemeral,omitempty" json:"include_ephemeral,omitempty"`

	// IncludeDeferred Include issues whose `defer_until` is still in the future.
	IncludeDeferred *bool `form:"include_deferred,omitempty" json:"include_deferred,omitempty"`

	// Sort Ready-work ordering. `priority` is priority-first; `hybrid` orders recent issues by priority and older ones by age; `oldest` is creation order. An unrecognized value is a 400.
	//
	// The default is the one `bd ready --sort` registers, so a client swapping `bd ready --json` for this operation gets the same items in the same order. The storage layer treats an EMPTY policy as `hybrid`, but that fallback is unreachable from the CLI and is NOT this parameter's default: `hybrid` demotes older high-priority work, so defaulting to it would change the item SET as soon as `limit` truncates — silently, and only for the clients this API exists to migrate.
	Sort *ListReadyWorkParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Limit Maximum number of items to return. `0` means unlimited, exactly as `bd ready --limit 0` does — the two surfaces read the same shared default and the same zero semantics, so they cannot diverge. A negative value is a 400.
	//
	// The default below is the shared ready-work limit constant (`workapi.DefaultReadyLimit`, the value `bd ready`'s `--limit` flag registers).
	//
	// One exception, and it is mode-dependent: when the server was started with `--allow-non-loopback`, `limit=0` is refused with 400 `invalid_argument`, `param: "limit"`, `reason: "invalid_value"` and detail "unlimited reads are loopback-only; pass an explicit limit". An unlimited read buffers the whole active set and its JSON encoding inside one shared process, which must not be reachable by arbitrary network peers. The bind mode is deliberately NOT advertised in `ContextResponse` — a client that wants an unlimited read asks for one and, on that 400, re-issues with an explicit limit; it is a client-side fix, never a retry.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListReadyWorkParamsSort defines parameters for ListReadyWork.
type ListReadyWorkParamsSort string

// ClaimIssueJSONRequestBody defines body for ClaimIssue for application/json ContentType.
type ClaimIssueJSONRequestBody = ClaimRequest
